### ISSUE TITLE
upgrading from 1.11.2-0.7.777 to 1.11.2-0.7.1091 causes multiple problems

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1006]
### Minecolonies version

version 1.11.2-0.7.1091

### Expected behavior

- upgrade without issue

### Actual behaviour

- A user of my modpack Colonial Expansion reported the following 
`Just updated from 2.2.0 to 2.3.0

 

I lost ownership of my colony 

My wife and I both logged in with only a single hamhock where as we had full hunger before the upgrade

We cannot eat

Vanilla Bread recipe is missing / disabled.

 

Very confused...`

### Steps to reproduce the problem

- upgrade from 1.11.2-0.7.777 to 1.11.2-0.7.1091

### logs

- the user of my pack didn't report any crashes so I asked them for their fml logs for both the client and the server if they were using one from before and after the upgrade.

1. client fml before upgrade https://gist.github.com/kreezxil/60f879eb740149fdaa0d13353e0cbe4c
1. client fml after upgrade https://gist.github.com/kreezxil/afe96e72ae2f56fdbe9d57d4a0dd58d9

1. server fml before upgrade https://gist.github.com/kreezxil/91fedd5d909a1347ed9f22067f255386
1. server fml after upgrade https://gist.github.com/kreezxil/83d22ee9f5ec55d1c62ce3e16cce9c48

**Comment by Raycoms** [comment]
That does seem to happen occasionally when relogging upgrading etc.

Tell your users to try to: Restart the world
type /mc colony refresh 1

(or /mc colonies list to get the id and then /mc colony refresh id)

They lost ownership of the colony that's why they are not able to eat.

2017-05-16 10:37 GMT-03:00 kreezxil <notifications@github.com>:

**Comment by Raycoms** [comment]
Still happening? Please reopen if yes
