### ISSUE TITLE
[BUG] Cookery block doesn´t work

### ISSUE THREAD

**Issue by LucaFerrarezi** [ldtteam/minecolonies#10166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.647

### Structurize Version

1.20.1-1.0.752

### Current Behavior

My cookery doesnt´work anymore, i have updated the mod and the cookery stopped work, it just say in the chat that the cookery can´t find the structure. It doesn´t open the HUD anymore and the npc doesn´t work.
![2024-08-25_14 03 36](https://github.com/user-attachments/assets/ce87a245-c6c4-4f33-b82e-5712c10f2953)

### Expected Behavior

I expect the cookery returns to work normally.

### Reproduction Steps

I just updated the mod to the new version. The problem started in the update form day 8/22/2024. I have waited for the new update to see if it would work, but it doesn´t.

### Logs

I don´t have any logs, just the screenshot

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
To properly diagnose your issue the latest.log is needed. 
You can generally find the log in your game or server directory under the logs folder. The file latest.log is most likely required.
Once you've found this file please post it on a paste site. As a team we recommend https://gist.github.com/.

**Comment by LucaFerrarezi** [comment]
https://gist.github.com/LucaFerrarezi/019fdb584a35034df2c31098edb7437d
The latest log from my modpack

**Comment by Talyda** [comment]
Gonna copy paste this here from discord. You're using the two mods mentioned below, that can cause a lot of problems.

Unfortunately some addons modify Minecolonies in a reckless way, causing both stability and performance issues. Due to this, we cannot give support when something does not seem to work correctly when those mods are installed.
Please try to reproduce it without those mods installed (make a backup of the world first!)
This applies especially to the two following addons:
- Tweaks addon for MineColonies
- Compatibility addon for MineColonies
We advise users and packmakers to remove these mods from their packs as the addon authors do not seem to be willing to do their changes in a responsible way, therefore harming our ecosystem.
Note that removing those mods may interfere with the request system, which could cause crashes. This can be solved with `/mc colony requestsystem-reset-all` on the server, or via the steps in the following discussion in singleplayer: https://discord.com/channels/139070364159311872/1125094832143077456/1275179301922410629.
