### ISSUE TITLE
Offset texture in Female Stone Smelter's skin

### ISSUE THREAD

**Issue by vectorwing** [ldtteam/minecolonies#10241]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.673-snapshot

### Structurize Version

1.0.755-beta

### Related Mods and their Versions

**Forge:** 47.3.6
**BlockUI:** 1.0.186-beta
**Domum Ornamentum:** 1.0.203-beta

### Current Behavior

There seems to be a minor texture offset in the head model of the female Stone Smelter.
![Stone Smelter](https://github.com/user-attachments/assets/6ca2579a-7f1c-4207-bc3b-894886e11918)

As far as I was able to check, this is the only job with this texture bug; other jobs seemed to have correct UV's. I'm also not sure if this applies exclusively to this ethnicity variant, or for other models as well.

### Expected Behavior

There should not be a transparent gap in her chin.

### Reproduction Steps

1. Hire a female citizen as a Stone Smelter;
2. Check the underside of her head.

### Logs

https://pastebin.com/gNywHTss

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@Imrielle

**Comment by Imrielle** [comment]
Theres a lot wrong with this model in the screenshot - aside from the head, the skirt is broken, its missing the bottom two pieces of the apron, its rendering part but not all of the second head layer, the glasses are missing.

Looking at the [entity model in the codebase](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/client/model/FemaleCrafterModel.java) for the NPC/gender and comparing it to both the BBModel _and_ a fresh export of the Java model - none of this is there. The textures are also correct. There have been no changes to either of those for several months, so that was to be expected.

Are you using any other mods that affect textures or model rendering? I'll make a fresh instance with your exact versions and any mods you may have that affect rendering or textures later today and test in-game.
