### ISSUE TITLE
Request: Make workers ignore buildings as waypoints except as a final destination

### ISSUE THREAD

**Issue by Amadeus99** [ldtteam/minecolonies#1053]
It is a little disconcerting to see workers, for example, go through a line of 4 citizen huts before stopping at the last one which is apparently their home.  I have decorations->waypoints->waypoint 6 blocks in front of each door to each hut, but they usually, not always, ignore those waypoints.  I also see workers go in and out of my deliveryman huts on their way to wherever they need to go.  Those huts also have waypoints 5 blocks from the doors.

If workers would ignore buildings as waypoints or prioritize decoration waypoints, then this shouldn't(tm) happen anymore.  Of course, workers should still use a building as a waypoint if it is their final destination, or perhaps if there are no player placed waypoints.

Thanks.

**Comment by Raycoms** [comment]
They actually don't prioritize anything, they use the waypoint with the
best heuristic to the goal, it seems like your player placed waypoints have
a worse heuristic.
Have you read our waypoint guide on the wiki?

2017-05-22 18:30 GMT-03:00 Amadeus99 <notifications@github.com>:

**Comment by cltnschlosser** [comment]
Our heuristic is a bit strong. Which is good for saving CPU cycles, but bad for finding the best path. Walking through a building (with walls) is unlikely to be an optimal path, because we will just have to walk back out.

I haven't looked into the waypoint system at all, but I think having huts as waypoints isn't the best idea.

**Comment by Amadeus99** [comment]
I just read the wiki.  I still can't see how to get the workers to follow a neatly laid out road system.  I have 4 citizen huts going N to S.  Each Citizen's Hut block is 18 blocks from each other.  My road is on the west side of the huts, the center of which is 9 blocks from the hut block.  Once a guard that is on automatic patrol goes into one hut, he will then hug the wall to go to the next hut.  I can't seem to get them to go back out to the road.  I also can't see a way to remove custom waypoints to try and play around with them better.

**Comment by Raycoms** [comment]
You just change the block the custom waypoint is in. After 5 seconds it
will get removed.

2017-05-22 19:14 GMT-03:00 Amadeus99 <notifications@github.com>:

**Comment by Raycoms** [comment]
Hmm hugging the wall is not intended, they should recognize a better path
since they can't walk this way.
I added some optimizations so that the worker should recognize that he is
close enough to the goal to not pursuit the way into the building, but it
seems like the check isn't made often enough so he actually runs often
inside the buildings, there is still some room for optimizations.

2017-05-22 19:28 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by cltnschlosser** [comment]
Also they weren't prioritizing roads before, that will be fixed, and should help some. See #1054 which has new code to prioritize roads (as you can see, some work is needed still).

**Comment by Amadeus99** [comment]
From what I've read before, citizens will go to 5 blocks from a way point and then move on to a different way point.  Could we have a config option to change that?  I would like to set it down to 1 block but that is a personal preference and thus a config option would be nice.  Although, if you make changes that cause citizens to always stay on paths until pretty much the last moment, then this probably won't be needed.

**Comment by Raycoms** [comment]
Could you open a new issue for that?
