### ISSUE TITLE
[1.10.2] Crash loading savegame

### ISSUE THREAD

**Issue by MokahTGS** [ldtteam/minecolonies#1061]
### 1.10.2.0.8.1536

https://pastebin.com/ummXYtqT

Getting this crash when loading a savegame with a previous version.

**Comment by MokahTGS** [comment]
I've had to completely remove MCol from my modpack as it won't let the savegame load.  I'd like some advice as to what went wrong.

**Comment by Raycoms** [comment]
Will be able to take a look at it tomorrow morning and try to push a fix.
It seems to be related to the farmer hut.

2017-05-24 15:37 GMT-03:00 MokahTGS <notifications@github.com>:

**Comment by MokahTGS** [comment]
When you do, can you post and let me know what happened?  I'm building a modpack for future public use and I'm curious as to what causes these issues...especially in big packs.

**Comment by cltnschlosser** [comment]
@MokahTGS Well this specifically happened because a field associated with a farmer was deleted (or atleast the TileEntity for the scarecrow was), and the Farmer hut was deleted(broken), close enough together that they happened in the same game tick.

The crash is because the error checking code for this isn't very good.

I'm guessing you loaded this world without minecolonies (so the TileEntities were deleted), and then again with minecolonies, so we tried to clean up the building that had missing TileEntities, but our error checking failed.

EDIT: I'll try to get a fix for you tomorrow, its pretty simple. We just need to get our current build issues sorted out.

**Comment by MokahTGS** [comment]
Odd because that crash happened before i removed anything.  So something got messed up first.

**Comment by cltnschlosser** [comment]
Could you do me a favor and see if this fixes your issue? https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_PullRequests/1847/minecolonies-universal-1.10.2-0.8.1847.jar

**Comment by marvin-bitterlich** [comment]
fixed in alpha
