### ISSUE TITLE
[request] prevent villages from be captured by townhalls

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1116]
Would be awesome if you could add a feature where when a town hall is placed such that encompasses a village, that the village remains public access. Better yet, the town hall refuses to place because it overlaps the village.

**Comment by AndrewTru** [comment]
@kreezxil If the team did that the blocks that are used in its construction will be prevented as well, there is arady and in game way to do it, just update the 'dirt' listing in the mod settings with the blocks in question, again this will make it so that if the blocks are used in the town every player will be able to interact or mine them and that will be a security issue come night time. just saying there are some thing to think about when making a request of this type.
@Kostronor What's your take on this?

**Comment by Raycoms** [comment]
Sorry for the late response.
I think thats for sure something we can have configurable in the config.
As far as I know there is a way to find the size of a village.

**Comment by kreezxil** [comment]
That would mean they Minecraft stores data on The Villages this is so epic
can't wait but will thank you

**Comment by xavierh** [comment]
Yes it does bit why would you want to prevent it?
Anybody can create a village with a villager breader. Preventing to capture one will not change that.

**Comment by marchermans** [comment]
Yes you can check if you are in range of a village

**Comment by kreezxil** [comment]
It's really part of a larger problem. Had players that were exploring and
when they needed to eat they couldn't because of the protection. You should
be able to eat your own food. However just the same I think you should be
allowed to interact with villagers regardless of who plopped a town hall on
top of them. Further in my case I also it's Toro quest and as such my
villages also have village lords that give quests can't be accessed because
of the protections. The sand thing for Bailey's Dailies which is another
mod that gives quests from inside a village.

In my case preventing village capture is ideal and once this capability is
possible a single config could be added to turn it on.
