### ISSUE TITLE
Lumberjack doesn't harvest fruit from Pam's Harvestcraft trees.

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1147]
https://github.com/MatrexsVigil/harvestcraft/issues/295

**Comment by Wissi** [comment]
This isn't an Issue with mod. It's not his job, sorry. He's a Lumberjack not a "farmer" or "tree fruit picker".

If you want to suggest that there be an option for a worker for a specific mod, not sure developers will want to do it atm.

Might want to change the Title to something like:

Suggestion: worker to interact with Pam's harvest Fruit tress.

**Comment by kreezxil** [comment]
if you click on the harvestcraft link and then the fast leaf decay link that is there you see that I am reference all three mods. This is not a request, I am reporting what feels like a bug.

All you have to say is "this is not a bug" and tag as such, maybe "invalid", "won't fix", "not a bug" and then close it. Oh wait you're not a developer ... does your opinion even matter?

**Comment by Raycoms** [comment]
That's quite interesting, I feel like harvestcraft should make them drop.
The lumberjack is not supposed to be a fruit-tree farmer.
We might in the farther future add a fruit-tree farmer which might work on
this.
But for the time being, I feel like we won't add support to this, since its
not in accordance with the lumbejack job itself.

Would be nice if harvestcraft makes them drop on harvest trees.

Wissi is not a developer but he takes part of our development team, so his
answers usually also count.

2017-06-09 21:50 GMT-03:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
That's cool. Appreciate  your feedback on this Raycoms. Not to come across as well cross but I guess I am, it doesn't seem to be good policy for someone to suggest that a bug report be put across as a suggestion. I've made suggestions/requests before, not sure if I've done it here, but it has been my standard practice to put [suggestion] or [request], I use the latter when I think it would really be beneficial and the former when it might possibly enhance.

I agree tho, Pam's Harvestcraft should make the fruit fall when the leaves attached to it are no more.

**Comment by Raycoms** [comment]
@kreezxil did you report that to Pam?
