### ISSUE TITLE
Improved D-man Delivery to Builder

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#1173]
Comment from one of my YouTube Channel Subscribers..

Can you make it so that Deliveryman would fetch items to the Builder hut when they are in the queue for building, but not begged by the builder yet. It's annoying how slow the process of building might sometimes be)﻿

Sounds like a reasonable thing to me.. Any chance we can do this?

Thanks :)

**Comment by SulpherStaer** [comment]
It already does that, as far as I know...

**Comment by pmardle** [comment]
Not as far as I am aware.. the D-man will deliver materials when the builder calls for them, but wont "look ahead" as to what is required for the current build and deliver them.  means builder is sitting idle each time until the d-man fetches and delivers the item

**Comment by xavierh** [comment]
The problem at the moment is that the builder does only know what he currently need but not what he will need next.

**Comment by xavierh** [comment]
the list of needed item is not:
- complete, place holder are not taken into account which is why the builder may ask for dirt which is not in the list
- ordered

If we do implement that I suggest that the builder request depending of the hut level:
- level 0 only the current item
- level 1 current item + next item
- level N current item + the Nth next one

In a similar fashion, the dman should deliver Nth +1 stack with N being the dman hut level

**Comment by pmardle** [comment]
Something must know what is needed next (or at least some point in the
build) as we have the list..

I'm happy for the d-man to just deliver "something" that is needed -
doesn't have to be the actual next thing needed - it will all speed it up a
bit.  As long as the actual thing asked by the builder takes preference
then it should still help overall.

**Comment by marchermans** [comment]
I think this is something for the new request system

**Comment by marchermans** [comment]
I think this is something for the new request system

**Comment by Raycoms** [comment]
Closed in favor of new issue soon.
