### ISSUE TITLE
Waypoints on bridges are in the wrong place

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#1262]
### Minecolonies version

version .0.8.2797 or curse X.X.XX

### Expected behavior

- Expect the colonists to walk across the bridge

### Actual behaviour

- colonists go under the bridge (the waypoints are set for the bottom row of the bridge (in the water) instead of up on the wood
![2017-07-06_22 18 20](https://user-images.githubusercontent.com/29446488/27940583-7c6518bc-6299-11e7-8ff7-af9cc608fc10.png)

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Yeah that's because of the way we calculate the waypoints (they are added
automatically in the center of the structure) We will have to invent a
waypoint placeholder for schematics.
Which would be AWESOME for the worker huts as well.
I'll open an issue for that.

2017-07-06 23:22 GMT-03:00 lunadragnstar <notifications@github.com>:

**Comment by Raycoms** [comment]
Closing in favor of: https://github.com/Minecolonies/minecolonies/issues/1263
