### ISSUE TITLE
better building want selection for schematics

### ISSUE THREAD

**Issue by Goten87** [ldtteam/minecolonies#1286]
### Minecolonies version

version 1.11.2-0.8.3123

### Expected behavior

- way to set schematics in main folder (befor decorations)
i like to have more then 1 road system for exemple stone brick road marble road enz enz enz
will like to have or more selection tools or to have the option to set the schematics in the root folder so befor decorations

### Actual behaviour

- your own schematics will always go into decorations folder

### New selection tool
will be nice if we just have a drop down menu with the items expending to the right
so main tree->Road tree->stone tree->road u want to pick

**Comment by Wissi** [comment]
There actually is a folder separate from Decorations called: My Schematics.

This is where all of your personal scans will be and you can rename then however you like. Check out all the info in the Official WIKI:

https://wiki.minecolonies.com/wiki/22/schematics

Your personal scans are not in "My schematics"? but instead are in "Decorations"? That would be an issue, because by default all your scans will go to My Schematics.

**Comment by Goten87** [comment]
if i put my own schematics in the folder `<root>/Minecolonies/schematics` then it will show up in decorations and not in my schematics or what ever i want to have it in the root as well do we have the decorations tab to be the start of the schematics folder for your self

**Comment by xavierh** [comment]
https://wiki.minecolonies.com/wiki/22/schematics#scanfolder

**Comment by Goten87** [comment]
i dont think u get the point :P i want to have the items in the root
so that i can do Greenhouse->stone/wood->level 1-5 for exemple
now its decorations->greenhouse->level 1-5

**Comment by Raycoms** [comment]
As far as I know you can sort them like you want like decorations -> greenhouse -> stone -> 1-5
