### ISSUE TITLE
Warehouse Full 

### ISSUE THREAD

**Issue by jc4me** [ldtteam/minecolonies#1315]
### Minecolonies version

version 0.8.8.3 or curse X.X.XX

### Expected behavior

- Delivery man sending material into warehouse 

### Actual behaviour

- Runs into warehouse then runs out without doing anything, currently just running around doing nothing.
- keepings saying "warehouse full or upgrade"
It is already level 2 warehouse, and there is nothing in it

### Steps to reproduce the problem

Not sure what is happening.

**Comment by Asherslab** [comment]
Update to latest version and repair your warehouse

**Comment by Electrocutor** [comment]
Repairing the warehouse worked for a few hours, but then the same request comes in again that the warehouse is full and needs to be upgraded even when its empty.

**Comment by Asherslab** [comment]
@Electrocutor So does it fix it every time it's repaired? I.E. When you repair it, does it fix it, until a restart or something similar?

**Comment by Electrocutor** [comment]
"Please upgrade or build a Warehouse for me to work at"
This message is different from the "is full" message.

I did not notice the message immediately after server reboot; but shortly after logging in about an hour later. The deliveryman then proceeded to use the Warehouse without issue, even without needing to be repaired again.

I also keep getting messages from the fisherman saying that the hut is too far from water.

I believe these are both being caused by chunks not being loaded. The deliveryman loads, but the warehouse has not; the fisherman loads, but the fisherman hut or water body has not.

If I log out for a while and then come back on, both of these message repeat themselves. It also happens if I walk a long distance away from the colony and then return.

**Comment by Asherslab** [comment]
Ooooh, so is the warehouse still being used? Or is it not being used the whole time you're logged in (even if you make sure the warehouse is loaded)

**Comment by Electrocutor** [comment]
If I am near the warehouse, then it's used; if I go to the edges of my colony, then it despawns and then I get the message again (and the deliveryman just stands there like he has nowhere to go).

**Comment by Asherslab** [comment]
Oh, lol, then it's not a bug. Although we should probably fix the message so there isn't spam when it's unloaded.

**Comment by Electrocutor** [comment]
I would agree; and as I said, I believe that the fisherman not finding water is being caused by the same thing.

**Comment by Raycoms** [comment]
The please upgrade message appears sometimes but shouldn't cause anything

**Comment by Electrocutor** [comment]
Okay, so it seems I discounted this prematurely. The deliveryman has now several times asked me to 'upgrade or build a warehouse for me to work at' while I was in fact standing within the warehouse itself. Thus, while there may be some false messages due to chunk loading, this is still an issue given some unknown conditions. I've not been able to figure out the pattern that causes it though.

**Comment by Raycoms** [comment]
These messages might appear once in a while, what matters is if he stops
working?
