### ISSUE TITLE
Tinkers Construct Tools once broken are not being handled correctly.

### ISSUE THREAD

**Issue by redtonM** [ldtteam/minecolonies#1336]
### Minecolonies version

Minecraft Version: 1.10.2
 Direwolf 20 1.10.2

### Expected behavior

When a tinkers tool breaks - The delivery man should pickup the tool and put it back in the warehouse for repair and not pickup any broken tools.  Then if any usable tool exists in the warehouse should deliver it.

### Actual behavior
The delivery man never collects the broken tools in many situations.  Also in some instances the broken tool is continued to be tried to use.  The NPC ask for diamond version since it's working with broken tool.  Other things I seen delivery NPC not notice a hatchet from Tinkers is a valid axe or deliver tools. 

### Steps to reproduce the problem
Give any NPC a broken tinkers item.

**Comment by Electrocutor** [comment]
In all honesty, the pick-up/drop-off AI for the deliveryman needs a good overhaul; he's pretty much nonsensical at the moment. He'll spend most of his time taking away the tools from a worker hut that they need and taking away the extra food from houses instead of picking up the resources they've cut/mined/crafted/looted.

I usually have to go and supply things to worker huts like tools and materials from the warehouse myself because the deliveryman is too busy doing senseless things. :-/

**Comment by ghost** [comment]
I had an idea that would him be more like a real mailman. Posted it here: https://github.com/Minecolonies/minecolonies/issues/1337

**Comment by Raycoms** [comment]
Will open a separate issue for that soon.
