### ISSUE TITLE
Builder won't build

### ISSUE THREAD

**Issue by RickArcee** [ldtteam/minecolonies#1344]
### Minecolonies version

version 1.10.2

### Expected behavior

-Builder should build decorations, work order should be created.

### Actual behaviour

- Won't build decorations at a certain distance. The work order is not created

### Steps to reproduce the problem

It seems that my new LvL 2 builder won't build above 100 blocs from town hall book... The bridge I want to build is 120 blocs away from Town hall book and only 20 blocs from the builder's hut.

**Comment by Raycoms** [comment]
That is 100% correct and intended behavior. None of your workers should be
allowed to operate outside of the colonies borders. You want to have them
work farther than 120, increase the colony size

On Aug 5, 2017 13:42, "RickArcee" <notifications@github.com> wrote:

Minecolonies version

version 1.10.2
Expected behavior

-Builder should build decorations, work order should be created.
Actual behaviour

   - Won't build decorations at a certain distance. The work order is not
   created

Steps to reproduce the problem

It seems that my new LvL 2 builder won't build above 100 blocs from town
hall book... The bridge I want to build is 120 blocs away from Town hall
book and only 20 blocs from the builder's hut.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/1344>, or mute the
thread

**Comment by RickArcee** [comment]
Thank you very much for your quick answer. But how do i increase the colony's size? The town hall is lvl 4 and i have 10 citizens.

**Comment by Raycoms** [comment]
That's defined in the config file which is located in the config folder.

**Comment by Raycoms** [comment]
minecolonies.cfg

**Comment by RickArcee** [comment]
Thank you!
