### ISSUE TITLE
[Enhancement] Additional Placeholder Blocks

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#1345]
### Primary Placeholder Blocks
Additional placeholder blocks would be added to the mod to allow for scanning and substitution depending on biome.

While it would require some discussion as to how many placeholders would be needed, I am seeing along the lines of the following:

PrimaryMaterial
- Base
- Frame
- Primary
- Detail
- Stair
- Slab
- Fence
- Window
- Door

Depending on the biome, these may be a mix of wood, stone, snow, sandstone, netherbrick, purpur, etc. If you wished, these replacements could even be level-dependent, so anything made of Primary might be Oak wood at level 1, Cobblestone at 3, and Stone Brick at 5.

These placeholders could then be used not only in styled and first-level hut designs, but in custom scan buildings, and sub-schematics like miner shafts and tunnels as well.

If you're interested in this, I could write up an XML to translate each biome into which blockids for each placeholder to start off, then you could make revisions as necessary.

This would also allow the Style category for schematics to actually be about styles instead of building materials. While things like flat roofs in deserts would still require a different style of building, for the most part the same schematic could be used for every biome and it would look like it belonged there as well as the primary materials to build it would be local.

### Addendum: Revision of Existing Placeholder Block
The existing solid placeholder substitution would also need to be updated to Netherack when built in nether, Stone when built underground, etc.

**Comment by Raycoms** [comment]
I think that would require too many hardcoded values.
The correct thing would be to have an own style for each own biome.
Because each biome does also somehow fit better with certain styles.

In this case we're happy if the community contributes with those, so we might add them to the official pack.

**Comment by Electrocutor** [comment]
There are 62 biomes in minecraft with differences in which resources they carry for most of them...

Also, I had said configured in XML; which is not hard-coded. I'll just take it that there is no interest in dynamic schematics from the team.

**Comment by Raycoms** [comment]
The idea about the schematics is letting the user choose what kind of style
will be built, independently from where he is  and yeah there are 62 biome
but in the end a lot of the biome a are really similar so we would need
like 15-20 styles which would be great to have.

On Aug 13, 2017 04:08, "Electrocutor" <notifications@github.com> wrote:

There are 62 biomes in minecraft with differences in which resources they
carry for most of them...

Also, I had said configured in XML; which is not hard-coded. I'll just take
it that there is no interest in dynamic schematics from the team.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/1345#issuecomment-322026064>,
or mute the thread

**Comment by hron84** [comment]
Biomes could be categorized by their properties. Take a look into how Forestry does this for its bees. We can gather certain conditions from the biome and figure out what styles could fit, for example (taking Forestry categorization): hot and arid biomes could less prefer wooden buildings, however cold biomes should always take account to snow/ice buildings. Nether and End could be determined either by their dimension ID, or some worldgen properties (to take account for custom dimensions like RFTools/MystCraft). If we restrict the 62 builtin and plethora of modded biomes into few categories, it could be easier for schematic handling.
