### ISSUE TITLE
Villagers got scrambled

### ISSUE THREAD

**Issue by XentoniX** [ldtteam/minecolonies#1455]
### Minecolonies version

version 1.12.1-0.8.3977

### Expected behavior

- Just working

### Actual behaviour

- Boot up fine but all citizens have scrambled. Guards are builders. Builders are bakers etc.

### Steps to reproduce the problem

Update from 3861 to 3977

**Comment by Asherslab** [comment]
@Raycoms i've also noticed a lot of weird things with Citizens and Jobs since the barracks came around.
E.G. Hiring (manually) a citizen for my herders, and they're in full guard uniform (And they do absolutely nothing) or sometimes certain civilian ones won't do anything useful for any buildings i hire them in. (No error logs, i checked)

**Comment by Raycoms** [comment]
Oh damn, I think going from a pre barracks version to the barracks version
can scramble up their jobs since we reworked them.
So the workers will load with their jobs but their buildings will load
empty and will try to assign new workers to them which causes this issue.
Damn, should've added a fix in code which loads the old workers as well...

2017-09-18 11:53 GMT+01:00 Asherslab <notifications@github.com>:

**Comment by XentoniX** [comment]
Ah ic. All Lvls were reset too. Builder went to lvl0 from 17.  Probably Same issue with not loading the villagers correct.

**Comment by Rosomah** [comment]
Yeah, the same happened to me when updating to the barracks version in 1.10.2

**Comment by Raycoms** [comment]
I created a fix I will merge soon, could you try to reset the minecolonies.dat to a moment things were still working and then load that version?

**Comment by Raycoms** [comment]
Try out this one for 1.10 @Rosomah https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/3992/minecolonies-universal-1.10.2-0.8.3992.jar

**Comment by Raycoms** [comment]
I created a fix for that will upload it soon. You should be able to fix it
then using an older minecolonies.dat

**Comment by Raycoms** [comment]
Should be fixed.
