### ISSUE TITLE
mc 1.12.1 some issues 

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [ldtteam/minecolonies#1528]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.4288.jar ; mc 1.12.1 , forge-1.12.1-14.22.1.2485, SURVIVAL only
https://imgur.com/a/g0SgS

1; delivery
- dumps his own inventory to e.g. builder chest, before recollect all
   result: message : could not deliver because chest full
- don't distribute FOOD, he itself get starved
- do not deliver ARMOR and WAPPONS to Guards 
- always take one stack ( if possible) instead of e.g. 5 items to deliver to BUILDER 
       ( monitored by RFTOOLS Inventory scanner in warehouse) 
- don't visit BARRACKS TOWER chests
- stops sometimes for Loong time , maybe "thinking" 

_____________________________________________________________________________
2: Guard ( in Barn as Patrol)
- do not drop Swords etc. gotten from raiders
_____________________________________________________________
3; general colonists ;
- colonists do not keep their FOOD , the eat some and drop the rest to their chests
- they don't use PATH's ( build by builder ) 
- if two of them try to pass single door, none will pass
        you have to build a 2-door entry to avoid 

### Expected behavior
- should work like intended
### Actual behaviour
- see above
### Steps to reproduce the problem

go to your testworld 

all others behave like they should ( farmer , miner, lumber, fisher , builder, baker )

regards from the town of the one and only real oktoberfest

**Comment by Raycoms** [comment]
Okay to 1) This will be fixed with the new request system we're working on

to 2) I didn't understand, you mean they don't dump them int he chest?

to 3) 
a) In the next update this will be fixed (including the cook).
b) They use the paths but only if it makes sense pathing wise
c) There is also an issue for that already. (Worker locomotion)

Please reopen an issue for each of the points, if they haven't been responded by this answer here or if they don't have an issue yet.
