### ISSUE TITLE
Colonists Duplicated by Scan/Build Process

### ISSUE THREAD

**Issue by GrandOmega** [ldtteam/minecolonies#1531]
### Minecolonies version

version 1.10.2-0.8.4234

### Expected behavior

- Scanned building for duplication (a tunnel corner in this case after placing Waypoint within), Builder stood inside. Presumed scanner would ignore Builder.

### Actual behaviour

- Builder's name was visible during blueprint placement within building. Builder was duplicated during building construction - inventory, name, stats, employment (cloned Builder and original both work at same builder hut and seem to alternate work when other needs supplies).

### Steps to reproduce the problem

1. Tunnel was 3x3 wide at corner point with 3x3 wide corridors leading away, with separate waypoint placed within.
2. Waypoint was final construction order for town, Builder stayed inside tunnel since they didnt have other work.
3. Tunnel section scanned as per manual instructions (corner to corner).
4. Construction begins as usual, with duplicate Builder created during 'decoration' placement.

Note: Was done in a Superflat Creative world and did work to duplicate second, different Builder. Now have clones of both. Original and Clone will both work on a project if they both have the parts in their inventory, effectively doubling construction speed if kept supplied. Duplicate Builders don't seem to exist within Colony Information - colony sees 2 Builders, not 4, and number of colonists doesn't exceed colony maximum.

**Comment by marchermans** [comment]
Yeah, it just scans all entities within the defined range. Including any citizen, which is done on purpose for Creative building.
Since it literally duplicates all entities (including their data), the effects that you are seeing are indeed possible, the Colony only knows the original Builder, but since the duplicate shares the same CitizenID and data structure, they behave like identical twins of some sorts, and the colony can not differentiate between them.

Just kill the builder next time when you build that structure.
