### ISSUE TITLE
[suggestion] Config to specify blocks for the delivery guy to take items from

### ISSUE THREAD

**Issue by winsrp** [ldtteam/minecolonies#1554]
Lots of mods have custom containers, chests, interfaces etc, so it would be nice to have a option in the config file to specify blocks that store items, where the delivery guy could take items from....

On this example popular mods like iron chests, refined storage, rftools, actually aditions, immersive engineering, drawers, etc etc, could have entries in the config file for the guy to look into this blocks that contain items.

I would love to put them in them in the warehouse and replace some of the racks with custom more efficient storage solution. 

e.g.

1- Put Refined storage -> Grid in the config file (with the id of course)
2- Setup item solution 
3- Place Grid inside warehouse
4- Profit!

-----------------------

Another addition to the solution solution could be for the main block on the warehouse, to not have an inventory of it's own, but scan all the inventory container blocks, in the area of the warehouse, and present that to the delivery guy... which I think is something he kind of does right now, so we limit this interaction to the warehouse area.

**Comment by marchermans** [comment]
Sadly not that simple. *Most* Mods use a Standard Interface, those would work, but things like RS are never going to happen. The trick here is that to make this work the BUILDER has to place said block as the colony has to become aware of the change. We can rewrite so that he checks for something other then a Chest or a Rack, but that feature is currently low on the priority list. It will be implemented eventually, maybe even with a black and white list. But we have discussed this internally and for now this is going to stay as it is.

Sorry.

Greets,

Orion

**Comment by winsrp** [comment]
hmm... I was thinking, there is another mod that is called... Architect... that what it has is an item provider item that you place on top of a chest, or other block that has items in it, and this way the auto builder of the mod knows where to get items from, maybe it could be something similar, an item that sits on top of a chest or something and the delivery guy knows he can take items from there... or automatically provide them to the builders hut. This Architect mod has a video that you can check to see what I'm talking about, it might spawn a new train of thought and give you a new light. =D

**Comment by Asherslab** [comment]
that thing would also require blocks to use the standard interface, our mod uses the standard interface. basically that wouldn't add any more functionality than what we already have

**Comment by Raycoms** [comment]
The thing is that if we support all those kinds of storage our deliver
system would have to search them slot by slot which is amazingly
inefficient, our racks have an efficient storage which requires way less
calls and won't lag the server

On Oct 27, 2017 09:11, "Asherslab" <notifications@github.com> wrote:

that thing would also require blocks to use the standard interface, our mod
uses the standard interface. basically that wouldn't add any more
functionality than what we already have

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/1554#issuecomment-339942752>,
or mute the thread

**Comment by winsrp** [comment]
I see, Thanks for the info.
