### ISSUE TITLE
[question] is there a way to make autominers work in the colony area?

### ISSUE THREAD

**Issue by winsrp** [ldtteam/minecolonies#1571]
So I'm using RFtool and actually additions, and they have machines to mine but when I put them near the area of the colony none of them seem to work, is there like a special setting, permission, fake user I can add somewhere to make them work?

**Comment by Raycoms** [comment]
Hi, we had a lot of discussions about that one already.
The main problems is that those mods don't implement fake players correctly and our colony protection blocks them.

If you're on single player just turn on the anti-griefing system in the config and things should work fine.

If you're on a server you'll have to tell RFtool to give the machine the players UUID as own UUID.
Because that's how forge intended it. (That's what Lex told us)

**Comment by winsrp** [comment]
thanks for the info, I'll tell McJty about it. thanks.
