### ISSUE TITLE
Enchantments bug.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1579]
### Expected behavior

- give colonist enchanted weapon they cant use and they dont use it.

### Actual behaviour

- uses weapon they cant use.

### Steps to reproduce the problem

1. Heavily enchant weapon 1 and give to colonist. They still complain they need a weapon.
2. Give colonist an unenchanted version of same weapon but leave enchanted one in inventory to the LEFT of the unenchanted one.
3. Colonist uses the enchanted weapon.
4. Profit

My guard was asking for a diamond sword. Gave him one with every enchant on it and he still asked for a diamond sword. Gave him a plain diamond sword and he ran off setting everything he attacked on fire and the enchanted sword took durability loss.

Same thing happened with a ranger. Wanted a bow with max enchant level 3. Same result as previous example.

**Comment by MineShadow7** [comment]
Same thing with every tool. Knights can even use axes if it's in first slot and the sword in the next slot.

**Comment by marchermans** [comment]
What level are your Buildings?

**Comment by Moobien** [comment]
Ranger was in a lvl 5 guard tower, knight was based in a lvl 5 barracks/lvl 4 barracks tower.

**Comment by Raycoms** [comment]
They're supposed to use axes though. As they're tools, I will take a look
at that today

On Nov 2, 2017 2:15 PM, "Moobien" <notifications@github.com> wrote:

Ranger was in a lvl 5 guard tower, knight was based in a lvl 5 barracks/lvl
4 barracks tower.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/1579#issuecomment-341474731>,
or mute the thread

**Comment by Moobien** [comment]
Have found a few other bugs but will make a dedicated thread for them in the morning (aussie time). Gotta collate my screenshots etc.
