### ISSUE TITLE
Observations and Suggestions Part 2

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1585]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.4442

Ok as promised here are some observations and bugs I have found. https://imgur.com/a/h50WV

1) Funky pathfinding.  In the image where I have drawn pretty lined on, Builder at A is building builders hut at B. the purple lines are fencing I have put up to keep colonists on the paths, the red line is the path the builder actually took to build the building.

2) Racks/Warehouse Storage - The Dmen are just dumping stuff into any rack and not sorting it anymore.

3) Mesa warehouse incomplete - as you can see in the screenshot there is no flooring in a section of the warehouse.

4) UI issue - As you can see on the screenshot the issue I am having with the build queue display.

5) Getting about 10 barbarians spawning EVERY night. I looked at the config and changed it to 14 days average between attacks and still get them nightly. (Thank god for Open Modular Turrets)

6) Farmers- Farmers seem to just stop and stand in place when  on the job, when I approach them their speech bubble says "just let me sleep"

7) Suggestion Racks - perhaps have them so they display what is in them on the shelves.

**Comment by Raycoms** [comment]
To 1) the builder builds a few blocks outside of the building so that might
actually be on that hill

To 2) they never sorted it, they just put similar items in the same chest

**Comment by Moobien** [comment]
I mean they arent putting like items with like anymore.

**Comment by Moobien** [comment]
Oh and 1 other minor bug, oak wood stairs dont have waypoints in them anymore.

Another suggestion is shorter versions of the pathing (have scanned in short versions for my own use)

**Comment by Raycoms** [comment]
To 3 and 4 Please open an issue for each.
To 5, are you using the newest alpha?
To 6, farmers only do one run per day each field (one of each task)
To 7 that's planned but is difficult to accomplish

On Nov 3, 2017 22:30, "Moobien" <notifications@github.com> wrote:

Minecolonies version

minecolonies-universal-1.11.2-0.8.4442

Ok as promised here are some observations and bugs I have found.
https://imgur.com/a/h50WV

   1.

   Funky pathfinding. In the image where I have drawn pretty lined on,
   Builder at A is building builders hut at B. the purple lines are fencing I
   have put up to keep colonists on the paths, the red line is the path the
   builder actually took to build the building.
   2.

   Racks/Warehouse Storage - The Dmen are just dumping stuff into any rack
   and not sorting it anymore.
   3.

   Mesa warehouse incomplete - as you can see in the screenshot there is no
   flooring in a section of the warehouse.
   4.

   UI issue - As you can see on the screenshot the issue I am having with
   the build queue display.
   5.

   Getting about 10 barbarians spawning EVERY night. I looked at the config
   and changed it to 14 days average between attacks and still get them
   nightly. (Thank god for Open Modular Turrets)
   6.

   Farmers- Farmers seem to just stop and stand in place when on the job,
   when I approach them their speech bubble says "just let me sleep"
   7.

   Suggestion Racks - perhaps have them so they display what is in them on
   the shelves.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/1585>, or mute the
thread

**Comment by Raycoms** [comment]
Which oak wood stairs?

**Comment by Moobien** [comment]
One other suggestion. Make the block directly beneath the worker/hut block to be untouchable by builders. Reason for this is so you can pipe things in and out of them. Prime example mekanism logistics sorter to pipe ores etc out the miner's block.

**Comment by Moobien** [comment]
One other suggestion. Make the block directly beneath the worker/hut block to be untouchable by builders. Reason for this is so you can pipe things in and out of them. Prime example mekanism logistics sorter to pipe ores etc out the miner's block.

**Comment by Moobien** [comment]
Sorry for double posting.

**Comment by Asherslab** [comment]
for issue 5. what minecolonies version are you using?

**Comment by Moobien** [comment]
Its at the top of the post.

**Comment by Asherslab** [comment]
Version 4482 has the Barbarian fixes in it 😄 
https://minecraft.curseforge.com/projects/minecolonies/files/2495543

BTW there are quite a few new versions since your current, with quite a few bug fixes

**Comment by Moobien** [comment]
Yeah noticed that this morning before I went to work. Had to rehire ALL my rangers and knights in my barracks though after updating.

**Comment by Raycoms** [comment]
Closed in favor of the new issues.
