### ISSUE TITLE
worker during rain

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1598]
minecolonies-universal-1.12.2-0.8.4596.jar

Default is for working to not work during rain.  Good option,  but it appears that means they just stand out in the rain until dark.

Are they suppose to just stand around in the rain?

![2017-11-05_13 22 09](https://user-images.githubusercontent.com/30982580/32418275-5fb609fe-c22c-11e7-9205-9882182fcdf4.png)

**Comment by bob0bob** [comment]
That is my miner.  All the citizen are just standing out in the rain.

**Comment by Wissi** [comment]
All the info is in the WIKI.
 Rainy weather will make your citizens stop working!!!
http://wiki.minecolonies.com/wiki/2/workers-info

**Comment by conqp** [comment]
> All the info is in the WIKI. Rainy weather will make your citizens stop working!!! http://wiki.minecolonies.com/wiki/2/workers-info

That link is dead. Where can I get the up-to-date info?

**Comment by MotionlessTrain** [comment]
I think [this](https://wiki.minecolonies.ldtteam.com/source/systems/worker) wiki page would match that old wiki page.

By the way, this github issue is more than 4 years old. For support, instead of commenting on outdated github issues, I would like to ask you to join our [discord](https://discord.gg/zjA75K8) instead

**Comment by Auhrii** [comment]
Requiring players join a Discord server to request basic information is less than ideal - GitHub is at least archivable and searchable.
