### ISSUE TITLE
Quick query

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1705]
Hey guys, currently using version 1.12.2-0.8.5203, latest alpha on curse is 1.12.2-0.8.5066.  is this a direct upgrade and safe to update to?

**Comment by bob0bob** [comment]
I've asked that also.  To an outsider, it make no sense that beta and release code version is higher then alpha code.  I can understand the release from yesterday being a hotshot release having an odd version but it doesn't make sense that alpha version is older then beta/release version.  But they said version is not a real version number,  it is just the number time the code has been compiled.  

So it can appear to be like this, but yeah.  I guess everyone has their method.  If they label the build number in their version control software, they can get back there.

**Comment by marchermans** [comment]
Since i am our build engineer. I am probably the most qualified to answer this. 

The version numbers are build up as follows.:
Mcversion - major.minor.buildId (- type)
In most cases a normal player, like yourself you will never get a version with a type appendix, these are only for developerversions. So let me explain the other elements.

Major and minor are values defined by us. As of writing i think they are either 0.8 or 0.9 depending on the release type (Alpha / Beta / Release). The buildId is an entirely different story however. It is defined by the buildsystem and allows us to track which build corresponds to which .jar-file. It is not related to any release type or version. It just increments everytime a build is made.

Now on to your question. If the person who authorized a release did it right, you can always update from a lower version alpha to a higher version beta. And from a lower version beta to a higher version release and from a lower version release to a higher version alpha.

This however went wrong the last times. The alpha build was created before the beta build causing their numbers to get switched. Which caused for a lot of confusion. I am currently looking into automating this process. But I am a really busy bee so it is a bit lower on the priority list.

Last but not least, alpha and beta builds are for testing only. We do not guarantee full functionality between version nor do we guarantee that a version regardless of release type will be bug free or compatible with the previous version. We do our best to keep them compatible since we have our patreonservers to run, but as stated we are humans and we make mistakes.

I sincerely apologize for the mixup and I will keep an eye on it for the next release cycle.

Greets,

Orion

**Comment by bob0bob** [comment]
Thanks for the explanation.   I know I'm playing with alpha and there might be bug and even huge bugs.   I have no problems with that.
