### ISSUE TITLE
[1.12.2] Can't open chests.

### ISSUE THREAD

**Issue by None1911** [ldtteam/minecolonies#1916]
### Minecolonies version

0.8.6291 (1.12.2)

### Expected behavior

- My hand will open the chest and the inventory of the chest will show i think?

### Actual behaviour

- Right click, hand moves, doesn't open the chest. not inventory interface showing, nothing.

### Steps to reproduce the problem

1. place supply camp chest
2. go to camp
3. try open a chest.
4. replace the chests to see if that fixes it
5. try open a chest. Again.
6. profit

### Debug crash log

pastebin link, mods installed are showed in the log.
https://pastebin.com/aHcLd1Fr

### Permissions

papasito89 (me) = owner

**Comment by None1911** [comment]
edited

**Comment by None1911** [comment]
updated to the new one released (0.8.6341 1.12.2), same problem.

**Comment by Raycoms** [comment]
Are you inside someone elses colony?

2017-12-28 20:37 GMT+00:00 None1911 <notifications@github.com>:

**Comment by None1911** [comment]
Nope, i'm playing singleplayer, it's my own colony.

**Comment by Imrielle** [comment]
Unsure if they fixed it on their end or not, but the issue isn't Minecolonies. Here is the relevant line:

"**Forge 14.23.1.2582 Optifine OptiFine_1.12.2_HD_U_C7**" - the issue is Forge and Optifine.

Update your Optifine to the preview version, **OptiFine 1.12.2 HD U C8 pre**, and the issue will be fixed.

**Comment by None1911** [comment]
It was a Forge problem, switched to .2555 and problem was fixed.
