### ISSUE TITLE
Babysitting the Builder

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#2086]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7133

### Expected behavior

- Builder checks chest and finds items for build

### Actual behaviour

- Have to pull from chest and give it to him directly

### Steps to reproduce the problem

1. Recalled him
2. exited and restarted world
3. picked up items and put them back, didn't take them and came back, only filling request works.
4. Profit

**Comment by Lordbaane** [comment]
Also, he seems to have a problem with level 2 barracks. He just sits there.

**Comment by Lordbaane** [comment]
I did a reset you recommended from another thread. It looks like it might have worked.

**Comment by Lordbaane** [comment]
It worked for a while, now I'm back to babysitting.

**Comment by copperwarrior** [comment]
Orion, this seems like the same issue I had while testing, with the builder ignoring his chest.

**Comment by Imrielle** [comment]
Yep, same issue I mentioned in Discord, I'm digging a pit for lava to roast the builder in now >.>

**Comment by marchermans** [comment]
Hmm.
I tested that twice.
Broken again blah.

**Comment by marchermans** [comment]
@Imrielle @copperwarrior @Lordbaane I have been debugging this this morning, turns out this is because of an item duplication bug. 
Let me explain: 
Right now a player or a building can overrule a request with an matching itemstack regardless of size. (This is so that you can get the Builder going with only a partial result, say 32 Items when he requests 64). However when this is a crafting request. This breaks in either on of two ways. If he can craft -> he will craft as many as he requested, regardless of the amount that is there. Aka: Put one 1 Log in, get 64 Planks. However if you have a request that needs more then one stack (say torches), this breaks and the craft fails, causing him to get stuck.

There is sadly only one direct solution that I see right now: Overruling can only be done with a complete stack!. Meaning that you at least need to give him what he wants! So if he needs 16 Logs. YOU need to give him 16 or more.

I am discussing with @Raycoms what this has for concequences.

**Comment by Lordbaane** [comment]
Does that resetting thing help at all then? Or is there another command that will work to start him up?

**Comment by Raycoms** [comment]
We are currently working on a solution.

2018-01-25 14:22 GMT+00:00 Lordbaane <notifications@github.com>:

**Comment by marchermans** [comment]
So I fixed this

**Comment by marchermans** [comment]
Build is on the way to the testers
