### ISSUE TITLE
Deliveryman

### ISSUE THREAD

**Issue by Vealikaso** [ldtteam/minecolonies#2100]
### 0.8.7210 Minecraft 1.12.2
![2018-01-28_00 48 27](https://user-images.githubusercontent.com/35880693/35477525-194d1978-03c5-11e8-8575-11750aa46891.png)
![2018-01-28_00 48 53](https://user-images.githubusercontent.com/35880693/35477526-1d49a56e-03c5-11e8-8112-c060fceb3e63.png)

version 0.8.7210

### Expected behavior

- Deliveryman brings slabs to Miner

### Actual behaviour

- Deliveryman only Gathers and dumps items

### Steps to reproduce the problem

1. Build Warehouse
2. Build Miner
3. Build Deliveryman Hut
4. Wait untill Miner wants something

**Comment by marchermans** [comment]
This is a known bug. The DMan is not actually ordered to perform the delivery.
As stated in your other Issue the RS takes a random Resolver right now, which means that it just happened to assign it directly to you. If it would assign it to the DMan it would show you a delivery right there.

This issue was extremely hard to track down due to the random nature of it (even though for some of us it seems to happen relatively often, it has only happened to me once). Which is the reason why testing this new build is taking a bit longer then ussual i had to take 4 cracks at this until i solved it.

Sorry for the delay.
