### ISSUE TITLE
[Discord Suggestion] Townhall Allies GUI Fix/Enhancement

### ISSUE THREAD

**Issue by Imrielle** [ldtteam/minecolonies#2126]
Suggestion: On the TH allies page, if the TH is too low a level to enable the teleport button, render a disabled button with the text "TH too low" or something similar

It explains why the buttons are missing for people who are expecting them, and tells people who don't know about the feature that it exists

From: Zyx#6333

**Comment by Raycoms** [comment]
Done already

On Jan 31, 2018 04:09, "Imrielle" <notifications@github.com> wrote:

Suggestion: On the TH allies page, if the TH is too low a level to enable
the teleport button, render a disabled button with the text "TH too low" or
something similar

It explains why the buttons are missing for people who are expecting them,
and tells people who don't know about the feature that it exists

From: Zyx#6333

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/2126>, or mute the
thread

**Comment by gaoruisi** [comment]
Umm, small problem with this one. It doesn't tell me what feature exists, nor does it tell me what "TH too low" even means, or how I might correct that. A google search for the alert brings up only this page, which is also unhelpful

**Comment by Raycoms** [comment]
yeah we'll add more docu on these things soon.
@lunadragnstar could we add this to the wiki?

**Comment by lunadragnstar** [comment]
Adding info to the wiki
