### ISSUE TITLE
[Suggestion] Translatable NPC Sound Files

### ISSUE THREAD

**Issue by Eufranio** [ldtteam/minecolonies#2176]
Right now, quotes are english only. It'd be nice if we could add translatable quotes to the mod, that would be played depening of the player's language. Those custom quotes would be provided by an separated sound tracks file or something, not required by the main mod and downloaded separately.

**Comment by Justen-N** [comment]
That would massively increase  mod size, as the only way to change
languages would be to record every line in that language and use that
instead of the default English.

**Comment by Eufranio** [comment]
Edited the ticket.

**Comment by mkienenb** [comment]
This would be done as some kind of resource pack, not part of the Minecolonies main jar.

**Comment by mkienenb** [comment]
Turns out to be trivial.

To start from scratch, follow the directions in
https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack

To see an example which will make builders quack like geese instead of talk, look here.
https://github.com/mkienenb/minecolonies-sound-resource-pack

To "install" any resource pack, copy or check out the files inside of a new folder (you can pick the name of the folder) which is located inside of the "resourcepacks" directory of your minecraft client (same level as your saves/world directory).  Note that the minecraft client itself will open up the "resourcespack" folder for you to do this if you go to "Options -> Resource Packs" -> "Open Resource Packs Folder" in the client [1.12 used as a reference].

The only non-obvious part is knowing the names of the sound files and the locations in the assets folder  But that's easy to look up in the official minecolonies jar, or you can ask for help.

I recommend that we close this issue and start a new project.   It could be under the minecolonies github or you could start it somewhere else.  It could be one language or many or even nonsense sounds as I demonstrated above.

**Comment by marchermans** [comment]
We should provide a github repo with resource packs. That way we can vet them and distribute them properly.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
