### ISSUE TITLE
Medieval Dark Oak Barracks places 2nd tower in a strange place

### ISSUE THREAD

**Issue by Bihlbo** [ldtteam/minecolonies#2205]
### Minecolonies version

version 4.19

### Expected behavior

- The level 2 Medieval Dark Oak Barracks places stairs on the opposite corner of the plot from the first tower, which also had stairs pre-built for it. I expected the barracks to place the second tower where these stairs would allow access.

### Actual behaviour

- The level 2 Medieval Dark Oak Barracks places the second tower on a different corner. This corner has what looks like a stable built by the design of the level 2 barracks, so in order to build the tower in this location the builder destroys part of the stable, leaving the part not occupied by the tower alone. The end result not only looks very strange, but leaves the pre-built stairs alone and useless.

### Steps to reproduce the problem

1. Build a Medieval Dark Oak Barracks to level 2.
See this image: https://imgur.com/a/pNG5E

**Comment by carlansor** [comment]
I can confirm this issue persist on latest alpha, also happening with medieval oak

**Comment by Nightenom** [comment]
@carlansor any progress?, though I think you solved this already

**Comment by carlansor** [comment]
@Nightenom i havent. To fix this i have to redesign the entire barracks of all styles. Its possible to return to the way that barracks guardtowers were placed before? Otherwise ill have to wait for the placement rework.

**Comment by Nightenom** [comment]
I'm not so long here to know what before means there, but if you mean tower-placeholders - I think I can get them working (if they aren't)

**Comment by carlansor** [comment]
having a way to place the tower placeholders instead of having to guess where the barracks is going to place it would be awesome. That way i just can place the tower placeholders in the order i want between the barracks levels and the problem will be solved without require me to redesign the schem.
The problem right now is that when i designed the barracas the placement order was this:

1_________2
_____B
3_________4

B=Barracks block
1,2,3,4=Guardtower blocks placed in numerical order as lvl increases.

Then, it changed to this order:

1_________3
_____B
2_________4

Thats why in the issue @Bihlbo says that in 2nd second lvl the builder destroys a stable, wich in first order just ocupies the place where a tower will be at later lvls.

**Comment by marchermans** [comment]
@Nightenom I would be amazing to add extension functionality to your idea of the download.
We will be storing additional information for the schematic anyway. Howabout also storing position were extensions need to be? Or even making it possible to split schematics into several pieces?

**Comment by Raycoms** [comment]
We thought about making the extensions work by a modifiable placeholder
block with a GUI which lets you define which block you want it to be.
That's easier for the creator of the schematic because then he doesn't have
to calculate the relative position.

Splitting schematics might be interesting, but that would probably be more
for 2.0 =D

Am Sa., 15. Sep. 2018 um 11:09 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by marchermans** [comment]
Well if we start to rewrite such core features, he should keep that in mind, and maybe have some extension points in his design for the jsons so we can hook that in real easy. Is just a note to keep something like that in mind.

**Comment by Raycoms** [comment]
Yes

Am Sa., 15. Sep. 2018 um 11:31 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by carlansor** [comment]
if anything of this becomes true, count on me to build some creative stuff :)
