### ISSUE TITLE
Dedicated Server crash on bootup when having both ProjectRed and Minecolonies

### ISSUE THREAD

**Issue by r3volut1on** [ldtteam/minecolonies#2294]
### Minecolonies version

version 0.9.6974

### Expected behavior

- Integration with Project Red without issue

### Actual behaviour

- Sometimes when booting up world, dedicated server crashes with following [crash](https://dpaste.de/posC)

### Steps to reproduce the problem

1. Have both ProjectRed and Minecolonies 
2. Load up the world on dedicated server and sometimes you will get this crash when booting the server (has not happened yet while server is already up)
3. Already contacted ProjectRed and they said [Minecolonies should catch the exception](https://github.com/MrTJP/ProjectRed/issues/1250)

**Comment by Raycoms** [comment]
Can you please report this to the project red page as well?
This happens because projectRed has an invalid implementation of the
blockStates. A bunch of other mods fixed that already.
We store and retrieve default blockStates the minecraft way here.

2018-03-07 21:52 GMT+00:00 Matthew Kinzler <notifications@github.com>:

**Comment by r3volut1on** [comment]
I reported this issue to them, and they said it will be fixed in 1.12 but not ported back to 1.10.2 unfortunately.  You can see their response in the step 3 link above.

**Comment by Raycoms** [comment]
What a bummer, yeah we also at the moment don't have time to port more changes to 1.10.
