### ISSUE TITLE
[mod compatiblity] When Dynamic trees is present, lumberjack fails

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#2316]
### Minecolonies version

1.12.2-0.8.7719

### Expected behavior

- expect lumberjack to collect wood from dynamic tree

### Actual behaviour

- lumberjack never collects the wood

### Steps to reproduce the problem

1. install dynamic tree mod
2. make a new world
3. make a saw mill
4. watch the lumberjack struggle to make wood because the tree grows against him
5. Profit

### Suggestion
Lumber jack needs detect the tree type and if it is a dynamic tree, switch to chopping the bottom log block, at which point the dynamic tree completely falls apart and the wood can be collected.

**Comment by SulpherStaer** [comment]
This issue made me start over in a world without dynamic trees. Guards also don't quite know how to path over these trees. As guards enjoy walking in trees.

**Comment by kreezxil** [comment]
Just learned that Dynamic Trees provides a conversion recipe utilizing a bucket of dirt as a catalyst to convert the seed drops to sapling drops. Provided you don't have replace minecraft saplings with dynamee tree saplings turned on, it is then the viable workaround to this problem and therefore this suggest can feasibly be back burnered. But it would still be nice to not have to manually plant a forest for the lumberjack/sawmill.

**Comment by SulpherStaer** [comment]
The lumberjack does recognise that the dynamic tree is a tree, but because they start harvesting at the top, and don't break block, but replace with air, dynamic trees get confused. Dynamic trees should be harvested from the bottom, and with break block event.

The breakblock event of a bottom log causes dynamic trees to drop the wood, and some sticks as items.
There should be a test for the lumberjack to see if the log is 'thick/mature enough' to harvest the tree, otherwise it'll only get sticks.

The tool still receives the correct damage, and the whole tree is felled. Harvest time does increase for bigger trees, but I'm not sure if the lumberjack gets its harvest time from the break block time and tool calculation.

The mod saplings however are not recognised, and the default which can be replaced by the dynamic trees mod, are not replaced, because it's a set block event, and not the same type of event if a player plants a sapling.

**Comment by SCAgamer** [comment]
When first hired, the LJ went to a close young sapling that would have maybe dropped a stick if it was cut from the bottom and cut it from the top down. The LJ has been picking up saplings ever since completely ignoring the mature trees right in front of him. You could probably easily work around this by making it a block break event and having a config option to chop either from the top down or bottom up.

**Comment by kreezxil** [comment]
I just occurred to me, have LJ check for a full block while it is chopping
a tree. If it is not a full block it doesn't chop that block. This will
make tree harvesting in general faster because it won't be wasting time on
leaves. Seriously what lumber jack actually chops leaves while they are on
the tree anyways?

So let's say it is chopping down from the top. The LJ should scan that
layer and check for non-leaf blocks, of those it should check to see if it
is a wood block (log). If it is not then it's a dynamic tree and it should
switch to the bottom layer and perform the same scan. In which it will find
the log block, chop it and the entire tree will come down. pick up the logs
and move to the next tree.
