### ISSUE TITLE
Sawmill freezes game upon opening GUI

### ISSUE THREAD

**Issue by UkeArie** [ldtteam/minecolonies#2353]
### Minecolonies version

version 1.12.2-0.8.7949
### Expected behavior

- Access Sawmill GUI

### Actual behaviour

- Long delay, game freezes, eventually opens GUI after several minutes. Opening Inventory causes the same thing to happen again.

### Steps to reproduce the problem

1. Open Sawmill GUI
2. That's it.

**Comment by Nezraddin** [comment]
Have the same problem.
I'm wondering if it is the amount of extra trees that causes this problem. Have a few mods installed that adds alot of trees (like forestry, rustic)

**Comment by marchermans** [comment]
Yes a lot of trees will cause this issue. We are already caching a lot. But the trees will still need to be analyse for gui purposes.

**Comment by Nezraddin** [comment]
As a little suggestion:
Maybe instead of the current system where the lumberjack reads every installed tree, something similar to the farm (where you add the seed of what the farmer should grow) could be added:
A window with some sort of special inventory in which you put the saplings of the trees which are to be recognized for cutting down.

Now sure how this is possible coding-wise, but this way the freeze might be avoidable since the lumberjack pretty much starts with an empty list.

**Comment by Raycoms** [comment]
Yeah we're currently reworking our GUI framework for that

2018-04-03 13:48 GMT+01:00 Nezraddin <notifications@github.com>:

**Comment by Heregerifa** [comment]
Have the same problem but the sawmill is only the start - delays begin with other minecolonies inventories (though not so severe) and then spread to others including vanilla chests and crafting benches.  (Cith Life modpack)

**Comment by marchermans** [comment]
@Heregerifa then it is not us. We use a custom gui Framework which does nothing with other guis.
