### ISSUE TITLE
Crash caused by ores... maybe...

### ISSUE THREAD

**Issue by DcNdrew** [ldtteam/minecolonies#2469]
### Minecolonies version

version 1.12.2-0.8.8242

### Expected behavior

- No crash.

### Actual behaviour

- Crash. :D

### Steps to reproduce the problem

1. Install Project Red everything
2. Install Minecolonies
3. ??? Pass. It worked for hours, but later I started to play, and crash.
4. Profit

Without Minecolonies there is no crash.

https://paste.ee/p/OoU2c

**Comment by marchermans** [comment]
This is a common issue with mods that have broken blockstates.
@Raycoms, as far as i could remember this was not an issue at minecolonieses side, correct?

**Comment by Raycoms** [comment]
This happens due to the mod which adds this mod here: They do set up their
blockStates wrong, please report it to them. Their mod triggers the issue
with minecolonies.

java.lang.IllegalArgumentException: Cannot set property
PropertyString{name=type, clazz=class java.lang.String,
values=[sapphire_ore, copper_ore, ruby_ore, electrotine_ore, peridot_ore,
tin_ore, silver_ore]} to sapphire_ore on block projectred-exploration:ore,
it is not an allowed value


2018-05-22 20:28 GMT+01:00 DcNdrew <notifications@github.com>:

**Comment by DcNdrew** [comment]
Wow, that was quick. :D

**Comment by marchermans** [comment]
:D
