### ISSUE TITLE
Player built a hut then their game crashed

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#2480]
pastebin: https://pastebin.com/wTaNTNE8

### Minecolonies version

build 1.12.2-0.8.8242

### Expected behavior

- not crash

### Actual behaviour

- crashed

### Steps to reproduce the problem

1. they said they finished building a hut

**Comment by Raycoms** [comment]
There must be some kind of mod which handles their ore blockStates wrong.

2018-05-25 14:08 GMT+01:00 kreezxil <notifications@github.com>:

**Comment by Vilkath** [comment]
Hey guys, I'm the user who had the crash. I have a couple of screen shots of the effects and was recording a video for a lets play series. I'm still uploading it now but I can post a link to the time code of where the crash happened if you guys want.

Basically though I had just completed my first building, the builders hut and it crashed. When I got back the Town hall and every clickable object of my colony was gone. Several blocks in the world were corrupted and replaced. Sadly I was playing Single player without a back up save so it's pretty much gone.

![2018-05-24_20 16 48](https://user-images.githubusercontent.com/39627661/40551650-6d58cd76-5ff2-11e8-97d8-9b88c43457a1.png)
![2018-05-24_20 22 27](https://user-images.githubusercontent.com/39627661/40551658-768df146-5ff2-11e8-9b39-4d11a885d65d.png)
![2018-05-24_20 18 10](https://user-images.githubusercontent.com/39627661/40551667-7af53fdc-5ff2-11e8-9357-0bee578c37ee.png)

**Comment by Nightenom** [comment]
Remember (@kreezxil) that using alpha builds in a modpack (as it looks like) may cause random bugs and a mod contain world destructive behaviour, so you should not update the mod. Even though Raycoms wrote it's more likely not a bug in this mod and alpha builds of this mod are more likely stable.
_If it's not from a modpack, then consider this comment to be irrelevant._

**Comment by Raycoms** [comment]
This bug is really strange, we never had something like that. This is also
not related to it being an alpha build. We're just behind in pushing to
beta and release.

This is really weird. It looks like there is a block which triggers
minecolonies. Although minecolonies for sure isn't causing the world
destruction.

Can this be reproduced?

2018-05-25 17:23 GMT+01:00 Nightenom <notifications@github.com>:

**Comment by Nightenom** [comment]
@Raycoms 
> I have a couple of screen shots of the effects and was recording a video for a lets play series. I'm still uploading it now but I can post a link to the time code of where the crash happened if you guys want

**Comment by Vilkath** [comment]
Sorry it took so long to reply guys, I just got off work. Her's the time code just before the game crashed. Not sure how far back you want to see what I did.

https://youtu.be/KEUlncYbpZs?list=PLVxfL3CNjiFv17N_SqoM3pRmbqCIVKy2-&t=2283

I'll see if I can reproduce this later. One thought I had that might of caused the problem is I put my Supply camp down near my base. But then I found out about the 2000 block limit for being to near spawn. So I had to put my town hall way far off from where the camp was set. Would this impact the mod at all?

**Comment by Raycoms** [comment]
shouldn't make any difference

2018-05-26 3:29 GMT+01:00 Vilkath <notifications@github.com>:

**Comment by kreezxil** [comment]
hopefully you haven't deleted your logs folder. if not, you should zip it
up and attach to this too.

**Comment by Vilkath** [comment]
No I haven't deleted anything yet, here is the logs.

[logs.zip](https://github.com/Minecolonies/minecolonies/files/2041653/logs.zip)
