### ISSUE TITLE
Farmer create an extra farmland tile

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2533]
MC 1.12.2
Forge 14.23.4.2707
Minecolonies 0.8.8618

Farm level 1, Medieval Oak

https://imgur.com/a/BPJ9EUT

**Comment by Nightenom** [comment]
Look [here](https://wiki.minecolonies.com/index.php?title=Farmer), it's not an issue then, btw we have a planned feature for resizeable fields (is waiting for another update, so give it something like 2-4 months)

**Comment by Raycoms** [comment]
This must be by another mod since he doesn't create anything himself, he uses the default minecraft classes for frming.

**Comment by MokahTGS** [comment]
Not really sure you can blame another mod for why the AI of minecolonies is making extra farm tiles outside of a 9x9.  Here's what's happening at my farm: https://www.dropbox.com/s/95av8bm6fm0v8ij/2018-09-22_11.04.34.png?dl=0

**Comment by Raycoms** [comment]
I don't get what the issue is

Am Sa., 22. Sep. 2018 um 13:12 Uhr schrieb MokahTGS <
notifications@github.com>:

**Comment by MokahTGS** [comment]
The issue is that the farmer is creating 10x10 farmland that cannot be watered on the outside ring.  So the farmland reverts back to dirt and the farmer re-hoes the ground, which then turns back into dirt, which he then re-hoes, dirt, hoe, dirt, hoe, for eternity...

I've so far had to supply the farmer with 10 hoes.  He's not planting wheat because he's spending all his time hoeing the ground.

**Comment by Raycoms** [comment]
yeah, this means that the water placement is wrong and you need to add a
bit more water. In the future you can configure the size of the field, but
for now the size is automatic this, you can add a cobbleborder around it,
this he won't try to hoe.

Am Sa., 22. Sep. 2018 um 17:37 Uhr schrieb MokahTGS <
notifications@github.com>:
