### ISSUE TITLE
Citizens disappearing, not being able to kill or recall.

### ISSUE THREAD

**Issue by stefan7080** [ldtteam/minecolonies#2580]
### Minecolonies version

version minecolonies-1.12.2-0.8.9646 or curse 14.23.4.2725

### Expected behavior

- Citizens wondering around, and being able to recall them to either their workplace or the Town Hall.

### Actual behaviour

- Citizens disappeared, no way of re-calling them, could not kill them using /cm colony kill. Refreshing didn't work either.

### Steps to reproduce the problem

1. Literally no clue.

Server log:
https://pastebin.com/K9vzdsF7
Client log:
https://pastebin.com/WGpzXmzB

EDIT:
Colony file: https://www.dropbox.com/s/cippu0qr8s0prd1/colonies-2018-07-01_22.33.07.zip?dl=0

**Comment by Nightenom** [comment]
If the problem still persists can you try updating to the latest version? Otherwise please close this issue

**Comment by Raycoms** [comment]
newest builds should solve this

**Comment by zekeflynn** [comment]
They don't. Still got vanishing citizens. Latest build as of Nov. 21.

**Comment by Raycoms** [comment]
You should be able to recall them at the townhall though. The disappearing
thing is part of minecraft that's not our fault. Unfortunately,
minecrafts entity management is terrible.

Am Mi., 21. Nov. 2018 um 05:17 Uhr schrieb cellopietro <
notifications@github.com>:

**Comment by DeanBeanBEER-WARE** [comment]
so im stuck now with 4 citizens, all of them vanished, reloading the game won't bring them back, and since i didn't even got to build the builders hut yet i can't use the townhall to tp them ? Are you guys kidding me ? I don't care "if it's not your fault", either fix it or take your mod off the curseforge modloader, insane, this issue first came up in 2018, and now 7 years later it still persists.
