### ISSUE TITLE
Builder not always taking items from container

### ISSUE THREAD

**Issue by stefan7080** [ldtteam/minecolonies#2585]
### Minecolonies version

version 1.12.2-0.8.9646 or curse 14.23.4.2712

### Expected behavior

- Builder grabs the items from the container.

### Actual behaviour

- Builder spams chat with requests while the requested items are in the container.

### Steps to reproduce the problem

1. Request build
2. Supply items
3. Watch Bob take an indefinite coffee break
4. Profit

A couple screenshots:
http://prntscr.com/k1zbc5
http://prntscr.com/k1zbje
http://prntscr.com/k1zbr5
http://prntscr.com/k1zbyu

**Comment by bob0bob** [comment]
I'm seeing it also on version 1.12.2-0.8.7582.

The builder will have an item in the huts chest or their inventory and the request still appears.

Also,  the request appears to be somewhat completed (guessing here), because when they are stuck like this the clipboard doesn't show they have an active request.

If I click on "Cancel" for the request on the citizen gui, it restarts and then the builder sees they have the item and starts building.

**Comment by Nightenom** [comment]
Yeah, therefore is the Cancel button used, we simply can't check inventory each tick

**Comment by marchermans** [comment]
Yep out of performance reasons we do not check inventories every tick. Especially the additioal chests in higher level buildings. Give it to him directly.

Inteded behaviour for performance reasons. Doublechecked that this is working twice now. Closing.
