### ISSUE TITLE
[Question] Can settlers be told to ignore modifications or use mod items?

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#2655]
Hi, it's been a while since I played MineColonies and I have a couple of questions. (I did a brief look around and decided it would be easier to ask, and maybe roll it into a request/suggestion.)

1. Is it possible to get the builder to ignore improvements (decorations, lights, mod items, etc.)? Conveyors, power cables, fancy lighting, chiseled variant blocks, etc.

2. Is it possible to swap out blocks with equivalent mod blocks and have them used? e.g., Switch a furnace for a redstone furnace? Or use alternate fuel? (Or the IE external heater?)

**Comment by Raycoms** [comment]
Hey, about 1:
That's unfortunately really difficult because then we would have to maintain a list of items to ignore which is difficult.

2: This is only possible if these mods implement the default vanilla classes.
Following this, you can create your own stylepack including these modblocks and check if the workers use them.
