### ISSUE TITLE
Guards not wearing Mekanism armors anymore

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2670]
forge-1.12.2-14.23.4.2739-universal.jar
minecolonies-1.12.2-0.9.37-ALPHA-universal.jar

This is happening since a few releases ago.

**Comment by marchermans** [comment]
@bob0bob

**Comment by demfels** [comment]
We are on 1.12.2-0.9.50-ALPHA and as far as I can tell guards won't wear ANY armor.  I've tried both knight and ranger with just iron armor.  They will pick it up from their box, but not wear it.  I also noticed their wayla tooltip still says 5 armor.  So it is not increasing.

**Comment by Raycoms** [comment]
@bob0bob can you check on this?

**Comment by bob0bob** [comment]
@Raycoms   Yes.   I'm working on redoing the armor request to match MC style.  It will have a min. and max level based on TYPE so.  Any armor that is registered correctly should work.  I should get this done today, hopefully.

Just when I started it,  I noticed all kinds of issues with guards on startup after a save.   When it loads, they are RUN back to their buildings,  even though they where in follow mode, or a fight.   On start it appears they do not really remember where they left off.  
They request armor all over again and send out a request even on SAVE they where using the armor.  But on load the armor is not remember. 

The state which they where at looks like it is being saved in the NBT but the start always makes them go back to their building and start over.  They really should continue doing what they were doing at the time of save.

So I started to see a bunch of issues that needs work.

**Comment by Raycoms** [comment]
You can store the armor details and the current state in their job.java so they continue where they left of.

**Comment by bob0bob** [comment]
Ok.   I've added a  LEVEL system for the armors.   Now armor are not requested by type.  They have a range instead of an request of an item.   The async request will go out with the range for items.  This should allow any type of armor be able to be used.  Only requirement is that they inherit from ItemArmor at some point.  The code will check to see if that is an instance and then if the material type and equipment type are set using the standard enum values.  MC will be happy using those items.
