### ISSUE TITLE
Oak WareHouse level 5

### ISSUE THREAD

**Issue by quentfr21** [ldtteam/minecolonies#2690]
### Minecolonies version

 minecolonies-1.12.2-0.9.50-ALPHA-universal.jar

hello

after i upgrading it to level 5 and max rack level a delevery man try  to completely empty the warehouse and stay stuck after it's invenstory is full 

does this is normal ?

sorry for my english and thanks for this great mod

**Comment by BonaireDreams** [comment]
Have the same issue in 0.9.7-BETA
LVL5 Taiga D-Man
LVL5 Medival Spruce Warehouse
Dman stands at chest and just randomly takes things out of racks until his inventory is full and then stands there.  He no longer goes to pick things up nor deliver. If I remove items from his inventory her just refills with random items from the racks.

**Comment by Raycoms** [comment]
Does restarting fix this? If not, can you send us your world?

**Comment by BonaireDreams** [comment]
Restarting does not fix it. I have also tried recalling him to his hut and he just goes right back to warehouse and stands there staring at his crate. I have too much in the warehouse to try and empty it to the point where he has room in his inventory to see what happens then.

World
[https://www.dropbox.com/s/bwl4kw896t8i4nt/Bonaire.zip](url)

My base is at -1700, 1400 near the MESA Biome. Colony is Colony: 2

We are running my custom modpack with Minecolonies on top so you will need my Modpack.
[https://minecraft.curseforge.com/projects/bcwolfpack](url)

*EDIT* Added modpack link.

**Comment by Raycoms** [comment]
The dropbox link isn't work for me

**Comment by Raycoms** [comment]
Weird, it's a github bug

**Comment by BonaireDreams** [comment]
Ya that's strange, even if I right click the link and say copy link I get the Github error page link. But i can highlight the entire link and copy/paste it into another browser tab and it takes me to Dropbox.

**Comment by Raycoms** [comment]
Yeah that worked for me as well

2018-07-30 17:01 GMT-03:00 Gerald <notifications@github.com>:

**Comment by Raycoms** [comment]
Okay it's weird, when I load up this world, at least in the dev environment it works perfectly, did you try to restart the server to fix this?

**Comment by BonaireDreams** [comment]
The server shuts down, backs up and restarts every night at 2AM. She's been doing this for 3 days but I have not been watching her closely. So tonight I manually restarted the server, logged right in and went to the warehouse. DMAN was running around the town like a chicken with its head cut off. She's so fast there is no way to keep up with her, easily 3x as fast as any other citizen. I thought, ok maybe its fixed... but after about 5 minutes of running like crazy (stopping at huts and going in and out of the warehouse, she came back to the warehouse and stood by her crate. I was close enough and clicked on her inventory right away, and saw the last row and a half fill up with stuff and now shes just standing there again.

So I fired her, and rehired her. She's been running around at mach 9 for about 5 minutes. she's stopped at the smeltery which doesn't even have a worker so there's nothing there and all this time the farmer has requesting his crate be emptied because he has no room to dump his inventory. She seems to spend far too long at certain crates. Keeps going to the barracks and spends a good 15-20 seconds there, even though there's never anything at the barracks (no guards).

Tried /mc rs reset colony: 2    no change.  Her pathfinding is also so weird, she walks forward then spins a bit. Then walks forward.

So I went the drastic route. I fired her and then she fell on my sword. I don't know how that happened. New citizen spawned, I hired him as DMAN. He walks at normal speed and after visiting a few other huts to pick up things, he went to the farmer and pick everything up there.  So it looks like it was just Madisen who got the crazy and didn't want to work anymore. Elijiah is a much more reliable worker and seems fine.

**Comment by Raycoms** [comment]
Ahh, it might need a few minutes? I will check tomorrow again then. She is
soo fast because they become faster on bricks or gravel and they become
faster during level (they as in dmen) so after a while the pathfinding is
slower than the walking and it bugs a bit (we're on that).


2018-07-31 0:11 GMT-03:00 Gerald <notifications@github.com>:
