### ISSUE TITLE
Fulfillment of Armor - Shouldn't take your armor

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2753]
When a guard request armor and you click on fulfill.  It will fulfill that request with the armor you are wearing.

Armor your wearing shouldn't be possible to fulfill the request for item.

**Comment by Wetz1990** [comment]
Related to this. It seems that the guards will also keep requesting the same piece of armor even if they already have it. 
I have several times checked the inventory of my guards and found that they have several helmets, leggings, chest plates and boots on them at the same time. 
This is not from picking up loot since it also occurs on peaceful mode, and removing all the extra armor from the inventory makes them request more from the warehouse, even if they already have it in their inventory.

**Comment by Raycoms** [comment]
Yah I'm working on that
