### ISSUE TITLE
Lumberjack issues

### ISSUE THREAD

**Issue by ShaneCourtrille** [ldtteam/minecolonies#2885]
Version: 
minecolonies-1.12.2-0.9.127-ALPHA-universal.jar

### Expected behavior
I expect the Lumberjack to cut down trees

### Actual behaviour
I ran into two odd behaviors.. 

1. We had an insanely massive tree growing a good distance away from the lumberjack but he would always walk towards it even though there were trees which were much closer.  Then about half way he would stop and turn around and walk back to the area near his shack before repeating the same back and forth. 

We cut down the tree and that behavior stopped and then he was able to cut down trees for awhile until..

2. He started to walk amongst the trees but he would never cut anything.  He had the correct axe, a house and food, empty inventory space and no requests.  The trees were growing on a hilly area so I grew some trees on a flat area near his shack and he still wouldn't cut them down.

I ended up just removing him at the end of the day.

**Comment by Paril** [comment]
I have a lumberjack that just stands on a specific spot, clearly trying to get to *something*. I think it'd be super handy if there was some kind of debug wand where you can "use" a villager and it draws a line to the place they're trying to get to and to explain what their goal is (ie, "Lumberjack is trying to get to block x, y, z to cut down Oak Wood."). Similarly they should give up on goals and not try them again for a while if they couldn't reach it.

**Comment by mojoyup1528** [comment]
In the cfg there is a pathfinder option I believe, but it might still be buggy. Not sure how it works yet, testing it now myself for lumberjack standing doing nothing even with all essentials. 

UPDATE: I believe the pathfinding boolean might be to help the citizens/workers not get stuck, as it shows now path visually, but restarting the server for me also helped. Took 2 minutes. As of so far, the option for pathfinding on true does not cause lag. Hope that is helpful. 


UPDATE 2: So, about 3 hours in (on and off), the lumberjack did the same thing again, open server. So doing another reset but other players will become aggravated I am sure. Not sure what it is anymore, but that suggestion above is now a temporary fix. 
I would call this an open case still

**Comment by mojoyup1528** [comment]
Still cannot find client side way to fix this behavior, nor server resets anymore is working :/ At a loss.

**Comment by Raycoms** [comment]
Patience until I'm back from holidays

**Comment by Paril** [comment]
I might know partially what causes this, @Raycoms. I've noticed that Lumberjacks will spend a lot of their time wandering around my town picking up random drops, like Balls of Fur dropped by cats inside my house (nowhere near trees, etc). I think what's happening is they're trying to fetch items that are dropped underground by mobs dying from things like bees, and just stand above where the items are since they can't find a path to them.

Maybe they should only try to pick up saplings + the drops from the saplings? I also had an idea where the lumberjacks themselves don't make it their priority to pick up items, and instead the Deliveryman will go around picking up items that they find (accessible items, and only above ground maybe?) along their routes or when they have no deliveries to make. This way, the deliveryman handles the item delivery of saplings, if the Lumberjack is missing saplings to replant they won't just despawn from them not picking them up after cutting trees and if you have enough Deliveryman they can handle picking up the dropped items and handing them out when the Lumberjack needs them delivered (assuming they put in Delivery requests for the saplings they may be missing). Could also have a toggle in Deliveryman hut to turn on/off collecting items and turn on/off delivery request fulfillment, that way you can specialize them in picking up items.

**Comment by Raycoms** [comment]
Yeah this part definitely needs a bit of love

**Comment by mojoyup1528** [comment]
No worries, its not too bad a deal just when you have time is awesome :) Your time is very appreciated!

**Comment by Raycoms** [comment]
@someaddons did you work on this? =D

**Comment by someaddons** [comment]
didnt change stuff regarding vanilla trees yet, but started looking into it, he doesnt seem to chop the taller jungle trees either

**Comment by Raycoms** [comment]
He stopped doing that again? What a pain.

Am Do., 8. Nov. 2018 um 19:45 Uhr schrieb someaddons <
notifications@github.com>:
