### ISSUE TITLE
Barbarians are invisible/attack you from hundreds of blocks away with newest update

### ISSUE THREAD

**Issue by sharkck** [ldtteam/minecolonies#2905]
### Minecolonies version
Version: minecolonies-1.12.2-0.9.13-BETA-universal
### Expected behavior

Barbarians come into the town to attack/be killed

### Actual behaviour

Barbarians, almost from the moment they spawn, start attacking you.  I have spent entire in-game days trying to track down these invisible/long-range barbarians that are just constantly hitting me from afar.

Usually, disconnecting and reconnecting forces them to teleport? nearby where you can see them and kill them.

### Steps to reproduce the problem

Wait for a barbarian raid.

**Comment by Raycoms** [comment]
I checked back with forge on that, and it seems that the invisibility of mobs is a general minecraft vanilla issue (can be observed when dealing with invisible players as well). Unfortunately, there is not much we can do to solve this. When you observe this, relogging should fix it, since it is a client side display issue.
