### ISSUE TITLE
Priest

### ISSUE THREAD

**Issue by dudasl** [ldtteam/minecolonies#2957]
I have in my mind idea to incorporate priest to the minecolonies. It's not complete, but may we start discussion. Peoples need to care for their souls.

Priest should decrease unhappy of colonists. Let say 1% per level. Sometime is hard to fullfil all needs of people. Level of building should determine how many people should be handled (5 per level).

The second possibility is also decrease time when colonists refuse work because death of someone (not sure how).

Priest also need some holly building like church, chapel, musk etc.

It should have some requests. But here I'm out of idea. Candle will be fine, but that need new craft item and how to do it.

**Comment by Raycoms** [comment]
Sounds like an interesting idea for sure

Am Do., 11. Okt. 2018 um 04:08 Uhr schrieb Ladislav Dudáš <
notifications@github.com>:

**Comment by ghost** [comment]
Ok, there's actually a couple of interesting things we could do with this, Off the top of my head, I think the priest could "Bless" crops and make golden apples and carrots without the need for gold. Additionally, we could make Golden crops increase Happiness in Citizens. 
There's also Healing, a Priest may "cast" thrown potions of health at guards when they need it, though that would require some interesting ways on how to organize that grouping.

Honestly though, the priest is a little Iffy, especially when there isn't any established Deity or equivalent in Vanilla Minecraft, which means we would need to establish our own, or keep it Dragon Quest/Final Fantasy Generic "Priest." I like the idea of keeping our mod genre-neutral, so that players can use it more immersively with other mods.

Additionally, I think there are just better outlets for Happiness management out there. Off the top of my head, FireRuner's Florist Job seems more suited, just create a Bouquet item that requires flowers to craft, and giving it to a citizen increases their happiness. Gives the Florist something to do besides make color Dye, and makes them more integral to the town.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
