### ISSUE TITLE
Guards need improvement

### ISSUE THREAD

**Issue by sharkck** [ldtteam/minecolonies#2975]
### Minecolonies version

Version: 1.12.2-0.10.1-RELEASE

### Expected behavior

Guards to be able to handle themselves even in a single encounter. Are they supposed to be able to kill enemies or are they just for looks?

### Actual behavior

Guards, even when you give them armor, are always dying.  

### Steps to reproduce the problem

Equip your army of guards with weapons and armor and let night come.

Watch the slaughter of your guards.

I know this is possibly a touchy subject but these guys may need some sort of boost or something... particularly when you upgrade their towers maybe?  It just seems that they are way too squishy and do nothing but either eat up resources or spam the chat when you dont give them anything.

**Comment by Nightenom** [comment]
The problem is they need to level up (simultaneously with towers), they were over-boosted, now "under-boosted". Give them a time to level up by helping them

**Comment by SulpherStaer** [comment]
Even if boosting them with a Bottle o' Enchanting (xp bottle) the level 2 building lvl 4 guard cannot take a single zombie on his own.

**Comment by Paril** [comment]
Mine take down enemies no problem, even Endermen. They do die at times but my current set of 12 guards have managed to survive quite a while. They usually only die if they don't eat when fighting or something.

**Comment by bonzai1102** [comment]
The Guards are strong enough.
Friendly Fire trough Sweeping Edge an Thorns on my Items are a much bigger problem.
I think i had to kill more Guards than Mobs did because of that.
A decend levelled Guard kills you in no time and the attack range of the Guards is much to big.
If you hit them accidently, you have no chance to escape.
They are faster and hit at a so quick rate... You're done. ;)
And it's no fun to get your items back in 50 person village,...
