### ISSUE TITLE
Problems with builder pathing

### ISSUE THREAD

**Issue by idontknow12** [ldtteam/minecolonies#3005]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.24-ALPHA-universal

### Expected behavior
I ordered a lumberjack's hut to be built using the building wand in the middle of a bunch of trees.
Also ordered some other builder's huts to be built above some craters with water in the middle of the colony so the builders could seal it and make the terrain more joyful to walk around.

I expected the builders to do the cleaning and building and get the job done eventually when i supplied them the materials and the tools they needed.

### Actual behaviour
The lumberjack hut's builder kept trying to clear the leaves on top of the trees, trying to path up there and sometimes falling down, then trying to get back up there again. He couldn't get to some leaves on trees on the other side of the build area so he just moved as close as he could and stayed idle up there on the leaves, day after day. The building would not be built at all if i just left him to his devices.

The "ravine closers" would constantly get down on the hole and get washed away by the water, and then get up again and do the same thing. I constructed a few walkable planks so they could move around easier and had to drain most of the water. Then they wanted some shovels to dig like 4 heights below where the builder's hut chest was placed, which made them dig and get stuck in the hole they created, so they couldn't go back to the town hall at night.

I think it's a bit annoying that these guys have to be babied so much...
In 1.10 they just moved to the corner of the build site and did all their work from there. It was a bit less realistic but it got the job done without having to check up on every builder. We already have to check up on the materials at the builder's hut and supply them, i don't think we should have to also check up on the worker's themselves to see if they are actually building the stuff.

### Steps to reproduce the problem
1. Build a lumberjack hut in the middle of a bunch of trees (I did it in the middle of dark oak trees and the dark oak hut).

**Comment by GanthorPrime** [comment]
i want to add to this, maybe some improvements to the build process.

- keep the pathing, reduce the amount of spot changes

- use the sometimes more eficient 'build from the corner thing' under some 'stuck' criteria: if it get stuck one time (ie need to be recalled / tped), it will go stuck again for sure.

- 2 pass cleaning, like the 2 pass building you can see when torches, water other entities / decorations in the hut:
  first pass: ignore leaves (let them decay while cleaning), falling blocks (sand, other), water, (builders tries to clear falling water every time if you build something near the ocean), cant thing on others like that.
 second pass: clear all

- a way to process the 'schematic' in advance, to, ie. know what materials will be needed next, to decide on the materials to grab from the hut, and reduce the amount of supply, return, resupply on schematics with many different block types.

sure all that is easy to say but hard to do, i dont want to sound demanding, anyways here are mi experience and toughts:

i im playing singleplayer and multiplayer (dedicated server) since 1.11 versions,  were they build from a corner and 'get the job done'. I apreciate the 'realistic path finding on building' thing and i imagine it was a big effort, but in is actual state, feels that it hurts the gameplay more than the benefits. i do not know if the intention is to force the player to solve the scaffolding before the construction to get ultra-realistic construction but at least i think what the players want is 'i got the resources, you build the thing' in a reasonably time :).

While i feel building has goten more dificultin general, im not sure if we can explain that 100% with the pathing feature: Before, in big schematics, sometimes your builder got stuck because precicely of triying to reach that far 'corner' unnecesarily. Maybe the solution is to keep both the patfinding thing, and the unrealistic but more efficient 'building from the corner', i dont know, maybe a 'smart corner', a spot reachable, not over the construction level currently on, without water in the path, or in the top of trees,  reduce the amount of 'spots' changes during building. etc. 

it seems the key to many building things is to be able to preprocess the schematic in some way:  to know what places will be unreachable, or a trap hole, and avoid going there and get stuck, dronwned, burned, etc (you see how much pain we feel, when that old virtual builder die, because of our orders).  More important than that: It can also helps to know in advance what materials will be required, to plan the grabing on the builders hut. that last is,  for me, the actual more anoying thing about building: to see the builder walk over and over to his hut to grab materials: build 3 blocks and return to hut to grab a material that he grabed before but returnedd because of a full inventory. 

I agree that the AOE villagers building the big castles from the ground were laugable, but in here, with small buildings, building from a corner was not really a big let down, maybe in very big huts / decorations were sometimes you cant see the builder (because is in a far corner).

wow. sorry for the bad english and the extremely long post.

**Comment by Raycoms** [comment]
Should be better now
