### ISSUE TITLE
barbarians are rude

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#3037]
### Minecolonies version

Version: 1.12.2-0.10.30 alpha

### Expected behavior

- barbarians not to be able to break certian blocks

### Actual behaviour

- barbarians basically broke a barracks tower when attacking

### Steps to reproduce the problem

TBH idk it might of just been a 1 in a quintillion fluke
1. 
2. 
3. 
4. ... Profit

**Comment by marchermans** [comment]
This is intendet behaviour. We do not want you to setup a wall and be done with it. Neither do we want you to dig a trench and have them fall in there and be done with it.

If they notice they fell in a hole they will climb out of there, if they noticed you build a nice wall to keep them out, they will dig through it.

**Comment by Raycoms** [comment]
He meant, they broke the minecolonies barracks tower block, and not the minecraft blocks around it.

**Comment by marchermans** [comment]
We can discuss left and right. It is irrelevant. They should break blocks on their way in. They should break the tower blocks on their way in. They should break through buildings if you build the door shut.

If you do not want to deal with them. Turn them off in the config. Or face the consequences.

If it causes other issues then we can talk about it. But this issue is not complaining about followup issues by the breaking. Just that they are rude. In other words he does not want them to break the blocks -> Turn it off in the config.

**Comment by CharCharthemonkey** [comment]
umm i was told to make a github issue from discord so thats wat i did i wasnt trying to complain bout it i was doing as i was told
