### ISSUE TITLE
Construction enhancement #2

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#3045]
Seperate the Building process further into:
1. Cleaning/digging
2. **Scaffolding**
3. Building the building

Scaffolding would be constructed around the not yet built building, to assist with building it. Could make use of Ladders to allow builders to climb up. Only needed when the Building actually has a certain Height, e.g. 5+ blocks above the ground. Also the 2. scaffolding task should be done by another new hut, not the builder himself.

**Comment by Raycoms** [comment]
Depends on https://github.com/ldtteam/minecolonies/issues/3044

Requires some additional steps
- [ ] Add a new step into entityAiStructure which calculates the outline of the building
- [ ] on clearing step we can calculate how many blocks the block is underground (how many blocks deep the builder has to dig)
- [ ] after clearing step a worker can do it
- [ ] worker ai needs to get the materials (fence, slabs, ladders, planks) (Should have a way to select the material)
- [ ] Should only be needed if building is higher than x blocks (and not in the ground like the star wars style for example)

**Comment by BonaireDreams** [comment]
Cool ideas. Digger & Scaffolder should be the same hut. Otherwise a new colony with 4 initial citizens needs 3 right away to be digger, scaffolder and builder.  The scaffold could be like the Immersive Engineering scaffold and can act as ladders for both the workers and players. No extra ladders needed to go up and down. The system already places the fence to outline the building.  Replace that with scaffolding to the height of the building.  Scaffolder takes down scaffolding when hut is complete so it is returned to inventory and can be used again. Scaffold recipe should be fairly simple. Sticks and planks, maybe like the vanilla fence recipe with 1 extra row of planks/sticks.

**Comment by Raycoms** [comment]
The builder will execute the tasks if the workers are not available. The
builder will just do them "less efficiently"

Am Fr., 9. Nov. 2018 um 16:13 Uhr schrieb Gerald <notifications@github.com>:

**Comment by someaddons** [comment]
or the level 1 hut could be very simple/easy to build so that its no real hassle setting up 2-3 huts at the start

**Comment by Asherslab** [comment]
might mention that scaff is usually put up by the builders themselves in the real world (however digging/etc isn't)

**Comment by Raycoms** [comment]
In Germany small things they put it up themselves, big things there are
companies which do only that with people who do only that.

Am Fr., 9. Nov. 2018 um 19:01 Uhr schrieb AshersLab <
notifications@github.com>:

**Comment by ghost** [comment]
Maybe level 1 builders will do everything, but as they improve they specialize. So a scaffolder is a level 2 building upgrade to the level 1 builder, but a level 2 builder avoids scaffolding and at 3 just doesn't do it. Maybe make the miner a level 2 or 3 digger specialization. Such a mechanic could have a lot of uses. In the long term it might even make some openings for adding custom workers.
