### ISSUE TITLE
New Worker: Forager

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#307]
Early Game worker,

Will wander the colony randomly, generating Food, Materials and more exotic items.

Suggested Skills - Dexterity, Intelligence

Worker wanders, and then stops, scrabbles around a bit and then "finds" and item (This should take 20 seconds per cycle)

Could be a chance based system to find food, materials (Wood, stone, sticks etc.) which gives higher chances of finding decent stuff the higher level he is (and his hut)

Another easy source of food at lower levels, plus basic resources.. higher levels could create more exotic blocks, tools, armour or almost anything we want him to be able to find (Ancient Tomes for the enchanter ;) )

Could be - 

Chance to find nothing = 50% -1% per worker level (50-0%)
Chance to find food item = 50%-0.5% per worker level (so almost exclusively food at lowest level)
Chance to find common item = +1% per worker level (0-50%) (as nothing chance reduces, this chance increases)
Chance to find rare item = +0.5% per level (0-25%) 

So at level 1 - 49% nothing, 49.5% Food, 1% Common, 0.5% Rare 
at level 10 - 40% Nothing, 45% Food, 10% Common, 5% Rare
At level 30 - 20% Nothing, 35% Food, 30% Common, 15% Rare
At Level 50 - 0% Nothing, 20% Food, 50% Common, 30% Rare

Level is capped at 10 per building level

**Comment by Kostronor** [comment]
I suggest we make this similar tot eh Ex Nihilo system, but just without the sifting.

So we have some json configs of what he finds so modpack creators can use this as a means to supply some rare items without offering ways to mass produce them.

Can we make it so that he also picks up real items, maybe stuff that someone just forgot or so.

**Comment by pmardle** [comment]
Yep sure.. Useful to have a worker that can "find" anything we don't want to give away too easily.. :)

Things I'd like him to "Find"

Common Stuff
All sapling types (so player doesn't HAVE to go off and find them all himself)
All flower types (Ditto above)
All Basic Vanilla Stuff, Woods, Dirt, Gravel, Stone, Cobble, Flint, Sticks, String etc.

Food Stuff
Apples, Seeds of all types, Carrots, Potatoes, Radishes, Fish.

Rare Items
All items you can get from Dungeons. (Saddles, Name Tags, Records etc.)

**Comment by WORMSS** [comment]
Like the Saplings/Item Types(eg, string flint, sticks)/Food/Dungeon 

But should he "find" blocks of cobble, gravel and dirt? Is that not miner? And wood being LumberJack?

I mostly agree with this because it taken me and my wife 20 odd hours (spread over 5-6 days) to fine acacia trees.. The seed for my world must have been particularly bad.

**Comment by marvin-bitterlich** [comment]
@WORMSS I'd say he finds stuff. And it doesn't have to be blocks. Maybe the Ex Nihilio things like dust etc. or small stones where 9 form a cobble

**Comment by WORMSS** [comment]
Oh, nuggets of things could be good.. Seeds of potatoes/carrots/ etc 👍

**Comment by harleypig** [comment]
Have an option where he clears the groundcover. Possibly even a config option to allow for searching out and removing groundcover instead of just as he's randomly walking around.

**Comment by Raycoms** [comment]
I think we don't need this anymore since we actually got a sifter.
