### ISSUE TITLE
Citizens get stuck crossing the drpmedieval bridge

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3165]
### Minecolonies version

Version: 0.10.77-ALPHA

### [Drpmedieval](https://minecraft.curseforge.com/projects/dark-roleplay-medieval) version

Version: 0.3.0.5

### Expected behavior

- To cross the bridge normally
### Actual behaviour

- Citizens try to cross the bridge, but get stuck once they reach the end, and pushing is required to get them off the bridge.

![2018-12-13_23 30 43](https://user-images.githubusercontent.com/12000593/49988794-ba63f100-ff3d-11e8-8f68-9d392822e186.png)

### Steps to reproduce the problem

1.  Obtain a hanging bridge item from the drpmedieval mod.
2.  Place the bridge to an island.
3.  Have the builder try to build something on the opposite end.
4. ... Profit

**Comment by Raycoms** [comment]
Thanks for reporting this, please be aware that improvements regarding mod supports are implemented based on popularity of the mod and how gamebreaking the issues are (crashes etc).
Unfortunately, since we have limited time it might need a while until we get to this.

**Comment by WenXin20** [comment]
Ok, that's fine, I'm not in any hurry. Thanks.

**Comment by hron84** [comment]
@WenXin20 I do not know if you did this or not, but it could be easier if you report it to the DRP side too and mention this issue for them, because it's possible to there is a bug on the other side, not in MineColonies. 

Also, you can make things easier if you check if e.g. zombies can cross the bridge without any problems. Minecolonies path finding is a little bit different but if I guess correctly checking obstacles is roughly same in both path finding code.

**Comment by WenXin20** [comment]
Zombies appear to cross the bridge pretty well most of the time, but I'll try reporting to the other mod author as well. 
Also, adding waypoints to both sides of the bridge doesn't seem to help, Minecolonists either go around the bridge on a 3x longer path, or they get stuck on a corner of the bridge.

**Comment by Raycoms** [comment]
did you check the newest version?

Am Do., 27. Dez. 2018 um 14:14 Uhr schrieb WenXin2 <notifications@github.com

**Comment by WenXin20** [comment]
I'm using version 0.10.87-Beta right now.

**Comment by WenXin20** [comment]
I just tried using version 0.10.92-Alpha, but colonists still try to walk around the bridge.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.

**Comment by Lariag** [comment]
When building something from a custom building template that had yellow fairy lights from "Fairy Lights" mod, the builder requests white ligths instead of yellow and no matter what light color I give, the builder keeps asking for them.
When I check the building material in the scroll it says that I have the lights in my inventory, but when talking to the builder there is no fullfill button available.
I noticed that once crafted, the lights have 1 nbt tag.

**Comment by ravenbuilder934** [comment]
What does that have to do with *anything* in this two-year-old issue? Please open a new one.

**Comment by Lariag** [comment]
I ment to answer on the "mod compatibility requests" that seem to be still active issue but somehow it ended here.
Will create a new issue.

**Comment by ravenbuilder934** [comment]
Ah, mod compat issue. Yeah posting there is fine
