### ISSUE TITLE
fix Builder should consider grass as dirt

### ISSUE THREAD

**Issue by schafhierte204** [ldtteam/minecolonies#3265]
### Expected behavior

Builder threats grass as dirt

### Actual behaviour

Builder picks up one dirt block at a time and places it.
 

### Steps to reproduce the problem

Build a building in which the builder has to place grass.

**Comment by Raycoms** [comment]
Yeah this has been talked about many times. And there are three options:
- Let the builder place free grass
- Require the builder to require grass blocks (requires silk touch)
- Let him place dirt instead of grass, it will eventually grow over.


Am So., 13. Jan. 2019 um 14:40 Uhr schrieb shafhirte204 <
notifications@github.com>:

**Comment by GanthorPrime** [comment]
dirt will not grow grass in certain biomes like vanilla desert, So if you have garden decorations for desert  placing dirt instead of grass will be a  problem, also note that flowers need grass. In addition, dirt will not grow on some conditions, i.e. no clear sky above.

Maybe that need to be a consideration on the scaning side (the player preparing the schematic), because it mainly depends on the intention of the building:

- place dirt if you want your decoration / hut buildable in early game (no silk touch), and you know that the biome intended for the building can grown grass.
- place grass if its key to the building intention and need to be placed in biomes / conditions that cannot grow grass (like desert, or in caves)
