### ISSUE TITLE
Can't craft Spruce Shingles in Sawmill

### ISSUE THREAD

**Issue by Dranemra** [ldtteam/minecolonies#3305]
### Minecolonies version

Version: 1.12.2-0.10.146-ALPHA

### Expected behavior

- 
Looking to have Sawmill craft spruce shingles for building.
### Actual behaviour

- 
Trying to add the recipe to the sawmill, I get the following error:
"Unable to store the blueprint. Either the Sawmill has no space for any more blueprints, or the blueprint doesn't correspond with its profession."

### Steps to reproduce the problem

1. At the Sawmill hut block, Click on Teach Recipes
2. Put the components in the grid as per recipe for the spruce shingle
3. You will get the error stated above.

![2019-01-26_17 50 39](https://user-images.githubusercontent.com/43527223/51793196-f15f3080-2192-11e9-9e2a-3d820f46e785.png)

**Comment by averman** [comment]
https://github.com/ldtteam/minecolonies/blob/539ff23e0989c2a32e29ae7588d72372a94c472b/src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java#L117

This line is never evaluated to be true, because one of shingle ingredients: brick
somehow in my build are having name: ingotBrick
because of this line,

https://github.com/ldtteam/minecolonies/blob/539ff23e0989c2a32e29ae7588d72372a94c472b/src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java#L107

it will return false before evaluating it's shingle or not
