### ISSUE TITLE
[FAIL] Updating packaged mods

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3306]
Minecolonies: 0.10.109-RELEASE

I just had a pack update rejected for shipping with an outdated/deleted version of structurize in the mods/memory_repo/com folder. Upon investigation I have discovered that this mod is unpacking that version. If possible, could you look into updating it, or perhaps changing to use the structurize files on curseforge directly, as a dependency?

"
 Notes:
The following file versions have been removed from CurseForge: overrides/mods/memory_repo/com/structurize/structurize/1.12.2-0.10.25-ALPHA/structurize-1.12.2-0.10.25-ALPHA.jar The modpack will not be approved until these files are replaced with versions that are currently available. 
"

**Comment by marchermans** [comment]
This is not a minecolonies problem. We always package the best compatible structurize version with minecolonies. If you upload a pack to curseforge ypu have to delete the memory_repo directory. It is created by Forge to unpack the libraries of mods. And it is the only fully official way of handling dependency distribution with a fat jar.
 
As such I see this as a no issue, and you as mod pack maker just have to be aware that this folder is not meant to be uploaded to curseforge since it get automatically generated on first launch by Forge anyway.

**Comment by ghost** [comment]
Alright, thanks for the info. The reason I have been uploading it is that at one point I had a mod saving other stuff in there, but apparently that mod is no longer in my pack. Sorry for any trouble caused.

**Comment by marchermans** [comment]
No problem. You caused no inconvenience.
