### ISSUE TITLE
Giving bread to a villager results in "The food I have is too raw to eat!"

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#3340]
Version: minecolonies-1.12.2-0.10.162-ALPHA-universal

### Expected behavior
The villager should not complain about bread

### Actual behaviour
The message "The food I have is too raw to eat!" is written in the chat. But the villager still eats it.

### Steps to reproduce the problem
1. Have a hungry villager and no restaurant (yet)
2. Give bread (because it's cheap and easy to make)
3. Ignore it's complaints and move on :D 

PS: I don't have Pam's harvest craft or similar in the pack - and I checked with JEI - I can't put bread into a furnace to make toast or similar things.

**Comment by QueenBonnydust** [comment]
I am also experiencing this issue and additionally:

### Expected behavior
The builder should eat the bread given to him when hungry.

### Actual behaviour
Builder may eat however much bread is required when bread is first given to him but then places it in his builders hut and later complains he is hungry and needs something to eat forcing you to enter his hut retrieve the bread and give it back to him. Sometimes triggering the "too raw" comment as above and often this repeats itself during the next thing he builds.

1. Place a builders hut, and have builder assigned. Give builder bread.
2. Give bread (because it's cheap and easy to make)
3. Get him to build something and he will eventually dump his food in his builders hut then request a restaurant because he is hungry.

**Comment by DaanSelen** [comment]
I still have this issue with cooked steak.

**Comment by uecasm** [comment]
> I still have this issue with cooked steak.

Does your modpack add a recipe for "burned steak" or similar (cooked steak in a furnace changes into something else).  That's why.
