### ISSUE TITLE
Alpha.164 - Icons

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3352]
### Minecolonies version

Version: 
0.10.164-ALPHA
### Expected behavior

Icons for items and recipes
- 

### Actual behaviour

black-pink square
- 

### Steps to reproduce the problem

1. 
I use JEI 4.13.1.225 (last stable release)
![2019-02-10_19 37 29](https://user-images.githubusercontent.com/46534073/52536467-04b1f480-2d6c-11e9-9866-49a2c3a8e185.png)
![2019-02-10_19 37 35](https://user-images.githubusercontent.com/46534073/52536471-0e3b5c80-2d6c-11e9-8075-32a55c31321d.png)
![2019-02-10_19 38 14](https://user-images.githubusercontent.com/46534073/52536473-14c9d400-2d6c-11e9-994a-fcefe34ec914.png)
![2019-02-10_19 38 16](https://user-images.githubusercontent.com/46534073/52536475-18f5f180-2d6c-11e9-86aa-d794242aba4c.png)
![2019-02-10_19 38 18](https://user-images.githubusercontent.com/46534073/52536478-1d220f00-2d6c-11e9-9cbb-02e97daa5eb1.png)

2. 
3. 
4. ... Profit

**Comment by Wissi** [comment]
Please update your version to the latest ALPHA. 
This issue is a modpack issue, where another mod is causing a conflict.
Use the latest version of the file and if it still generates this issue, report back to the modpack author. 
This does NOT occur with minecolonies alone.
And join us on [Discrod ](https://discord.gg/uCUH8dM)for questions, comments and faster reply.
