### ISSUE TITLE
Alpha.170 - Guard cannot wear armor from extra metal

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3370]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

In query for armor, list many kind of metal for armor, but bronze armor not wear, but silver helm and tin chest put on.
Bronze, silver and other extra metals from "Thermal Foundation" mod.
![2019-02-12_23 09 11](https://user-images.githubusercontent.com/46534073/52664918-4df47680-2f1b-11e9-8817-1ecf3657bb3f.png)
On screen silver helm, tin chest and other gold armor (helm and chest have different color)
- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Apollon-Theos** [comment]
Maybe cannot wear armor with "Armor Toughness" ?

**Comment by Wissi** [comment]
Again. Answer is in [WIKI](https://wiki.minecolonies.com/source/systems/happiness).
Read WIKI first.
And visit [Discrod ](https://discord.gg/uCUH8dM)for gameplay questions. This is for Bugs/fixes support only.

**Comment by Apollon-Theos** [comment]
WIKI is not true, because in your WIKI not described that Fisherman's Hut MUST be build in a level of river.
I build water pool in a level of Hut, but fisher not catch fish from pool and walk river's coast.

"Farm" can be installed on sand and farmer stand near scarecrow all time :)

**Comment by Wissi** [comment]
This "issue" is for Armor.
If you have other legitimate issues please report with all details.
Recommend using the latest ALPHA first. If in modpack, then list all mods being used. 
Not all mods work well together (this is a know concept for any modpack maker and all developers).
If we can find a modpack incompatibility we will let you know so you can contact the modpack author or change/remove conflicting mods.
Other than that we will test your issue with our mod only and if it's not happening then will be closed due to what I just aforementioned. 

Fisherman can be built at any level and fisherman will search for water  (above or below his hut level) to find water and work. This has been tested. Check WIKI for correct pool size?
Farmer and all worker will be slow at level 1 building and if they have low stats. ground must be hydrated and tillable (like any normal farm) You can start to till and plant land for farmer first to speed up the farmer.
And join us on [Discrod ](https://discord.gg/uCUH8dM)for questions, comments and faster reply.
