### ISSUE TITLE
Builders hut is bugged and wont build again

### ISSUE THREAD

**Issue by ActualDio** [ldtteam/minecolonies#3467]
Version: 1.12.2-0.10.202-RELEASE

### Expected behavior
I tried to move a builders hut (Dark oak style) with the building wand after it was built by destroying it and then placing it in a better place. I thought it would just reset and if I clicked rebuild it would rebuild it.

### Actual behaviour
Instead all that happens is once I place it in the new place (the chest is a few blocks above the ground) it shows me the button to build the hut but when I go to the next page it says it is 100% complete without it actually working as a builders hut because it will still prompt me to build it without anything getting built despite it having the resources in its chest and a builder right underneath it

### Steps to reproduce the problem
1. build a builders hut in a dark forest with dark oak style
2. let it finish
3. destroy the chest and replace it with the building wand in a new location ( now the chest is not on solid ground)
4. try to build it again

I was using it in the Life in the village pack by xDreamz.

**Comment by spacewolfcub** [comment]
The only way Minecolonies can address that kind of bug is by releasing a new version. 
Life in the Village modpack has an old version of Minecolonies. 

If you are playing in single-player, you are highly encouraged to update the Minecolonies file to the latest alpha (v 215), which has the latest fixes and new features. 
[https://minecraft.curseforge.com/projects/minecolonies/files](https://minecraft.curseforge.com/projects/minecolonies/files)

If any of your current buildings have custom building blocks from Minecolonies (the white blocks with timber shapes or the cactus planks/etc) then they **might** disappear from your world because the version in that modpack is so old. You can fix this by repairing buildings with your BuilderNPC. Or editing the NBT of the savegame directly.

If you are playing on a server, we cannot help you, and recommend your server's admin update the Minecolonies file in their server. 

If you still experience this problem using the latest alpha, please let us know so it can be fixed in a future version. <3
