### ISSUE TITLE
Builder needs the prefetch materials

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#35]
Dman should not pick up food in worker's chest
Dman should gather broken tools.
Dman pre fetch items builder needs before he needs them.
Dman should always send food to houses even if not hungry.

**Comment by Raycoms** [comment]
I kinda like that because that way he isn't thaaat fast.

can I close this?

**Comment by pmardle** [comment]
Gets really tedious when you have a large colony and for every material change he has to walk 100-200 blocks back and forth.. 

Happy to leave as is if the consensus is to do so.

**Comment by cheongchan** [comment]
I agree that it is tedious. For multiple builders i think the queue for the builder should change depending on distance to job. This way two builders dont pass each other to go across town to build something just because it is next on the list. Some kind of optimization could help here. 

The builder should:

0. Fill his own inventory will all available items from his hut needed to complete building. 

1. Determine how far the jobsite is and percentage of blocks he has. If percentage too low he sends out a request to delivery boy and waits for a specified amount of time (2x the amount of time it takes to get to the jobsite from builder hut?). 

1b Otherwise, Start going to job site and start building.

2. As he leaves (if he is missing something), he should send a request to the delivery boy to remove all the stacks from the hut inventory that does is not required for the current building and get anything he is missing if possible. 

3. The delivery boy then goes to the warehouse to check if there is anything he can get. If not go to the closest crafter/logger/miner to get raw materials/tools. (this could be complicated especially if crafting available at some point) Otherwise does nothing moves to next job and lets request stand for player to fullfill. 

4, If there is stuff he runs back and forth until builder hut has everything.

5. Builder comes back dumps as much extra stuff as he can (that he has somehow picked up). 

6. Go back to zero until building finished

perhaps some other corrections to close out the logic. Something like this could be nice.

**Comment by Rhodizzle** [comment]
One way to fix this might be to regulate block placement speed and number of blocks related to the build per worker level. Example: A level 1 builder can only grab 15 items and place them one per second. Each level doubles the items and halves the speed of block placing.

**Comment by alanman** [comment]
Sorry, replying to quite an old post.  But since it's still open...

A simple resolution might be to add a "hold inventory" to the deliveryman chest.  Maybe make it half as big as normal inventory.  Like the scarecrow, you just put in one piece of any item you want the deliveryman to keep on his person, and he'll try to keep a full stack of that item. Need more? put a piece in two slots.  Then have him stock up every time he goes to the warehouse if stock permits.

**Comment by Asherslab** [comment]
So is this fixed now?
