### ISSUE TITLE
[Feature Request] From LadyShatana (HangryHobbit) on Discord. Anti-Waypoints.

### ISSUE THREAD

**Issue by TheStrato** [ldtteam/minecolonies#3545]
### Minecolonies version
Future

### Expected behavior
Much the same way that current waypoints provide a preferred path for colonists. How about "anti-waypoints" that can restrict them from taking a particular path of blocks. This would be helpful for a number of reasons such as being combined with regular waypoints but as border/barrier blocks to ensure that they stay on a given path, or to make sure they can't enter specific/hazardous buildings by being placed at all the entrances. It would also be helpful to use like barrier blocks to keep them from falling off of cliffs and such and allow for a lot more design options within a given colony without having to use visible deterrents like fences and the like.

**Comment by GanthorPrime** [comment]
Seems like a good idea to have a 'fence like' invisible block to block the entrance to some buildings, although i havent encountered the need to use that: im using fences on cliffs, iron doors (button activated) to block entrance to hazardous buildings and im not seeing citizens triying to swimg in lava for quite some time. Only hazard related issue i keep seing are cactu. In other thread i suggest cactus block to be treated like fence blocks to avoid citizens / builders walking over them and dying. Of course all this, assuming the logic to avoid fences in pathing can be replicated to other blocks.

If you add that remeber to give a way to track and remove them. (i dont remeber at this time how we remove normal waypoints added with decorations)

Just i want to mention l found impractical to surround an entire cliff / laggon with an invisible block just to keep citizens from falling - climbing / swiming, that sound more of a patting enhancement needed: like citizens always priorizing plain terrain pating over swiming / climbing. 

With that say, in most cases, you can place 'some' waypoints surrounding the cliff / hole / pool in a way that the distance between them match you desired path, but however, sometimes you cant: there is a safe path between 2 waypoints you dont want them to use (i.e because they need to swim / climb). In other words, sometimes you want to 'force' citizens to use a path that is not necesarily the shorter way. 

Maybe a kind of waypoint with 'higher priority' that normal waypoints in the  chosing of avaible waypoints to the target. This waypoint will let you to build a 'troncal' path, like a transited avenue, without the need of 'walling' the entire place to force the use of that. The objective is that citizens priorize pathing with these waypoints over normal waypoints (if that can put them nearer to the target), despite of having normal waypoints avaible. when citizen reach the nearest hight priority waypoint to the target, they can path using normal waypoints.

**Comment by marchermans** [comment]
The problem here is, performance. Pathing AI in Minecraft is expensive. And yes we have been designing alternatives which will allow all of this. But these are still a bit out.

@Raycoms what do you think? Anyway we can add negative waypoint markers?

**Comment by Raycoms** [comment]
I think negative waypoints are possible, but easier would just be invisible
walls

**Comment by Nightenom** [comment]
I haven't played mc thoroughly for at least two years, but my opinion (based on my knowledge and skills) on that is:
if any NPC is so dumb that (s)he goes to an area where (s)he is not expected to be, I just put a solid barrier there
if there is a thing that can "route" NPCs somewhere (like minecarts, or our waypoints) I use them too (but only if I can manage them easily)
so my resolution on that would be to provide a way to manage waypoints easily and in schematics only place the most needed waypoints so a player can adjust NPCs pathfinding to their needs

**Comment by GanthorPrime** [comment]
i just re-read my own post again and i must say another type of waypoint sounds like madness lol. (now i cant figure out how that can help us more than normal waypoints)

invisible 'citizen-only' wall is the most easy thing to manage for a player also , i think. just make them visible / destroyable for players. i.e using the build tool.

**Comment by OCDCleric** [comment]
Instead couldn't you just add a tool that allows us to place/remove waypoints?
Additionally the tool can allow us to set a priority to the waypoint like the delivery system. That way we can set main roads as high priority and branching paths lower priority when deciding how to travel to various locations.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
