### ISSUE TITLE
Not able to increase Town Size in config or ingame

### ISSUE THREAD

**Issue by iTheCuteKitten** [ldtteam/minecolonies#3632]
### Minecolonies version

Modpack Version:  Mine Colonies Official Modpack V3.2  (Latest version as of now)

Mod Version: minecolonies-1.12.2-0.10.286-ALPHA-universal

### Expected behavior / What I want to be fixed

Implement a more simple command to increase the size of the area where you can place buildings around your town hall.

When I go into the config, it should work properly. There shouldn't be so many different things in the config saying "Increase size of town" and "area of placement around the center of the town". 

Maybe the command ingame could work properly? It's kind of impossible to play the modpack.

### Actual behaviour
I tried going into the config of the minecolonies modpack and changing everything so I can place buildings farther away from the town hall and that didn't work so I did the command: **/mc colony claim colony: 1 dimension: 0 range: 1 add: true** but it was really buggy to where I could only place the buildings in a weird way.

However, when I don't use the official modpack and I make my own modpack via the twitch launcher and putting the minecolonies mod along with some others mods the error doesn't exist and everything works perfectly.

Just watch the video.. It's hard to explain.

[VIDEO (PLEASE WATCH ITS SO HARD TO EXPLAIN](https://www.youtube.com/watch?v=UDuVOCzgDlU&feature=youtu.be)

### Steps to reproduce the problem

1. Download the Minecolonies Modpack from Twitch Launcher
2.  Enter a single player world on superflat in creative mode and place down a town hall. 
3. Place any building at least 90 - 200 blocks away from the town hall
4. Do what I do in the video
5. ... Profit

**Comment by ArodSnaux** [comment]
Claim changed several times and doesn't work right in some older versions. Additionally, many of the colony-size configs have been deprecated to some degree. Ignore them all,  and use your build tool instead of directly placing hut blocks... this will solve most placement problems. In the most recent versions, when you _carry_ the build tool, it _auto-allocates_ blocks to your city center, no more need to Claim!

Here's how... follow steps exactly and it should fix your issue:

1) Get the latest version of MineColonies (the 258 alpha). It's fairly stable apart from some issues with the request system in very large cities.
2) Open the game and map, then hit ESC and go into mod configs... use the ingame editor, btw, and not the textfile... this will give you any new settings you might be missing.
3) Under gameplay, turn the enableDynamicColonySizes setting to TRUE. Save the config.
4) Use the BUILD TOOL... dont' just drop the hut, this no longer works correctly... you still need to hut in your inventory, but carry the buiuld tool (yellow wand) instead and left-click the ground.

**Comment by iTheCuteKitten** [comment]
The 258 build is not the latest.. Do you mean the 288 Alpha?

EDIT: I just read the rest of your reply and I didn't even know the build tool existed.. Thanks alot!

**Comment by ArodSnaux** [comment]
oops yes, 288 alpha. sorry i type with a cat in my lap lol
