### ISSUE TITLE
multiple colonies one id.

### ISSUE THREAD

**Issue by themaddestone** [ldtteam/minecolonies#3677]
### Minecolonies version

Version: minecolonies 1.12.2-0.10.259-release

### Expected behavior

-  different colonies with different id's functioning correctly 

### Actual behaviour

-  two colonies share an id, talking to someone in the second colony brings up a person from the first one cant open villager inventory.

### Steps to reproduce the problem

1. create one colony (in the overworld)
2. create another (aroma's mining dimension)
3. colonies now share an id

is only recreated if you build one in the overworld and one in the aroma's mining dimension, i havent tested other dimensions.

**Comment by marchermans** [comment]
Officially colonies in other dimensions are not directly supported.
How ever we enabled the option to create them on a users own discretion.

That said, this should not happen: @Raycoms Something wrong with the manager or the commands?

**Comment by themaddestone** [comment]
it's worth mentioning that on further testing the id's do count up but separately for the two dimension's workaround was to build two colonies and then delete the first.

**Comment by Raycoms** [comment]
Seems to be a problem with the views. We gotta sync the views correctly so that when you enter the other dimension you get the new view.

I recently added all coded to allow colonies in any dimension, and they also get new ids (so only colonyId + dimensionId is unique).

I have to test the view part though.

**Comment by Raycoms** [comment]
Okay, I digged into this. I don't know how this mod does it, but it adds a new dimension with id 0. Which is the same dimension id as the overworld. @OrionDevelopment shouldn't they increment the ids of dimensions? How will we detect which world this is?

**Comment by marchermans** [comment]
That is impossible, if they do then it is broken, and no you need to choose one, you are free to pick the next one (via the counter), but you can pick any id as long as it is free.

**Comment by Raycoms** [comment]
I contacted them already =D

**Comment by TheMerricat** [comment]
Sorry for butting in here, but just to be clear here. 

In Aroma's Mining Dimension - the Mining Dimension is defaulted to Dim -6 and the BioSphere Dimension is defaulted to -12 in it's configs. 

If I create a pack with just minecolonies and the mining dim mod, at least in single player it's correctly doing what I would expect and there is a dim-6 and a dim-12 folder in my save folder. Adding Journeymap to the 'pack' causes the maps for each dimension to be properly created in the appropriate dimension's folder under the Journeymap folder. This was using the most recent versions published on curseforge for all the mods. So from an outsiders viewpoint it looks as if the dimension ID assignment is working properly.

The reason I bring this up is because if you've been following the saga of the official server at the moment, one of the problems that is occuring is that using teleport commands such as /warp or /home seems to be correctly moving players to the appropriate dimension but somehow leaving everything thinking they are in dim 0. So when they /spawn or /mc home they get shunted to a location in that dimension instead of being returned to the overworld. On top of that, mods like Journeymap are confused as well and start overwriting the overworld map instead of updating the pre-existing maps for the dimension. This started happening recently (but before the last modpack update).

I'm wondering if the dim 0 thing isn't a 'bug' with Aroma's mod but just a side effect of some other bad mod interaction going on. Are the two of you (OP and Ray) able to replicate these issues with just minecolonies and the mining dimension mod installed?

Again sorry for butting in, but since this sounded a lot like what was happening on the server and I don't think you two get on it much, I wasn't sure you were aware of that twist in the story.

**Comment by Raycoms** [comment]
Yeah I was able to reproduce it easily, I entered in contact with them.

**Comment by Raycoms** [comment]
Can you test this:
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/28795:id/build/libs/minecolonies-1.12.2-0.10.996-PERSONAL-universal.jar

**Comment by themaddestone** [comment]
![Annotation 2019-07-03 135623](https://user-images.githubusercontent.com/33189894/60562406-c5c42000-9d9a-11e9-9791-673bde92036b.png)
the bug is still a thing in that build, and furthermore, I can no longer delete the colony attempting to do so sent a global message for each colony member that was part of the colonies death and removed the building but left the id taken and me unable to make a new colony without console commands.

for transparency, I'm going to post my versions and mod list since the pack is a custom pack.
http://modlister.com/user/themaddestone
this should stay up to date as I add and remove mods whenever I feel like it.

**Comment by Raycoms** [comment]
It is completely valid that two colonies have the same ID if they are in
different dimensions, what can not happen is conflicts between them.
Deleting colonies only works their own dimension

**Comment by themaddestone** [comment]
ahh, I misunderstood the intended functionality then, I will find a time to test that in the next day or so. Without the ability to delete the existing colonies (which I have confirmed isn't working)

**Comment by Raycoms** [comment]
I'll test the deleting then
