### ISSUE TITLE
Recipes on my Server won't save

### ISSUE THREAD

**Issue by Gorbachof** [ldtteam/minecolonies#3772]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.259-RELEASE-universal

### Expected behavior

- After teaching a worker a recipe, they will retain it until manually deleted

### Actual behaviour

- Recipes are removed after approximately 24 hrs real time

### Steps to reproduce the problem

1. Teach any worker a recipe
2. Normal recipe functionality (workers will create items when necessary
3. Eventually workers will stop work (ie millers won't be able to fulfill needs) due to not having any learned recipes

**Comment by marchermans** [comment]
@Gorbachof We will Need logs from the server you are on.

**Comment by Gorbachof** [comment]
Sure thing!

[debug.log](https://github.com/ldtteam/minecolonies/files/3471051/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/3471052/latest.log)
[2019-08-05-1.log.gz](https://github.com/ldtteam/minecolonies/files/3471053/2019-08-05-1.log.gz)

I'm not sure if you want me to simulate anything? I just grabbed these and can almost guarantee there are no learned recipes on the server right now.

**Comment by marchermans** [comment]
Okey so I am not sure if that is related (normally not since saving has Nothing todo with it) but you have an Issue with the RS, which we discovered last month, and which I had no time yet to fix, since I Needed additional infrastructure before I could attempt a fix for it. Your RS seems to be broken.

You can try resetting it, see the wiki for that.

**Comment by Gorbachof** [comment]
Appreciate you getting back to me, but I'm not sure what you mean by RS?

**Comment by Asherslab** [comment]
Request System, it's what the dmen, workers, and etc use to communicate what resources they need, and also how they get those resources they need

EDIT: Oversimplified, don't stab me orion =P

**Comment by Gorbachof** [comment]
Got it, I'll check out the wiki for that fix.

**Comment by marchermans** [comment]
@AshersLab that is exactly what it is. Compare it to a blackboard, you miner posts a note on it saying he needs a tool, rings a bell and everybody in your town will come look at the board and the blacksmith will take the note, since he knows how to make the tool. He however needs sticks and for example iron to make the tool requested so he puts up two notes indicating that he needs those materials, and the loop starts over again.

**Comment by Raycoms** [comment]
Fixed
