### ISSUE TITLE
Minecolonies error

### ISSUE THREAD

**Issue by Hamerley** [ldtteam/minecolonies#3781]
### Minecolonies version

Version: 1.12.2

### Expected behavior

- The sawmill worker should make the materials requested by the builder

### Actual behaviour

- The worker stands still without doing anything

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Asherslab** [comment]
what version. that is your minecraft version not the mod version.
an issue like this was fixed in recent versions by @OrionDevelopment

**Comment by fr3akb0y** [comment]
I didn't play the version that came out yesterday but that one before. (minecolonies-1.12.2-0.10.341-ALPHA-universal.jar) I still had to do a lot of manual request-canceling with the sawmill. Sorry if that should be fixed in those two hotfixes mentioned in the last version (no clue what those hotfixes are) but shouldn't it be fixed in the new API thing that he did? Because that one is still not merged. Again, sorry if I am completely wrong here.

**Comment by Asherslab** [comment]
yeah, nah you're right. we had to revert that merge. forgot about that.
https://github.com/ldtteam/minecolonies/pull/3777
should fix this issue

**Comment by marchermans** [comment]
@Asherslab No #3777 Should not fix that issue
I need the API abstraction layer to write the damn unit tests that verify my patch

**Comment by Asherslab** [comment]
Okay, so #3777 leads on to the issue getting fixed in the future?

**Comment by marchermans** [comment]
Yep

**Comment by Raycoms** [comment]
done this one
