### ISSUE TITLE
Sawmill improvement?

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#3794]
The builder requested spruce stairs and the request system showed that the request will be fulfilled by the miller, but he needed some more spruce planks. I was hoping that the miller could request the rawest material which would be the spruce wood, making it into planks and then into stairs if planks were unavailable at first. I also noticed that until the miller doesn't have the necessary amount of wood to craft all the stairs, he doesn't start working.

**Comment by marchermans** [comment]
This is all by design.
Forbhim to request the rawest material, you have to teach him what the rawest material is. 
He can not start earlier due to the fact that not all resources are available yet, he does not know where the resources come from or if the currently delivered resources are even for him. As such we sadly can not change this, or implement the requested features.
