### ISSUE TITLE
[Feature] [Discussion] New storage buildings.

### ISSUE THREAD

**Issue by Asherslab** [ldtteam/minecolonies#3797]
Currently MineColonies only has One storage building, the warehouse, It also has a limitation of one warehouse per colony. This issue is a proposition for new storage building types, and also the removal of this limitation. I have talked to @OrionDevelopment and he believes it shouldn't be too hard to remove the warehouse count limitation.

After the limitation is removed, a few storage buildings i would like to see are:
1. The Silo [or alternatively Granary] . A simple storage building that stores wheat, just wheat, would only be maybe 5x5 and each upgrade level would add maybe 3/4 layers to it. A cool way of implementing this would be to have wheat blocks represent the amount of wheat stored inside, we could use just normal wheat blocks, or visually more impressive, blocks that increase in hight as more wheat is stored inside. It would need to have a storage benefit over a building like the shed (i.e. higher storage amount because it's only one item type!)
Thinking about it, this building could also possibly store seeds (of a single type). 
The building would be useful for a sort of buffer near herder huts, also it would be aesthetically pleasing!
2. The Shed [Better name pending? please suggest]. A small storage building that acts as a sort of buffer, you can select certain items to always keep it stocked with (to a limit), e.g. wood and logs near a builder. each upgrade level could increase the number of "keep stocked" items selectable and storage size (only a little, it's only a buffer). These buildings would be helpful near builder huts, also near crafters/furnace users (basically everywhere if used properly)
3. The Tool Shed [Again, better name pending?]. Used as a building to specifically store tools, would have a storage benefit over other buildings in that it would only ever store That specific type of item.
4. The Larder [yeah, name], storage place for Food items, allows you to have a buffer for cooked foods like steak or etc, could technically even be Included inside a restaurant schematic! This building could possibly have the benefit of being directly usable by the cook/restaurant worker instead of DMen. allowing a proper buffer, possibly even keeping raw meats and a small amount of coal to act as a very good buffer. 

One system that would definitely need implementing for this sort of thing would be a Priority of storage (for specific items even), so that you can have the Silo have a higher priority than the Warehouse (as you'd obviously want). 

Another thing that would be helpful if this sort of thing were added (So as to not overload the DMen) , would be specific "couriers", their only job is conveying resources between storage buildings, making sure that items are kept stocked and priorities are obeyed. 

Please, Discuss! These are just suggestions and ideas at this point. refining these ideas is important!

**Comment by marchermans** [comment]
@lunadragnstar Can you see if you can make some buildingschematics in this direction?

**Comment by Asherslab** [comment]
Maybe just in one style, or just some general ideas. silo should be and easy start. and they're all pretty small =D

**Comment by Nightenom** [comment]
to 2-4: I would do it like first three levels would be generic but much smaller warehouses, when you would like to upgrade to 4 and 5th level you would be forced to specialise the building for only one kind of items (eg. food, blocks, weapons and armor) but the storage will grow a lot
it would allow easy buffering of small colonies and easy upgrade to bigger district specialized colony

**Comment by Asherslab** [comment]
that would be interesting. however i think having seperate buildings would allow for nicer usage.
however, i think the Shed (2) would nicely fit what you're wanting for lower level colonies, it's a smaller warehouse with a buffer. it doesn't specifically have to have any filters on it (and as such could be used as just a simple small warehouse)

**Comment by lunadragnstar** [comment]
Ok, just thinking about the way I typically play, the silo would be good but it should be able to store any  food from the farmer.

The tool shed, I don't really see this as needed because the blacksmith makes tools on demand, unless we are going to allow him to make random tools on his own, then at least I know I don't usually have a high collection of tools

The Larder, no idea what that means but I think a "pantry" type of storage for cooked food would be good, since the cook is suppose to just cook and not do it on demand. 

The shed, I really see useful, specifically for logs for the sawmill, stone for the stone mason and stonesmeltery, those are what seems to clog up my warehouse,

This all would be on you guys to make this so that only certain things go in certain "buildings" but if you make all of these wouldn't that kind of make the warehouse unnecessary except for all the misc. stuff. Unless like I said, if we could get the crafters to make extra stuff, rather than on demand only.

**Comment by lunadragnstar** [comment]
![image](https://user-images.githubusercontent.com/29446488/63230830-42db1580-c1e0-11e9-8d7b-7ce508601bb5.png)
Very generic silo

**Comment by lunadragnstar** [comment]
Generic shed/tool shed
![image](https://user-images.githubusercontent.com/29446488/63230937-5d15f300-c1e2-11e9-9473-29d2e4980633.png)

**Comment by lunadragnstar** [comment]
I would like to make a suggestion though. If we do this, then I would like to have the respective workers be able to access them, farmer to deposit surplus into the silo, baker and cook to remove, etc.. Just to help out the delivery men. Since we are getting so big, 5 delivery men is not enough to sustain a town.

**Comment by Talyda** [comment]
I love the idea of a silo/granary. Wheat gets used a lot by more than one building, so always need a lot of it. I agree with Luna on that, if we have a silo, then the herders etc should be able to access them as they need wheat too =)
I don't see anything wrong with calling a shed a shed either! Always gotta have a shed! Though I do think that you could combine shed and tool shed - cos mostly if you have a shed your tools are in there with everything else anyway!
I also like calling the larder a larder. To me at least, a larder is a place where prepared foods are stored, pantry is where raw goods are stored =)  Inside the restaurant schematic would be cool too! Like a walk in fridge type thing. But if it was a separate thing, that would open up to option of building "cellars" under a building to act as a larder (or pantry) too - and that would be a good idea!

**Comment by Asherslab** [comment]
with the buffer buildings (larder/pantry and tool shed) the building could could have an option to make requests to keep itself stocked, i think the thing with the tool shed that's useful, is putting it near a barracks where your soldiers/etc may be using up bows/swords/shields quite frequently (especially earlier in the game, when they've got stone swords at best)

The silo would be specifically for wheat, which is why it would have a huge storage bonus for such types of items (or possibly seeds).

The Larder would be what takes raw food as well, instead of the silo.


Specific workers being able to use a small storage building near them is kind of a difficult one to think of, placing restrictions on that and etc. but it's totally possible (especially if we'd want to do that sort of thing with the cook and the larder)

**Comment by lunadragnstar** [comment]
When we get to 1.14 we can use barrels instead of racks or chests for the silo, that would fit much better, and allowing any worker to access any of the storage buildings would be a help, because it's not like the farmer is going to go take a sword or something, but may need a hoe, so I'm good with all workers having all access.

**Comment by Asherslab** [comment]
the silo would use a custom block for storage, not an actual storage block. like the hay block or whatever. 
barrels wouldn't work well because that'd cause lag. if we *had* to use storage blocks it would have to be racks

**Comment by lunadragnstar** [comment]
Why would barrels cause lag, they are part of vanilla minecraft

**Comment by Asherslab** [comment]
because of the way the code works for getting items. The same reason that we made the racks and don't allow chests to be used in warehouses

**Comment by marchermans** [comment]
@Asherslab I have been looking into this, what if we turned the warehouse logic upside down first, before adding these, add a worker to the warehouse: A warehouse manager, which periodically scans the entire warehouse and indexes it.
I mean keeping track of a placement of a new inventory is easy, the blockplace event can be used.
We would just need to make an efficient way of keeping track where each building is instead of a loop over all buildings in a colony, something like a nice tree will do.

Additionally we could then very efficiently index the entire inventory of a warehouse, even allowing the placement of several custom inventories, and have the inventories only be indexed depending on the building and worker level working there (bigger inventories -> higher level).

Now that logic can be reused across all of these buildings, adding a Farmboy to work in silos, a dishwasher for the pantry, and so forth. It would make our colonies feel more alive and allow us to add sorting for example.

**Comment by lunadragnstar** [comment]
I like that idea

**Comment by Asherslab** [comment]
as  a note @OrionDevelopment sorting already exists =D 
otherwise, sounds like an interesting idea, not entirely sure how we'd go about it though

**Comment by OCDCleric** [comment]
Silos store one type of item in vast quantities. So maybe a new storage block to hold vast quantities of 1 item exclusive to such storage facilities? In addition each level up would add an additional silo to hold same or different item?

So difficult finding a picture of a silo that isnt aluminum or concrete...

**Comment by GanthorPrime** [comment]
Hi. is very nice to see you planning expansion on the storage and delivery part of the mod.  As a player i just want to tell you that the combination of warehouse / sort function / and the postbox has become a very usefull thing this mods adds. PostBox lets you verify if you have an item, and if you are in a hurry, the sorted storage helps in finding it manualy.  This become very helpfull not only in accomplish the mods objectives, but with the game in general, specialy in late game and with other mods.

With that say, im very happy to read something about the concept of a buffer:  a way to say that for some item/s, we need to keep a stock. Im pretty sure this key functionality will improve the rol of the crafters and the supply chain in general.  

Speaking for my self, im always requesting the crafting of items i know will be needed soon: for this i need to empty the warehouse of those items, and use the postbox to request them so crafters start to work before the items are actualy needed in the request system because a builder or another worker. 

Generalizing this scenary of use it becomes as: sometimes, we, as the managers, foresee we need to keep a storage of a certain item (specified by us), independently if this item is for the use of a builder, a worker, or maybe for ourselves.

If the plan is that the type of items to keep stock will be tied to the type of structure (hut) you put. maybe its a good idea to include one for general use that allow us to specify the items to keep stock, like the postbox, or tu put this fucntionality in the warehouse itself.

**Comment by Asherslab** [comment]
@GanthorPrime to the very last part, the "shed" would be a catchall (everything), and then have seperate huts that are specific but with benefits of larger storage for those items

**Comment by Moobien** [comment]
A further suggested building would be a depository of sorts, one where you can pipe items into it that colonists need and the piping doesnt get broken with each upgrade

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
