### ISSUE TITLE
[1.14.4] Builder repeatedly asks for same materials

### ISSUE THREAD

**Issue by KayoKake** [ldtteam/minecolonies#3861]
### Version
Version: 0.10.358-ALPHA

### Expected behavior
- I give the builder the materials he requests and then he continues building

### Actual behaviour
- I fulfill his request and give his the materials (ex. 2 oak wood slabs), but then he proceeds to ask again requiring double materials. On one occasion, specifically 2 cobblestone for the mineshaft, I had to fulfill his request for 2 cobblestone 11 times.

### Steps to reproduce the problem
1. Wait for builder to go in front of builder's box to wait for the materials.
2. Click fulfill with the materials in your inventory.
3. The UI flashes and the fulfill button reappears, requiring more materials until he continues.

**Comment by Asherslab** [comment]
do you have the items needed for "fulfill" in your inventory?

**Comment by KayoKake** [comment]
Yes, and I watched the amount of cobblestone in my inventory go down each time I clicked that.

**Comment by Asherslab** [comment]
okay, and did the items appear in his inventory, or get placed down?
if not, was there space in his inventory?

**Comment by KayoKake** [comment]
I'm not entirely certain but I believe they went into the builder box inventory, not theirs. There was indeed space in his inventory.

**Comment by KayoKake** [comment]
Nevermind, I was wrong, it goes to his inventory.
(Sorry about that. Hope I didn't waste too much of your time.)

**Comment by GanthorPrime** [comment]
By the steps given, i understand he is fullfiling the request in the worker GUI for requested items, and not in the building hut (the needed items full list).  If this is the case, i want to confirm that i also observed this behaviour from many versions ago. (im in the 1.12.2 branch).  

To add, if you press the fullfill button, the worker gui flashes and the request for that same item shows agains.  If you continue pressing the button, you keep giving items to him, the item goes to his inventory so he ends with many times the amount he realy needs (i verified this for my case).  Its like if the check for the fullfilment in the worker own inventory ocurrs with less frecuency than the check for the request fullfilment in the hut inventory.  I say this because for some reason, if you fullfil the request using the hut GUI, the request dissapears from the worker gui instantly.

**Comment by KayoKake** [comment]
^Haven't tried the very last sentence up there, but the rest sounds very accurate to what I've got going on here.

**Comment by Talyda** [comment]
If you guys try pressing cancel, (in the builder's requests), after you fulfil it once, does the request go away and the builder go back to work?

**Comment by KayoKake** [comment]
If I let it sit there for a while the request goes away, although not immediately (maybe around 5-10 secs waiting).

**Comment by KayoKake** [comment]
Now that I'm building more and getting more experienced with this mod, I recognize now that it's not entirely consistent - sometimes it doesn't happen at all, sometimes it only requires a few secs of waiting for it to start working right, although on occasion I have to take it out of their inventory and keep redoing it to get anywhere. It's seems to be a flip of a coin on when it'll happen.

**Comment by bicobus** [comment]
This is the behavior I've observed during my play:

 * Fulfilling his request while there are items in the warehouse isn't recognized, as if being ignored. Canceling right after forces the builder to reevaluate and the request doesn't get remade.
 * If the items needed are not present in the warehouse, the request is fulfilled properly on the first try.

**Comment by Raycoms** [comment]
Yeah, we're working on those things atm.

Am Fr., 20. Sept. 2019 um 13:27 Uhr schrieb Bicobus <
notifications@github.com>:

**Comment by Raycoms** [comment]
fixed
