### ISSUE TITLE
Place a town hall, then can't place builders hut!

### ISSUE THREAD

**Issue by lordmadkid** [ldtteam/minecolonies#3916]
**Minecolonies version**: minecolonies-1.12.2-0.10.348-RELEASE-universal.jar
**Minecraft version**: 1.12.2
**Forge version**: 1.12.2-forge1.12.2-14.23.5.2838

**Expected behavior**

when I've placed my town hall, I place my builders hut then the builder start to build my town hall.

**Actual behaviour**

1 - Place my town hall: Check! 
2 - Right click on town hall's book but nothing is happening: doesn't matter, go to the next step!
3 - **Then try to place my builders hut: "you must place a town hall first." (or something like that).**
MY TOWN HALL IS ALREADY PLACE!!! What's the hell?

**Steps to reproduce the problem**

Just play normally? I don't know why it doesn't work and how it's possible.

**further information**

I've tried in 1.14.4 too (Minecraft, Forge and Minecolonies) and it's the same issue.

**Comment by Raycoms** [comment]
Uhm, when you placed the townhall did it create a colony?
Can you try the latest alpha too?

**Comment by mojoyup1528** [comment]
I have this happened to me every now and then. My fix was to enable the player commands to reset the colony, and delete it with true on building destruction, then start again. The commands system link is here: https://wiki.minecolonies.com/source/systems/commands

So, reset it first, let it regen the requests etc, then delete it completely and restart the town hall placement. You should still have your ship or starter area, that should not go away, but if so, just make another real quick with planks. 

Commands I used: 
1. /mc backup
2. /mc colonies list - see if the colony actually "exists" and has a name (could be the main issue
3. /mc colonies rsresetall
4. /mc colony delete colony: 1 candestroy: true - some blocks might be left over but they get overwritten when building or you can just get rid of them any other way. 
5. replace town hall
6. make building hut
7. place close to town hall - mine worked about 20 blocks away padding

Hope that helps

You can dynamically create colonies also because sometimes, due to depreciated values in config, the requirements for placement might be confined.

**Comment by someaddons** [comment]
what exactly did you do to "Place the townhall"?

**Comment by Raycoms** [comment]
I'll close this here with a comment. Don't place the townhall from the decoration menu, but with the buildtool and townhall in the hand from the townhall menu, which was likely causing the issue. Else, it might've been a desync from client to server which we fixed in recent versions.

**Comment by mojoyup1528** [comment]
@Raycoms I know this was JUST closed but real quick, does the placement of the town hall always lie in the lower right corner area of the colony? Maybe that is a confusion for some, where placement errors come up saying need to be closer etc. I found that through testing, the town hall is located in that corner rather than the center. 

This is testing boundaries with the LATEST release 3 days ago: 
https://ibb.co/Dt1kcVF

**Comment by Raycoms** [comment]
actually you place the townhall first and it is going to start an initital claim area. So it should be centered.
