### ISSUE TITLE
[feature request] Ability to start builds from townhall block.

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3941]
Sometimes when placing a structure you lose sight of where the block that will allow you to start the build is. Rather than having to chop down a forest or excavate a ton of blocks and other debris, why not have it so that the builds can be activated from the townhall block?

**Comment by fr3akb0y** [comment]
That would be awesome. Spent so much time into finding them xD. I also think they are accessible through town hall since it gets the information of all jobs so maybe not that hard to implement(of course there needs to be extra UI for that)? Also with that Idea maybe later on a map (which is i think also planned or at least in mind) like in Millenaire which then lets you select the buildings on the map.

**Comment by Raycoms** [comment]
We are planning on a map in the townhall which shows you the blocks on the map and allows you to do some actions on them.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
