### ISSUE TITLE
Builder can't finish upgrades, voided glass panes

### ISSUE THREAD

**Issue by slowiu06** [ldtteam/minecolonies#3981]
minecolonies-0.10.465-ALPHA-universal

My builder can't finish upgrading structures e.g. stone hut to lvl 2, dwarven library to lvl 2. He wants more glass panes one by one and voids them when beeing on building area.
![2019-10-25_16 57 58](https://user-images.githubusercontent.com/7887594/67581697-c2d5ac80-f748-11e9-92a6-5b500ef37810.png)
![2019-10-25_16 58 14](https://user-images.githubusercontent.com/7887594/67581696-c2d5ac80-f748-11e9-992c-4d3ef4a429c7.png)
![2019-10-25_16 58 01](https://user-images.githubusercontent.com/7887594/67581698-c2d5ac80-f748-11e9-96d8-95c2802c7205.png)

**Comment by Raycoms** [comment]
I'm pretty sure that's because of 1.12/1.14 schematics.

**Comment by Raycoms** [comment]
We're in the progress of fixing those.

**Comment by ferds814** [comment]
Same thing has been happening since 

minecolonies-0.10.415-ALPHA-universal

Requests window panes for every build. even when not needed. and just runs around complaining.

I am not building anything fancy either, just the dwarven schematics. but i can confirm its for all schematics. if the schematic has glass panes in it, your builder will get bugged completly.

"I'm pretty sure that's because of 1.12/1.14 schematics." possibly a cause

![2019-10-27_12 12 11](https://user-images.githubusercontent.com/9455836/67637661-211e9e80-f8b3-11e9-8a12-022bb9ab50b5.png)
![2019-10-27_12 12 25](https://user-images.githubusercontent.com/9455836/67637662-211e9e80-f8b3-11e9-830b-74d4b072bc2d.png)
![2019-10-27_12 13 47](https://user-images.githubusercontent.com/9455836/67637676-49a69880-f8b3-11e9-9c3b-c14b7bf6760e.png)

**Comment by slowiu06** [comment]
minecolonies-0.10.515-ALPHA-universal
Now Builder voids White Banners when I'm trying to upgrade Nordic style Deliverymen's Hut to lvl 5.

**Comment by Raycoms** [comment]
yes, all part of the schematics
