### ISSUE TITLE
[1.14.4] Item unknown builder

### ISSUE THREAD

**Issue by tiphilou17** [ldtteam/minecolonies#4164]
### Minecolonies
 minecolonies-0.10.600-ALPHA-universal.jar and Minecolonies minecolonies-0.10.602-ALPHA-universal.jar

Version:  FORGE 1.14.4 1.14.4 - 28.1.107

### Expected behavior

i want to build builder's hut but no npc action...message starting build

### Actual behaviour
npc want a unknow item...gold or wood, i give shovel axe and pickaxe wood and gold....no action...

- 

https://zupimages.net/up/19/51/ckwa.png
https://i.goopics.net/9jXrV.png

**Comment by EnterTheNameHere** [comment]
I got the same issue.

I coudn't get builder to start working; Got that issue both in my few days old survival and newly created creative on a clean installation.

Steps to reproduce:
- Download, install and run GDLauncher (I use it as mod manager, it's really comfy);
- Create new instance - I use forge / 1.14.4 / 2.8.107;
- After downloading right click on the new instance and choose Manage;
- Select Mods Manager in left menu;
- On right up you can see "+" icon, click on it;
- You can see "Search a mod" which is text box, so enter "minecolo" and press Enter, which should find two mods, one we want is "Minecolonies", the other we don't want is "Better With Minecolonies [Forge]";
- Hover over the mod icon, "Install" should appear, so click it... Latest version of structurize is downloaded automatically too;
- Now you can exit the Manage by pressing X on right up, which should bring you back to instance selection and you can run it by pressing twice...
- Forge preloads, loads, you can check mods, my mods:
Minecraft 1.14.4
Structurize 0.10.201-ALPHA
Forge 28.1.107
Minecolonies 0.10.602-ALPHA
- Create new world (I did creative, cheats on), wait till it's loaded;
- Cheat yourself ship/camp and place it inworld
- Get building tool and town hall from chest, place it inworld
- Cheat yourself builder hut and place it inworld
- Wait for villager spawning
- Go to builder hut and assign villager as builder
- Choose build options and create build request
- Give all the required material through the builder hut GUI
- Cheat yourself wooden (or iron or golden) pickaxe, axe and shovel
- Give it to the villager
- Cancel and resume build request if necessary
- Villager has red icon over his head and reports she needs "Tool of class:Uknown with minimal level:Wood or Gold and with maximal level:Wood or Gold" tool as tiphilou17 shown in screenshot.
- I can press Fulfill but villager will again after some ticks returns to red icon over head state...

I checked that builder should require pickaxe, shovel and axe in the source code, so that requirement should be fulfilled, but I couldn't guess from where the Unknown comes from...
Probably not related, but in log there is 

> WorkOrderBuild at location BlockPos{x=1797, y=64, z=1078} is using schematics/medievalspruce/builder1 instead of schematics/medievalspruce/builder1

I attach all the logs... (the -1 suffix files is just a run of client to check mod versions)
Note: The client won't close itself, I have to kill it, but I don't know where is issue with that. World however is saved alright without any issue.

[2019-12-21-1.log](https://github.com/ldtteam/minecolonies/files/3990915/2019-12-21-1.log)
[2019-12-21-2.log](https://github.com/ldtteam/minecolonies/files/3990916/2019-12-21-2.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/3990917/debug.log)
[debug-1.log](https://github.com/ldtteam/minecolonies/files/3990918/debug-1.log)
[debug-2.log](https://github.com/ldtteam/minecolonies/files/3990919/debug-2.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/3990920/latest.log)

**Comment by tiphilou17** [comment]
I can not move back to reposition a building, when I escape and I click again with the building tool it gives me a decoration but no repositioning with hindsight

**Comment by Asherslab** [comment]
Already known and being worked on

**Comment by Raycoms** [comment]
Should be fixed
