### ISSUE TITLE
Library lowering citizen stats ramdomly since 593

### ISSUE THREAD

**Issue by LordILarrion** [ldtteam/minecolonies#4220]
### Minecolonies version

Version: minecolonies-0.10.614-ALPHA-universal

### Expected behavior

- 
Prior to 593 you could put citizens in the library and supply them with paper and they would continually increase random stats slowly until they were all at 10 (if you waited long enough)

### Actual behaviour

- 
You look at their stats to see what they are, one time you will go check on them and their stats will have raised, go back half an hour later, and stats that were raised will be lowered. I have seen stats make it up to 8 or 9 get reset down to 4 or 5.

### Steps to reproduce the problem

1. Assign citizens to library
2. Give them tons of paper
3. Go check on their progress every half hour or so, the stats go both up and down, and the downs are usually drastic.

**Comment by masternetra** [comment]
Yea apparently the library doesn't like traits at level 10, I haven't had a issue with trait drops unless I sent in a citizen that spawned in with a lvl 10 trait and the problem is just with that trait but once it drops to at least 9, firing and then rehiring stops the decline. It does this in stable too (592).
