### ISSUE TITLE
[Suggestion] need more dynamic building materials

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#425]
### Minecolonies version

1.11 beta 8 (probably others too)

I've noticed that when you request buildings to be built that the builder is rather emphatic on the type of materials he wants.

This works fine if your colony is founded in a plains biome where almost all of the different tree types are available, but if for some reason you start your colony in a snow biome with only spruce, you will be traveling hundreds of blocks just to get an oak tree.

Suggest updating the mod to allow wood to be any available wood type.

perhaps have a button available that if clicked tells the builder to not be so darn picky and loosely accept compatible materials for the various parts. Like cobble, andesite, diorite, would all be compatible, and all the woods for wood and all the logs for log, etc. You get the idea.

Or craft an item that if in his inventory makes him lazy about the materials.

**Comment by Raycoms** [comment]
The idea was to "motivate" the player to travel around to get certain types of wood.
But, we will as soon as we have the time and manpower add additional types of styles for each hut, allowing the player to choose the one which most matches his biome.
In higher upgrades, for sure, more diverse materials are always needed, since they add awesome benefits to the colony.

**Comment by kreezxil** [comment]
I personally don't feel motivated, when after traveling about 300 blocks on my world seed, I come to ocean and still no oak, just spruce everywhere! I know 300 blocks isn't much technically.
