### ISSUE TITLE
Fancy Square Barbacan

### ISSUE THREAD

**Issue by chriskeena** [ldtteam/minecolonies#4309]
### Minecolonies version

Version: 0.10.680-RELEASE
MC Ver: 1.14.4

### Expected behavior

- I would expect the Builder, after excavating, to be able to place gravel without need of grassy dirt blocks.

### Actual behaviour

- Builder has excavated pit for construction and upon attempting to place gravel realises it would be suspended over the pit. I can only assume items like torches are meant to be placed in the hole but they aren't placed until much later in the build.

### Steps to reproduce the problem

1. Queue Fancy Square Barbican schematic
2. Watch builder dig a pit for foundations.
3. Watch builder fail at placing gravel.
4. ... Profit

**Comment by Raycoms** [comment]
if a gravel block in a build would be placed above an outside air block, it has to place some kind of block under it to make sure it doesn't fall down, leave a hole, and leave the entire schematic incorrect.
Thus, if he detects it, he is smart, takes the most common block of the biome and places it under it.
This is on purpose and was often requested by our community.

**Comment by chriskeena** [comment]
The issue is that this is occuring with a blueprint included in the mod and the void under the gravel was created by the builder themselves.

**Comment by Raycoms** [comment]
@lunadragnstar can you confirm?

**Comment by lunadragnstar** [comment]
This is due to the fact that it is a redstone torch that is placed below that block, and redstone torches are the one of the last items placed, so it places a grass block during the initial build. At the end, it is replaced.

**Comment by Raycoms** [comment]
okay, that should be fine then. The only way to make this work is by doing that.

**Comment by chriskeena** [comment]
Can we not have Schematics that rely on dirt placeholders during construction.
Ask submitters to replace floating gravel and sand with solid blocks.

**Comment by lunadragnstar** [comment]
There are only a few builders, however as the schematics admin I am overall responsible for all of them. I only mention this because there are over 3000 schematics  and there is no way I have time to go through each and every schematic to make sure there aren't "floating" gravel/sand blocks that might need dirt placed under them. Dirt is the easiest block to obtain, and this schematic places 2 extra as placeholders.  I don't mean to sound rude or anything, but we do this for free, in our free time. It is not worth me spending days and weeks checking each schematic for a couple of errant placeholder blocks. Besides, during the schematic building process we have 2 generic placeholder blocks that we use, (you can see them in structurize tab in creative, they are the light placeholder blocks, which tell the builder to leave whatever is there alone, and the solid (dark) placeholder, which tells the builder to replace any block that is in that location with the biomes default block, which is usually dirt. So, this isn't a feasible request. Sorry.

**Comment by chriskeena** [comment]
I'm not asking you to personaly check all the schematics. It might not be an impossible task but I'm sure it would be mind crushing.
A note in the submissions guide should be sufficient.
