### ISSUE TITLE
SUGGESTION: Better instructions on MC commands

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#432]
Been playing about with the commands, trying to get to grips with what you can do and I have to say it takes a little guesswork as the messages that come up don't really tell you what format to put the commands in.

These two are fine and quite obvious as they only have the "list" sub command
`/mc colonies <list>`
`/mc citizens <list>`

Gets a bit more complicated with this one though 
`/mc colony <kill|respawn|info|delete|addOfficer|citizenInfo>`

So far as I've worked out, the syntax is-
`/mc colony <sub command> <colonyID> <variables>`

In order to use this you then need to run the following to get the colony IDs-
`/mc colonies list`

To get info on the first colony you can then use -
`/mc colony info 1`

To add yourself as an officer on the first colony (assuming you're an op?)-
`/mc colony addOfficer 1`

To add another player as officer on the first colony
`/mc colony addOfficer 1 <playername>`

etc...

**Comment by pmardle** [comment]
Glad you bought this up, I have been thinking of doing a video on the text commands we have in the game :)

**Comment by nekatu** [comment]
Thanks! 

Your videos are awesome. :-)

**Comment by xavierh** [comment]
Small correction, to get the list of citizens we need the colony id
`/mc citizens list <colonyId>`

**Comment by Raycoms** [comment]
@pmardle could you make a video about them?

**Comment by xavierh** [comment]
Wiki as well? I would hate to have to play a video just for that. Maybe it
is a generation  thingy ;)

**Comment by Raycoms** [comment]
Yeah Wiki and Video.

2017-03-05 12:32 GMT-03:00 xavierh <notifications@github.com>:

> Wiki as well? I would hate to have to play a video just for that. Maybe it
> is a generation thingy ;)
>

**Comment by Wissi** [comment]
Yeah, that has been talked a lot with Kostronor and Raycoms and they had me "hold off" on it since it may cause more confusion and questions than help. Since it's basically more of a "server side" management than player related commands (Since player needs to be /op in game)

Yes.... I know for SSP it works as well, but honestly if you're playing SSP, you probably don't really need them. 
I can create another WIKI page (as we have discussed in the past for "Server Management"). But there seems to be NO documented list of commands I can access to list on the WIKI other than the ingame /help (which is what this thread started out to be).

Is there more server side management info you guys can give me or want me to include in the WIKI as well?

**Comment by Wissi** [comment]
@Raycoms @Kostronor Can you guys close this issue now? I can't seem to close it, no option. 
Wiki page added with all available commands.

**Comment by Raycoms** [comment]
Good job on that. =)
