### ISSUE TITLE
Racks in schematics

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4423]
In every version of minecolonies for 1.15.2 I've noticed that the racks aren't connecting properly, sometimes they aren't visable, sometimes when there are items in the racks, the graphic that displays showing items in the rack isn't there, and the racks appear graphically empty.

**Comment by pixar02** [comment]
(Only when placed by the builder, can't reproduce as player)
- Or even the texture glitches, 2 racks next to each other and one won't show, one of the two has a shadow.

- 3 racks next to each other, the third rack placed doesn't connect (might be intentional).

- Sorting the warehouse creates "visually" empty/full racks. Some become empty but show like they have items. and the otherway arround too (this is fixed when the player forces a item in and out).

**Comment by Raycoms** [comment]
I have adapted some things in one of the last 4 versions. Have you tested it lately?

**Comment by lunadragnstar** [comment]
I'm running test using the latest version now, i will check this as well.

**Comment by pixar02** [comment]
- A double rack still has the issue, if you put an item past the middle so row 4,5 or 6 and leave the rest open it's doesn't update the racks to show that it contains items. (code compiled version)

- Forcing a rotation of a rack (builder places 2 racks, 1 "facing north" and 1 "facing west"), still glitches the combined rack block (only one of them glitches), it's like it doesn't know what his rotation should be.

- Sorting bug, after sorting the warehouse, some racks (2 racks next to each other) show that they contain items but are empty. When opening the blockrackair, it updates to empty, if you reopen the rack but with the rack (not the air one) is becomes full even if the variant is blockrackempty. (this variant changes on opening the rack) 

But the shadow bug, invisible rack,... are indeed gone (at least for me).

**Comment by lunadragnstar** [comment]
I haven't tested everything but so far no invisible racks
