### ISSUE TITLE
Substitution Blocks

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#445]
Just a thought.  Can we easily in the code flip the two substitution blocks.  So the old one is the "solid" block and the new one is the non solid one.

If we don't I have to replace the substitution blocks on ALL existing buildings and re-scan.. :(

**Comment by Raycoms** [comment]
I think their styles wouldn't combine if swapped.
and I'd say no need to rescan for now, it works well as it is. If we have to rescan one building (because of orange wool or citizens going up roofs we will use the solid one. And for new ones as well.
That way we automatically replace all of them over the time =)
