### ISSUE TITLE
Pathing into oil

### ISSUE THREAD

**Issue by April25th-mc** [ldtteam/minecolonies#4504]
### Minecolonies version
This is on the Patreon 1.15 server.
Minecolonies: 
minecolonies-0.11.787-ALPHA-universal.jar

Before an update about a week ago, my deliveryman used to walk this way all the time without problems. But now when he needs to walk in this direction, he just walks right into an oil pit, bounces a few times, then sits there. I believe the oil pits are created by Industrial Foregoing? Unsure if he'd have the same problem in water.

He's very enthusiastic about diving into the oil... lol

![2020-03-24_23 23 58](https://user-images.githubusercontent.com/58610784/77499119-9c1abf80-6e27-11ea-8d56-384bcea93766.png)
![2020-03-24_23 24 36](https://user-images.githubusercontent.com/58610784/77499121-9de48300-6e27-11ea-953a-bc8ada10976e.png)

**Comment by SirSmuggler** [comment]
The pathing update does seem to bring more problems than it solves. Before the update my delivery men had no problems using bridges I had built over a river and up to parts of my colony that is in the mountains. After the update, they ignore the bridges and try to climb the mountain instead. They very often get stuck in a loop climbing and falling of the same route over and over again. It's not just delivery.-people ofcource, but due to them allways running around, it is most notisable for them.

**Comment by marchermans** [comment]
@SirSmuggler That might indeed be possible.
The new system does not look extremely far if the bridge is for example more then 10 blocks away from the direct path, it does not even consider it, especially if the water is very short. Since that is the directer cheaper route. You can help it make better decisions by placing a good amount of way points since it then will start looking for the shortest route between them. But if your bridges are two far apart or if there are too few. They will swim across.

**Comment by PasixTheValkyrie** [comment]
Going to add to this. Since the pathing update the citizens become wicked parcour-enthusiasts, but they're absolute amateurs. I have to do a lot of specific fencing to force them to stop trying to drown themselves now. :(

**Comment by SirSmuggler** [comment]
A few waypoints placed along my bridges seems to solve the worst issues for me.
Is there any drawback to spaming waypoints along all intended paths to prevent "parcour enthusiasts" from runing amock? Will it impact performance or something?

**Comment by Raycoms** [comment]
Yes, it makes the performance better
=D
