### ISSUE TITLE
[1.12.2] Yellow Banner not being accepted Medieval Town Hall Lvl1 to Lvl2 upgrade

### ISSUE THREAD

**Issue by MacAttack-UK** [ldtteam/minecolonies#4771]
![Yellow-Banner](https://user-images.githubusercontent.com/13574886/80307821-6882da80-87c3-11ea-95fe-fd29c346ea8d.png)
Custom Pack fo MC 1.12.2

Forge Version : forge-1.12.2-14.23.5.2854

Minecolonies Version : minecolonies-1.12.2-0.11.804-RELEASE-universal
Also tried latest Alpha : minecolonies-1.12.2-0.11.841-ALPHA-universal

Builder Asks for Yellow Banner to continue but won't accept plain Yellow Banner. The Picture in the part list looks like a Yellow banner with a pattern, which I have made exactly as shown but that doesn't work either.

Thanks in advance and for such an awesome mod :)

Edit : I moved the builder forward by setting the config to not need resources and restarting the server to move it forward past the banner which turned out to be called a 'Yellow Banner' but is actually Orange by the looks of it.

**Comment by Raycoms** [comment]
I checked into this, you need the exact banner. I don't see any good way to solve this in 1.12 besides changing the schematic to only have base color banners.

This makes this a schematic issue then.

**Comment by TTrebron** [comment]
Posting here because this issue comes up quite high in the search results.

Here's the command that gives you the banner the builder is looking for:
```
/give @p yellow_banner 1 0 {BlockEntityTag:{Patterns:[{Pattern:vhr,Color:14},{Pattern:vh,Color:1},{Pattern:tr,Color:1},{Pattern:tl,Color:14}]}}
```
I found the exact banner block by opening the blueprint file minecolonies-1.12.2-0.11.841-BETA-universal.jar\assets\minecolonies\schematics\Medieval Oak\Cook3.blueprint in an NBT viewer. It was one of the nodes under tile_entities.

The builder accepted this banner for the Level 3 Restaurant, but it should be the same for the Level 2 Town Hall.

**Comment by gwentales-bit** [comment]
the exact command is /give @p banner 1 11 {BlockEntityTag:{Patterns:[{Pattern:vhr,Color:14},{Pattern:vh,Color:1},{Pattern:tr,Color:1},{Pattern:tl,Color:14}]}}
