### ISSUE TITLE
Gmae Crashing After Placing Supply Camp

### ISSUE THREAD

**Issue by NoopSloop** [ldtteam/minecolonies#4898]
### Minecolonies version

Version: 0.10.771-RELEASE

### Expected behavior

- 
Supply camp being placed
### Actual behaviour

- 
I have tried to place the supply camp on multiple occasions (and the supply ship) and my game crashes every time. I am new to Java Minecraft, so there is a very high chance that this is an issue on my end. Have a great day!

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog: https://gist.github.com/NoopSloop/2a95c4a09ffe26696010810b2f7264ed

**Comment by Raycoms** [comment]
Please update both minecolonies and structurize to the latest alpha

**Comment by GitSugar** [comment]
### Version:

- minecolonies-0.11.938-BETA-universal

### Expected Behaviour:

- Placing a supply camp

### Actual behaviour

- CTD

### Steps to reproduce:

- Step 1: Craft the camp
- Step 2: Place it and make sure it has the floor requirements
- Step 3: Game freezes and CTDs


I installed minecolonies literally a month later but I'm experiencing the same issue.
I downloaded the latest minecolonies version for 1.15.2 as well as structurize.

Any Ideas of what's going on?

**Comment by Raycoms** [comment]
alpha? latest alpha
