### ISSUE TITLE
Deliveryperson instead of deliveryman, fisherperson instead of fisherman

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#4939]
I have two female deliverymen who think the name should be changed to deliveryperson (or deliverer) instead and a female fisherman who wants to be called a fisherperson (or possibly a fisher). Do you agree? Should we change these?

**Comment by marchermans** [comment]
This is not an issue but something that should be discussed on our discord:
https://discord.gg/w6FysPA

Feel free to join and discuss this there.
That said this is not something we do from our side directly i would say. The name deliverymen and fishermen has grown historically due to the nearly 10 year history of the mod at this point, and nobody has expressed any issues with the naming before. Additionally if you feel offended then you are free to create a resourcepack that overrides the language files and add support for it that way.

On the other hand if the community wants it changed, then we will of course change it.
