### ISSUE TITLE
Wiki is broken or hacked

### ISSUE THREAD

**Issue by Lincoln1234543** [ldtteam/minecolonies#5255]
It tried to steal some of my fuckin passwords or something else

**Comment by ToMe25** [comment]
Please describe your issue in more detail, to help us find the issue if one exists.
Also which wiki url did you access?
https://wiki.minecolonies.ldtteam.com/ or https://ldtteam.github.io/MinecoloniesWiki/ ?
For me both of them seem normal.

**Comment by ToMe25** [comment]
Do you mean the warning you might, depending on your browser, get when clicking on the wiki link in the header?
If yes, that is just because the wiki got moved, but still links to the old location, this shouldn't cause too much problems, or security risks tho.
Also that should hopefully be fixed soon :)

**Comment by Lincoln1234543** [comment]
wut

**Comment by Raycoms** [comment]
Please don't dig out old closed issues. This was because the certificate had timed out.
