### ISSUE TITLE
1.15.2 M?anie K. Haddock Render Crash

### ISSUE THREAD

**Issue by McKitten** [ldtteam/minecolonies#5369]
Versions: 
Forge 31.2.30
minecolonies-1.15.2-0.13.21.1-ALPHA-universal.jar
structurize-0.13.4-ALPHA.jar

### Expected behavior
No Crashy. Tho glad it was only local.

### Steps to reproduce the problem

1. Raiders @ friendly player's colony
2. Teleport in to assist.
3. Crash.
4. Give fun reading to Raycoms inc.

debug.log (last minute or so) : https://gist.github.com/McKitten/a42966a5c51c559dbc90413e8869e568

**Comment by Raycoms** [comment]
This is the classic forge issue we've been complaining about for months: java.lang.NoClassDefFoundError: com/minecolonies/coremod/client/render/MRenderTypes

Forge didn't load this class accordingly on startup causing the crash for you.

Unfortunately there is nothing we can do until they solve this on the forge side. These crashes occur with all kind of other mods too. (Just not as much because they don't have as many classes to load).

**Comment by McKitten** [comment]
Would -XX:+AlwaysPreTouch assist in prevention?

**Comment by Raycoms** [comment]
I don't know to be fair. You'd have to ask forge about that.
