### ISSUE TITLE
builder not finshing builds

### ISSUE THREAD

**Issue by DimsionWalker** [ldtteam/minecolonies#5434]
Version: minecolonies-0.13.59-ALPHA-universal.jar
--

### Expected behaviour

to get the little build a complete message
- 
after fishing a build they should say complete and move on
### Actual behaviour

after finishing the build, mine, and farmer huts the builder refuses to say any other build is complete and just punches around the build when the desk thing in the hut says the build is complete (using nordic buildings)
- 

https://drive.google.com/file/d/1sKgaf3p0NSmPK7UVCTnSdyoCnWL4hEOb/view?usp=sharing

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
Does the desk say it's complete or does it say it's at 100%?

**Comment by DimsionWalker** [comment]
yay but no notice nor can't assign workers

**Comment by mgailp2** [comment]
I am having what looks like the same / similar issue. When a job is finished, the builder just stands and his hut says 100% rather than clearing that job and showing a new one. When I exit and come back, the builder has multiple jobs assigned in the town hall list. He will then occasionally do 1 new
![2020-07-21_18 14 33 Multi- Job Assigned top](https://user-images.githubusercontent.com/68662697/88219760-a6a76300-cc27-11ea-97e4-9bfeb981b113.png)
![2020-07-21_18 14 37 Multi- Job Assigned bottom](https://user-images.githubusercontent.com/68662697/88219764-a73ff980-cc27-11ea-9f14-7445ee19578d.png)
![2020-07-21_18 16 51 map with no jobs](https://user-images.githubusercontent.com/68662697/88219766-a7d89000-cc27-11ea-9083-7a370ccf71f0.png)


 job but is then stuck again.  Mine is a little different as exiting and returning will remove the construction tape.

I use what is in Twitch as "Minecolonies Official" and as updated as that allows. It says version 5.3_Final under the name.

Attached pictures are 2 of the town hall list with multiple jobs assigned to the same builder (top then scrolled down) and the third is the map with no brown boxes of construction tape.

**Comment by Raycoms** [comment]
It's because after reaching 100 percent the builder can need another 10 minutes to do the remaining scans

**Comment by DimsionWalker** [comment]
that seems overkill for a few scans but good to know that is what's happening and there should be a note stating the builder may take x time to scan builds after they are done.
P.S. Thank you for responding and telling me what was happening.

**Comment by Raycoms** [comment]
It's because it has to check if there are blcks to remove in the world, like water, etc. And it's a classical mathematical problem. It's difficult to estimate the additonal time.
