### ISSUE TITLE
Bug Report, 1.15.2

### ISSUE THREAD

**Issue by lyricalprimeboy** [ldtteam/minecolonies#5628]
The builder will not finish building the fortress townhall1. Idk if the same problem occurs with other types, as i have only tried the fortress one in creative. Its all built, just wont finish it. Also the villagers seem to get trapped on double fencegates

**Comment by ravenbuilder934** [comment]
Please fill out the entire template, it's there for a reason. The double fence gates bug was fixed recently, make sure you're on the latest alpha.

**Comment by Mekle001** [comment]
I'm going to close this out since it didn't use the full template and fill it out. 

I will also mention that for the fortress townhall, you need to be very patient, as some of the builder phases are checking the blocks, and he has 4 full chunks to check, assuming you lined it up with chunk boundaries. 

As Ravenbuilder934 said, please make sure you are using the most recent alpha, as it has the fix for the double gates, and does a better job of showing builder progress.
