### ISSUE TITLE
Asian Barracks Tower Placement Issue

### ISSUE THREAD

**Issue by CaptainAether** [ldtteam/minecolonies#5646]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.169-ALPHA-universal
- Structurize Version: structurize-0.13.42-ALPHA
- Related Mods and their Versions: Installed on Valhelsia Modpack version 2.2.7 with only Structurize and MineColonies changed manually. Confirmed old files deleted and only versions listed above installed.

## Expected behavior

Builder places Barracks Tower blocks for Asian Barracks facing the correct way

## Actual behavior

Tower blocks are placed 180 degrees the wrong way, even after breaking and clicking repair on barracks.

## Steps to reproduce the issue

1. Go to existing Level 1 Asian Barracks
2. Remove the only Barracks Tower block
3. Open the Barracks block and choose Build Options > Repair
4. Wait for builder to repair structure
5. Barracks Tower block is turned around 180 degrees but in the correct spot

### Logs

- latest.log: https://gist.github.com/CaptainAether/e7bc26c9898ab4c7cfd73f28c7b879ca
- crashlog: N/A - Crash does not occur

### Notes
Conversation about issue can be found in MineColonies discord server here: https://canary.discordapp.com/channels/139070364159311872/724810039281451028/747156544881426503

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This also happens for the dark oak barracks. *NOT* a schematic issue.

**Comment by Raycoms** [comment]
@ravenbuilder934 this was fixed in a recent version for all mirrored barracks. This should be a schematic issue now! #5006

**Comment by arrowflightmain** [comment]
I am having this problem currently in the dw 20 1.13.0 version. happened to 2 of my towers, broke them and now they say you have to upgrade barracks to build, even though i have a rank 5 barracks.

**Comment by Raycoms** [comment]
Do a repair on the barracks to respawn the towers

**Comment by thiper01** [comment]
I am having this problem on minecolonies-1.18.2-1.0.1397-BETA, the 3rd barracks tower is facing away from the door instead of facing it, making the barracks tower doorless and overlapping the barracks building, so no way to go in
![2023-05-27_21 45 00](https://github.com/ldtteam/minecolonies/assets/57779605/636c5da3-726e-4030-910c-97106178528d)
![2023-05-27_21 45 15](https://github.com/ldtteam/minecolonies/assets/57779605/b8c4d404-9c6d-45de-b346-2e2deabaf66a)
![2023-05-27_21 45 28](https://github.com/ldtteam/minecolonies/assets/57779605/31ca2bb6-84a9-46c5-9d11-19b27ce744e8)
![2023-05-27_21 45 37](https://github.com/ldtteam/minecolonies/assets/57779605/b40043a8-3802-4fae-9392-5e440580faa8)
