### ISSUE TITLE
Tavern Visitors falling through world

### ISSUE THREAD

**Issue by DangerDr** [ldtteam/minecolonies#5811]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: 0.13.268
- Structurize Version:0.13.64
- Related Mods and their Versions:

## Actual behavior

![image](https://user-images.githubusercontent.com/70381349/93806030-750b4200-fc40-11ea-9308-9f3e150cc809.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

issue has been ongoing through a few versions.

Update (22.09.2020): so it seems that even though the message appears it doesn't actually happen?
I got one 5 minutes ago saying Marion W. Chestor fell though the world but whilst I was wondering around my town at night i found her creeping like Ghost - she's not recruitable however 
![image](https://user-images.githubusercontent.com/70381349/93916758-e959ea00-fd01-11ea-8c82-3317d9ab0216.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by LucidDreamer0322** [comment]
I find that it happens any/every time the chunks get unloaded. The villagers all remain safely in their stasis, however the non-villagers fall out of the world. happens both when leaving the area via travelling outside of chunk loading range or via logging out of a server, getting the message of death upon reentry to the server.  Happens 100% of the time for me.  However, it can be used to recycle guests so you don't have to kill them yourself to get new ones 👍

**Comment by ravenbuilder934** [comment]
I've never gotten this, even when chunks get unloaded.

**Comment by DangerDr** [comment]
Its also cant be that cause i'm not leaving the village so the chunks aren't unloading.

I'm also getting a message that villagers are falling to their death INSIDE the tavern from the table to ground level

**Comment by LucidDreamer0322** [comment]
you and i seem to be having a similar issue with different triggers then, unless its something else entirely.

My server is set to range 10, as is my client.
i am running the latest 1.16 alpha on minecraft 1.16 with other mods, none of which would conflict with anything village related though, unless maybe waystones with world-gen, but i doubt it.

**Comment by JasonEpic** [comment]
I've also gotten this bug many times, I've seen it probably at least 3 times in my last play session, as well as before and after upgrading to newer versions of Minecolonies so it is a genuine bug. I've been playing on the latest 1.15.2 alpha version with other mods as well but I don't think conflicting mods would cause tavern visitors to spawn at 0, 0, 0, cuz I assume that's what's happening since by the time I get the death message its at around y= -180

**Comment by DangerDr** [comment]
So I think Lucid is right and that theirs two different triggers.

I just left my village for the first time and 3 of my visitors "died" 
![image](https://user-images.githubusercontent.com/70381349/94218598-b3bd2880-fedc-11ea-9de9-61d80d21a9cf.png) this is my first time getting that error on this save/world (singleplayer)

**Comment by LucidDreamer0322** [comment]
i've been thinking a bit about the numbers as well.... its always at x/z 0. i've never been to 0,0 in my world, so there would be no land there, is the mod teleporting visitors to 0,0 because unlike your villagers, visitors have no anchor (beds).  I think i will test and see if it still happens after i have my world generate at 0,0. also are they being teleported to -182 and insta-dying, or is that just how long it takes the dot effect to kill them from dropping them out of the sky lol

Update: Causing the world to generate the area of 0,0 does not fix this issue.

**Comment by LucidDreamer0322** [comment]
so it isn't spawning the visitors there, they are the ones who are currently in my city that get yeeted.

its not tp/dropping them there, i've had someone stand at 0,0 when i leave my city, nothing changed and they were never seen at location.

my deductions are that they are just falling through the world in your city (contrary to what the chat log says) and its a stasis/chat bug, or something is legit just sending them to 0, -182, 0.

What i find REALLY suspicious is when the chat says the villagers died, but then you later find them alive and well in your village still.  that happens very rarely, but when it does you can no longer interact with the visitor, any attempt to just plays the audio clip with no gui or any other response.  also this death bug happens every time i leave the area, i have yet to note a single exception.

**Comment by McArgent** [comment]
I'm seeing this happen with 1.16.3
minecolonies 0.13.312
structurize 0.13.90 (Alpha)

I can see it when I'm bopping around town.  It's possible I'm getting far enough away from the chunk that includes my tavern (always happens at the tavern).  My colony has gotten pretty huge, so entirely possibly I'm still in town, but far enough for chunk to unload.  It's been happening since my tavern was level 1; its now level 3.  
It's not happening at 0,0 (more like -92,-14,62).  It happens almost every time when I first login now.
