### ISSUE TITLE
placing blocks bugged since minecolonies-universal-1.11-0.6.2829 update

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#585]
### Minecolonies version

minecolonies-universal-1.11-0.6.2829

### Expected behavior
to able to place blocks on top of one another

### Actual behaviour

right clicking a block overwrites orignial block and shift right cliking doesnt allow it to be placed either

### Steps to reproduce the problem

1. install minecolonies-universal-1.11-0.6.2829
2. load into a world
3. tryplacing blocks
4. Profit

forge:1.11.2-2229

**Comment by ScytheIronclaw** [comment]
I also encountered this issue with the mod version: 1.11.2 soild

I encountered this issue with torches.

When I placed a torch on a block, it deletes the block and replaces it with the torch, also this bug affects placing oak planks. You cannot place oak planks at all.

I rolled the mod back to version: 1.11.2 Delivered v3, these issues do not occur with 1.11.2 Delivered v3

**Comment by kreezxil** [comment]
I have confirmed this in my mega pack. I went through everything and to my dismay it was Minecolonies. However, I'd like to point out that my players said this issue was happening far earlier and I wish they reported it then so we could've had a longer run on tracking this down.

Sadly there is no information in either the server or client console.

This issue exists in both SSP and SMP environments with only this mod loaded.

**Comment by marvin-bitterlich** [comment]
Seems like some wood types are now marked `replaceable` and I guess this could be with the construction tape changes @nojo121 

@Raycoms any other changes that could have caused this?

**Comment by Liguma** [comment]
![2017-02-13_09 47 18](https://cloud.githubusercontent.com/assets/24432099/22877074/01c552a6-f1d4-11e6-9fb0-f9c1e12d1b65.png)
![2017-02-13_09 47 39](https://cloud.githubusercontent.com/assets/24432099/22877075/01f29a4a-f1d4-11e6-84b4-e984201c8391.png)
![2017-02-13_09 47 49](https://cloud.githubusercontent.com/assets/24432099/22877076/01f2fed6-f1d4-11e6-8382-0dc2a2ea3f0e.png)

Here are some pics - before, cutting, placing
