### ISSUE TITLE
Can't interact with colonies im added in

### ISSUE THREAD

**Issue by kryldost** [ldtteam/minecolonies#5930]
We tried a lot of things. I am officer on colony A, I receive achievement completion, I have messages ingame saying the builders my friend ordered around are doing things. But when I click the townhall, Nada. I am prompted to create a new colony although there's an existing one right there. We verified if the permissions are all good, yes. I'm officer.

Then we tried in Colony B! Unfortunately same problem there.

So I thought.. maybe its my account? I logged in my alternative account and tested in both colonies. I am Unable to perform anything as an officer, in fact it also asks me if I'd like to create a colony.

We tried with OP on, doesnt work. The owner of the server was added as an officer in Colony A and she was able to interact with the colony. 

So I am out of alternatives! Why am I not able to interact with colonies?

next time I tried was making my own colony! I tried placing a supply camp? Nada. Tried placing a supply ship? Didnt work either. I tried with all the requirement right, just wont work. I don't understand whats going on...

**Comment by ravenbuilder934** [comment]
Please fill out the entire template, we need important things like your versions.

**Comment by kryldost** [comment]
What is the template, sorry I didnt see I needed one

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues/new/choose and choose Bug Report, then fill it out

**Comment by kryldost** [comment]
I'm guessing the minecraft versions, the server is running 1.15.2

**Comment by ravenbuilder934** [comment]
I meant the version of the mod, like 347 beta

**Comment by kryldost** [comment]
minecolonies-0.13.313-BETA-universal.jar

**Comment by ravenbuilder934** [comment]
Updating might fix it

**Comment by kryldost** [comment]
Its part of a modpack, its not something that's in our control unfortunately.

**Comment by ravenbuilder934** [comment]
If it's your own server, you should be able to update it individually without breaking anything

**Comment by kryldost** [comment]
Is this the first time something like this happened?

**Comment by kryldost** [comment]
Hmm, I'll convey this to the owner of the server then see if it can help?

**Comment by ravenbuilder934** [comment]
First I've heard of it, but that doesn't mean it wasn't fixed already :p

**Comment by Raycoms** [comment]
Are you in a LAN mode server?

**Comment by kryldost** [comment]
Nah, connecting via an IP

**Comment by Raycoms** [comment]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior


## Actual behavior




## Steps to reproduce the issue



1. 
2. 
3. 

### Logs



- latest.log: 
- crashlog: 

### Notes


---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.


Fill in this template please

**Comment by kryldost** [comment]
Hello, so my issue seems to be fixed now! There was an update to the modpack and I couldnt log in although I seemed updated so I deleted the file of the instance and redownloaded the whole thing. Since both accounts that were affected were logging in through the same file, I believe there was something wrong with them. Thank you for your patience and giving me such quick replies! Much appreciated.
