### ISSUE TITLE
Pirate ship spawning and destroying Hospital building

### ISSUE THREAD

**Issue by AlieDupuis** [ldtteam/minecolonies#6474]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version. 
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.566
- Structurize Version: 0.13.104
- Related Mods and their Versions: N/A

## Expected behavior

I expect the pirate ship not to spawn inside of a built building, and possibly be a certain amount of blocks away.

## Actual behavior

Pirate Ship spawned inside the area of my hospital, destroying blocks on the edges of my building

![image](https://user-images.githubusercontent.com/72582289/106391132-cd560b80-63b9-11eb-87a8-0d96fea2b9d0.png)

## Steps to reproduce the issue

Unfortunately the steps to reproduce this error are minimal.
1. Build a large building near the edge of the water
2. wait for pirates to spawn into building and destroy blocks never to be found again

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by AlieDupuis** [comment]
Update: Once the pirate ship disappeared, the hospital building was put back to normal.

I want to build my town out onto water, so I still think it would be important the ships can't spawn into buildings.

**Comment by gattsuru** [comment]
There's some protection very close to the building blocks themselves, but it is a potential issue; AbstractShipRaidEvent relies on isSurfaceAreaMostlyMaterial, which is more meant to check whether the blocks on the same vertical level as the central spawn point are water or ice, rather than whether they have a clear view to the sky or whether the full volumetric area of the ship is eligible.

(CFE Rith's case https://discord.com/channels/139070364159311872/741531022872674314/798945223845609502 for a more extreme example, further augmented by what I _think_ is the issue at https://github.com/ldtteam/Structurize/issues/261 hitting a large storage system).

I think I can take a swing at it, once I've got a bit of time free from FRC setup.

**Comment by Raycoms** [comment]
We should probably do an overlap check with closest buildings
