### ISSUE TITLE
Console Logs Spammed with "Skipping Entity with id" While builder is working

### ISSUE THREAD

**Issue by darkninjas789** [ldtteam/minecolonies#6827]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.60-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior
No spam or a UUID to be presented with the entity for tracking

## Actual behavior
Over the past couple versions I have been getting the following spam in the Server console when a builder starts work on a building and will continue until the nighttime and will resume in the day.
It also once it starts it continues even if the builders are fired. 

## Steps to reproduce the issue

1. Set Builder to build something
2. see Spam
3. set to night
4. see spam pause

### Logs

- latest.log: https://gist.github.com/darkninjas789/80a32393d47d48bda63125c5e8191a82
- crashlog: no crash

### Notes
Currently playing on server world that has been played on since 0.13.676-ALPHA Minecolonies

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by darkninjas789** [comment]
Can provide world file if needed.

**Comment by PomPoko-lab** [comment]
Happens to me too since the last of versions as well. I searched the discord and github, no same issue so I thought it was just me. I've been ignoring it. Although I'm unsure if it causes any issues. I have been experiencing more lag than usual. I've started a new world to try to fix it but it comes back after awhile, unfortunately. Always updating to the newest version. No mods have been removed at all since world creation.

**Comment by Yuureishi** [comment]
I'm running a Valhelsia 3 server and this issue has occured on that, resulting in immense lag after a short period

**Comment by Raycoms** [comment]
@darkninjas789 what kind of other mods do you have installed? And does it still happen on the latest?

**Comment by darkninjas789** [comment]
@Raycoms 

Some world gen(re purposed structures) some magic and tech. At the time this started the only other mod we were actively using was project e but we used that be for starting a colony and the issue only came up once we had an established colony going.

And it is still happening with new version as of the last time we updated minecolonies wich was 04/05

**Comment by Raycoms** [comment]
Okay, I checked through this carefully, this is something that can only be triggered if you are rendering a building preview that has invalid entities in it. Or if chunks are attempted to be loaded with invalid entities (when an entity from a mod or the mod itself gets removed). I believe what is happening is that a builder is building around an area that has this. So this is not a MineColonie sproblem per se, but a problem uncovered by MineColonies loading some chunks.

**Comment by arrisar** [comment]
Hi @Raycoms, do you know where the log itself originates from? If MineColonies is producing this warning log, it would be _greatly_ appreciated if the spam could at least be alleviated. The logs for my server are currently entirely unusable because of this message happening every single tick.

Further, if the message could also be expanded on, it currently doesn't even provide the id for the entity. No spam, more and useful information, or at least a way to filter out this message in configs. Hell, point me at the file/line that generates this message and I'll submit a PR.
