### ISSUE TITLE
Miners won't level up past level 3

### ISSUE THREAD

**Issue by Zoidey** [ldtteam/minecolonies#684]
### Minecolonies version

0.6.2849 (for 1.10.2)

### Expected behavior

Miners leveling up past level 3

### Actual behaviour

Miners leveling up to level 3 and no farther

### Steps to reproduce the problem

Build a miner hut, level it up to level 5 and let the miner you hire to their thing.

I know it takes time for the miner to level up but I have one thats been mining for a week on my server (runs 24/7) and has yet to pat level 3 so I build another one and leveled up the hut to level 5 and even that miner was pretty quick to level up to level 3 but wont level up anymore than that.

**Comment by marvin-bitterlich** [comment]
You have a citizen hut for the miner at an appropriate level?

**Comment by Zoidey** [comment]
The hut is level 5, shall I try building another miners hut and only level it up to level 3 and see if the miner will level up past level 3?

**Comment by Raycoms** [comment]
His citizen hut (home) has to be existent and on a higher level to allow leveling past level 3.

**Comment by cheongchan** [comment]
Will this be implemented in minecolonies 1.11? The wiki is very sparse on details on things like this (due to multiple versions)

This is also very restrictive so i hope it will not be implemented. Otherwise, there is a bias to build and level up one house rather than build multiple houses at low levels first. This would be fine except all the odd items needed to level up a building. (Especially the builder)

I think just needing to level up the particular worker hut is better (simplier)

**Comment by Raycoms** [comment]
It has been implemented already in 1.10 and 1.11
