### ISSUE TITLE
Annoyances I found with the sifter

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6900]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: 

minecolonies-0.14.77-BETA-universal.jar
--

- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
https://wiki.minecolonies.ldtteam.com/source/workers/sifter
Would tell me how do meshes for sifters can now be obtained, and which citizens craft them

## Actual behavior

They don't, and I can't figure out how to make them as JEI doesn't show their recipes.
Also when I apply the diamond mesh into the sifter via creative, a bunch of announcements appeared in chat telling me my researchers unlocked the research for all the meshes, and after I re-checked, there isn't any research for them at all.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
The wiki update is under PR (https://github.com/ldtteam/MinecoloniesWiki/pull/588), with badly formatted relevant text [here](https://github.com/ldtteam/MinecoloniesWiki/blob/47fb76fea813239d00591ffc749524bb3e843490/source/items/meshes.md).

The Sifter would _normally_ unlock the String Mesh unlockable research when the Sifter lvl1 is completed, or on the first world load after updating the mod, automatically teach it to the Fletcher, and unlock the Unlockables branch at the university.  Further Sifter upgrades will give more durable versions.  I'm not sure if that's inconsistent with the behavior you saw.

EDIT: and, while only a _little_ useful because I changed how it handles Sifter and University behavior on mod updates in live worlds, do actually fill out the form.  We do need to know at least the Minecolonies version.

**Comment by ravenbuilder934** [comment]
Is this an actual bug? Or just a problem with the documentation?

**Comment by gattsuru** [comment]
It sounds like it might make sense to have items that are locked by the University to have tooltip text describing their requirements (and maybe even their crafter, unless that's going to be handled by the JEI plugin).  Kinda similar to how hut blocks update their tooltip to warn if they're locked by the university, but potentially with more detail, since a common case for this situation will have hidden research. I don't know if we can do tooltip overrides for external items in JEI/inventory very easily, but for the Minecolonies-specific items like plate armor, cake batter, meshes, etc, it wouldn't be too hard to set up.

There's a few things on the GlobalResearchTree side that it might make sense to refactor if we want to have detailed information pointing to the specific university requirements, in which case it might be faster for me to rework in than Mekle001.

But unless there's something really inconsistent going on if a low-level sifter is gifted a higher-level mesh than the colony has unlocked, which doesn't seem to be the case, no, I guess it's not really a bug.

**Comment by warning-djkajslh** [comment]
Also when I take a look at the blacksmith teaches recipes I only see the recipe for iron mesh, and not the diamonds, also nothing shown where to craft the other meshes, not even the wiki, so this is at least a wiki problem.

**Comment by ravenbuilder934** [comment]
Incorrect, there is now a wiki page for Meshes with their crafters as well
