### ISSUE TITLE
Sifter Hut gui missing

### ISSUE THREAD

**Issue by Fitzer11** [ldtteam/minecolonies#6937]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context    and 

- Minecraft Version: Minecraft 1.16.4
- MineColonies Version: minecolonies-0.14.40-BETA-universal.jar
- Structurize Version: structurize-0.13.113-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior
To interact with the Sifter's Hut's gui and set him working

## Actual behavior
 The hut gui just shows daily limit field with an ever present 0. I upgraded to level 3 hoping something would happen, but its just the same. I've done all the check list: fire, rehire, pause, start, etc. No needs, no requests, worker just stands there every day.

## Steps to reproduce the issue

 

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
Have you set a prestock in the hut for what you want to process?

**Comment by Fitzer11** [comment]
There's no option in the gui to set it. That's the the main problem here. I gave him 4 stacks of gravel a week ago and he still has all of it

**Comment by Mekle001** [comment]
There is a tab to set "prestock" on the left side. That's how you set what they request. Gravel is only part of it, the sifter also requires a Mesh now, which the string version can be made by the fletcher. 

My recommendation is to add a prestock for both gravel and the mesh you would like, and that should resolve your issue. The prestock numbers are in stacks, and the meshes don't stack, so a 1 is probably fine for the mesh, though you may want a larger number for the gravel to minimize courier trips. 

The UI that used to allow you to set how many to do per day changed, as did the text around it. It now displays how many have been done vs the daily limit for the level of hut.

**Comment by Fitzer11** [comment]
Setting up gravel mesh as a minimum stock did finally get him going eventually, thank you for that. There's still no ui on the second page giving options on which mesh to choose or anything other than the count box. It's just really unintuitive as it's the only profession Im aware of that you have to set out a particular minimum stock just to get the worker to work. I think I just wasn't expecting that to be necessary.

**Comment by Mekle001** [comment]
It's also the only profession (that isn't a 'gatherer') that works entirely on it's own, instead of on-demand based on requests from other crafters. 

While the gatherer professions all request a tool, it's a simple matter of whatever tool is available in the colony, and they are vanilla tools. The mesh is different than all of that, and given the cost varies from a single string to a diamond, we wanted to make sure you had the choice of which mesh to use. You only saw one, because your building is not yet at the level to unlock the more capable meshes. 

I expect to see us use the minimum stock mechanic more in the future, for a variety of purposes. It already is one of the best ways to optimize several of the crafters (Baker is great to set a minimum stock of dough, and then it quickly responds to bread requests)

**Comment by uecasm** [comment]
Not quite the only one; the crusher is another.  That one does still have a mode-based UI at present, but it's possible that might change in the future.

And you don't *have* to use the minimum stock, you can just dump items in their hut inventory periodically (including at least one mesh).  But the minimum stock is easier and more automated.

**Comment by Mekle001** [comment]
The crusher is a bit different because it does respond to on-demand requests, because the outcome of a recipe there is deterministic. the background processing is an option today, yes. But that's slated for removal when I find the time. 

With the sifter having non-deterministic outcomes, where a recipe cycle may or may not produce anything, and when it does it could be one of N different things, we haven't hooked it up to the request system, though we have a plan on how we might do that. This is what makes the sifter unique today. 

That having been said, the sifter will become a template for some other resource gatherers like the nether worker, and the "drop required items in the building, or prestock required items" will be a bit more common
