### ISSUE TITLE
Pathing killing children at night. 

### ISSUE THREAD

**Issue by Sabbatha** [ldtteam/minecolonies#6964]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Valhelsia 3 release 3.2.1
- MineColonies Version:0.14.110
0.13.166
- Structurize Version: 0.13.166
- Related Mods and their Versions:

## Steps to reproduce the issue

1.  Build Fortress Style Alternative 2 civilian hut. 
2. set housing to automatic, and children being born to on. 
3. They are automatically assigned to available upstairs bedroom.
4. Night falls and they try to go to sleep, but instead fall to their deaths. 

### Logs

https://gist.github.com/Sabbatha/c282dcdcff1fed006bc8b7d3a0c5e085- latest.log: 
- crashlog: No crash. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just a note - I thought this had been reported months ago =P It can happen with adults too - it's the upside down stairs at the top of the ladder that cause it - turn them the other way up, and they are fine =)  Pretty sure it's the same problem anyway!

**Comment by Raycoms** [comment]
do you have a screenshot of where they die?

**Comment by Melriken** [comment]
They try to climb the ladder, fall off near the top and land next to the chests below the ladder.  They take a SMALL amount of damage and attempt to climb the ladder again... if you wait for 'All colonists in bed' the child dies... a new one is born... and the next night... yeah... nothing gets done in that colony again.

I tried walling in the ladder and replacing the floor with hay bales, the kids still fall off and still die...

Adults do NOT fall off that ladder, moving an adult into the house prevents the issue.

Talyda sounds correct that this is caused by pathfinding on the upside down stairs causing the shorter children to get off the ladder too soon and fall, while the taller adults can't get off before they are high enough to stand on that step.  I didn't take a screen shot and fixed it by filling the house with adults so it isn't happening to me any more.

**Comment by Melriken** [comment]
Sorry meant to say the block they die on is the one one step closer diagonally to the house's door than the ladder itself (this is adjacent to a chest).

**Comment by Melriken** [comment]
![Childdied1 jgp](https://user-images.githubusercontent.com/10856771/115608187-cb099c00-a29a-11eb-8ab1-c3a9592ee51e.jpg)
![ChildDied2](https://user-images.githubusercontent.com/10856771/115608197-cd6bf600-a29a-11eb-8ee1-fcd08cc91aa9.jpg)

https://www.youtube.com/watch?v=iCHSADOiHmU

Warning: Video is sad... ends badly :(
Also the message says he died on the chest, this is NOT the location I experienced in my survival world, but you can see the message and the map location info in the second screenshot.

**Comment by Talyda** [comment]
Negligent homicide officer!

**Comment by Sabbatha** [comment]
I’ve already moved adults in. I’ll replace the upside down stair at the top as well. I also noticed that some builders get stuck on ladders capped with trap doors so I removed them, and some builders get stuck on the rails draped over piles of logs in the sawmill hut. I just removed them as well.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by patgoull** [comment]
I can confirm this happening also on recent alphas with fortress alternative. I've recently had the problem on several fortress alternative houses.
