### ISSUE TITLE
Sifter complains of no mesh, does not request one properly

### ISSUE THREAD

**Issue by Lielac** [ldtteam/minecolonies#7082]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.155-BETA
- Structurize Version: 0.13.171-ALPHA
- Related Mods and their Versions: Playing Life in the Village 2 for 1.16.5, but I doubt this is relevant

## Expected behavior

When the sifter doesn't have a mesh of the appropriate level, a request is sent to the warehouse and/or the fletcher to get or make one, and if there's no fletcher to make one the request for a mesh should appear on my colony clipboard.

## Actual behavior

I have a fletcher, with a worker. I have a sifter, with a worker. The sifter sits in their hut complaining of not having a mesh of at least level String, but doesn't send this request on to the fletcher or warehouse. When I manually request string meshes be made via the postbox and then put them in the warehouse, none are couriered over to the sifter. Ultimately I have to ferry the mesh to the sifter myself.

## Steps to reproduce the issue

1. Build a fletcher.
2. Unlock sifter, build sifter.
3. Unlock string mesh.
4. Watch your sifter sit there, complaining of no mesh without requesting one, for in-game weeks.

### Logs

- latest.log:   [latest.log](https://gist.github.com/Lielac/6ccb6ef7029c5efa42d4c876cd9b1f7f)
- crashlog: 

Pretty sure latest.log isn't relevant, and this isn't a crash bug. 

### Notes

Broff#0083 on the Discord also reported this issue but probably isn't on the same mod versions. They also reported the sifter doesn't properly request siftable materials, but I'm not sure of that myself because I skipped straight to bringing my sifter both a mesh and a stack of sand.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by chandler05** [comment]
Can confirm, should be a simple fix, working on it now.

**Comment by Mekle001** [comment]
This is a matter of making sure the user has control over which mesh is in use. The sifter doesn't know which of the 4 meshes they should request, so doesn't. 

If you want the sifter to request a mesh, go into the prestock tab of the sifter, and add the mesh there, at which point the sifter will request one. 

This way, if you don't want to use more than string meshes, it won't be eating your diamonds because it can.

**Comment by aelfwyne** [comment]
I'm not sure why this is closed because it's clearly broken. No other hut requires you to know to "pre-stock" an entire stack of items just so they worker can have it. He should request the mesh, period. I've been trying to figure out why the fletcher won't craft anything, only to find this thread claiming the "doesn't order anything but complains anyway" is by design?

If anything there should be an option in the sifter UI for which mesh to request.

**Comment by uecasm** [comment]
"An entire stack of items" for a mesh is exactly one mesh, since they don't stack (like all other items with durability).

They can't request one directly from the request system because there's several different kinds of meshes and they don't know which one to order -- you wouldn't like it if you wanted them to be using one of them but they ended up requesting the wrong one, wasting your blocks and generating the wrong resources.  So you have to either give them the desired mesh or set a request for it yourself.

This is explained on their [wiki page](https://wiki.minecolonies.ldtteam.com/source/workers/sifter).  And if they don't have a mesh, they should have a little cog on their head and if you talk to them they'll ask for one.
