### ISSUE TITLE
Composter's Hut, "Items to Compost" is empty

### ISSUE THREAD

**Issue by firatakandere** [ldtteam/minecolonies#7111]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.163-BETA-universal.jar
- Structurize Version: structurize-0.13.171-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

When I interact with Composter's Hut and go to "Items to Compost" page, I expect to see compostable items.

## Actual behavior

There's no list.

![Screenshot](https://i.imgur.com/6ty9OTy.png)

## Steps to reproduce the issue

1. Build a Composter's Hut.
2. Right click to Composter.
3. Go to "Items to Compost" tab.

### Notes

Happens with other players in the server as well.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
can you send the latest.log? (preferably in a paste site)

**Comment by firatakandere** [comment]
https://pastebin.com/JvRYxvGS

1. Restarted server.
2. Re-produced issue.

**Comment by gattsuru** [comment]
Do you have a client-side log?  The server appears to be loading the compostables, but it's plausible some other mod has done something screwy to the RecipeManager on the client side.

**Comment by Raycoms** [comment]
Isn't this the same recipe issue we had already with the fuels?

**Comment by gattsuru** [comment]
CompatibilityManager.getCompostables uses a separate path from the rest of compatibility manager, and hooks a RecipeManager pulled directly from the Minecraft.getInstance, rather than one created during RecipeUpdatedEvent, so it's possible that this can have problems in instances where the other compatibilityManager stuff is showing up. (Possibly including if remote clients don't have JEI installed?)  It may be related to some of the issues that drove the fuels, food, and flower rework, though; there's a lot of the stuff Forge doesn't populate, or populates in weird orders, for remote clients.

EDIT: it _does_ work fine with just Minecolonies + Structurize + JEI, though.

Firatakandere, do your players have similar blank lists on the cook's fuel and food page?

**Comment by firatakandere** [comment]
@gattsuru yes, one more player experienced the same issue. However, installing JEI on client-side resolved the issue for both of us. Thanks for the advice!
