### ISSUE TITLE
Composter GUI - unable to select materials to compost

### ISSUE THREAD

**Issue by VampireTechnologyLord** [ldtteam/minecolonies#7161]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.14.182-ALPHA
- Structurize Version: structurize-0.13.174-ALPHA
- Related Mods and their Versions: none

## Expected behavior

A list to toggle the items the composter is allowed to compost

## Actual behavior

When i open the composter gui it all works perfectly fine, unless i open the tab to toggle which items the composter is allowed to compost. There is just a button "Reset to default" (which does nothing on click) and a searchbar at the top. The "Settings" and the "Main" tab work fine.

![image](https://user-images.githubusercontent.com/75166884/119823066-adac9b00-bef4-11eb-8341-38093049d6f2.png)

## Steps to reproduce the issue

1. Construct a composters hut
2. Open the composter hut block gui
3. Click tab "Items to compost"

### Logs

- latest.log: https://gist.github.com/VampireTechnologyLord/4a87ce7569a22dcc5ef2d1f5fad71d69
- crashlog: none

### Notes

none
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Does this happen with just minecolonies and structurize (no other mods)?

**Comment by Stoovey** [comment]
Some sort of config is not being loaded once the Composters hut has been

a) Built
b) Upgraded

Building/Upgrading the Composters Hut will disable the Items to Compost screen which actually results in the Composter not working because there is no config for it to read from.

If you now restart your server (after building/upgrading) the Items to Compost screen will show and the Composter will start working as normal :)

**Comment by VampireTechnologyLord** [comment]
So first ravenbuilder934, no, it only happens with them. Second: I'm playing singleplayer and even after reconstructing it and restarting the game it doesn't works.

**Comment by uecasm** [comment]
This should have been fixed by 0.14.170-ALPHA and up, are you sure you're using a newer version?
Although do try the test without other mods, a known issue is that if you have too many mods with too many recipes then some of them can get lost.

**Comment by uecasm** [comment]
Your log is full of recipe parsing errors, it seems likely that you have some other mod (Recipe Stages, perhaps) that's causing issues.

**Comment by Stoovey** [comment]
@uecasm,

I'm able to replicate this on my server too. Did you see my comment?

> Some sort of config is not being loaded once the Composters hut has been
> 
> a) Built
> b) Upgraded
> 
> Building/Upgrading the Composters Hut will disable the Items to Compost screen which actually results in the Composter not working because there is no config for it to read from.
> 
> If you now restart your server (after building/upgrading) the Items to Compost screen will show and the Composter will start working as normal :)

**Comment by ravenbuilder934** [comment]
@Stoovey this is really the symptom of tags not being able to load because of issues in other mods. So, it depends very much on what other mods you have installed, which I'm guessing is not the same as VampireTechnologyLord. (Also, VTL said restarting didn't help.) If you send *your* log we can look at it

@VampireTechnologyLord Since it doesn't happen with just mcol, it's not our issue. Check with different combinations of mods to find out which one it is (uecasm mentioned Recipe Stages as a possible culprit)

**Comment by Stoovey** [comment]
@ravenbuilder934 

https://gist.github.com/Stoovey/0b84d4920af86f71dab6aee56637c2b7

However, this probably isn't going to show anything because I've already restarted my server and the "Items to Compost" screen now works.

**Comment by ravenbuilder934** [comment]
yeah that doesn't show any errors
