### ISSUE TITLE
This one will never grow :(

### ISSUE THREAD

**Issue by gd71** [ldtteam/minecolonies#718]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.3125

### Expected behavior

- Plant slime tree sapling after harvesting slime tree

### Actual behaviour

- plant oak sapling instead of slime sapling

### Steps to reproduce the problem

1. Put a slime sapling on slimy dirt in a lumberjack area
2. wait lumberjack to cut the slime tree
3. Weep over the fate of this poor oak slime which will never grow :cry: 
![2017-03-19_20 51 49](https://cloud.githubusercontent.com/assets/25818272/24084254/f18b6fc8-0ce6-11e7-9dea-44f801584c83.png)

I hope it could have touched you too :smile:

**Comment by gd71** [comment]
quite sure the lumberjack don't keep the slime sapling in its inventory too

**Comment by Raycoms** [comment]
@nojo might be a problem with the metadata?

2017-03-19 17:03 GMT-03:00 gd71 <notifications@github.com>:

**Comment by Wissi** [comment]
@nojo121 These are the current Issues with the LJ and Slime trees.
The LJ will plant any sapling anywhere.
1.- Plant normal saplings on the slimy dirt/grass (Which is also doable by player) instead of the Slime sapling.
2.- Plant Slime saplings on normal dirt (which player can NOT do) instead of oak saplings. (not sure if other variants as well) and which will never grow.
3.- Will not plant the correct variant of Slime Sapling it just harvested (if various types are planted).
3.- Will NOT harvest the leaves, will only take down the trunk like a normal tree. (This issue seems to be only in SMP. Apparently in SSP he does take down the leaves.)

The saplings Block ID is: " minecraft:sapling ", so I guess they are missing the Block Id **Data values:**
```
Oak Sapling         :0
Spruce Sapling      :1
Birch Sapling       :2
Jungle Sapling      :3
Acacia Sapling      :4
Dark Oak Sapling    :5
```
And the slime saplings Block ID is:  " tconstruct:slime_sapling " and the Block Id **Data values:**
```
Blue Slime Sapling      :0
Purple Slime Sapling    :1
Magma Slime Sapling     :2
```

**Comment by gd71** [comment]
indeed,
thanks @Wissi  for clarifying this
I was not aware that oak sapling can grow on slimy dirt (which became normal dirt after it grown)
I assume other points than the first one are not expected ?

**Comment by Wissi** [comment]
Unfortunately those are the issues the LJ has atm with the slime trees. I'm sure @nojo121 will fix these issues soon and make the next update, he's been pretty fast and thorough with his coding.

**Comment by gd71** [comment]
No problem, it's fine and this is not breaking too much the game!
A software without issue is an unused software :smile:

**Comment by nojo121** [comment]
Hey,
sorry i hadn't got any time!
I'll fix all LJ issues asap!!!!
Sorry for letting you wait :(

**Comment by Wissi** [comment]
@nojo121 Hi, it's been a week now. Any update on the fix?

**Comment by Wissi** [comment]
@nojo121 Hmmm... 15 days ago. Any news?
