### ISSUE TITLE
Animals escaping from buildings

### ISSUE THREAD

**Issue by nmills3** [ldtteam/minecolonies#7260]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.223-ALPHA-universal.jar
- Structurize Version: structurize-0.13.177-ALPHA-universal.jar

## Problem description
Animal keepers leave gates open for too long and let animals escape the pen. For example with the wooden shepards hut over time the sheep will escape the wooden fance pen and make their way into the building and then eventually escape out of the door as citizens come and go. this leads to the area slowly filling with sheep as the shepard will then breed new sheep (even inside of the house) and then those sheep will also escape into the surrounding area

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah, we know. As of now we see this as "Gives the player sth to do". We plan on extending this system in the future to reduce this  and make a better more realistic system in general.

**Comment by ghost** [comment]
Any update on this issue? My colony is overrun with Sheep, pigs, chickens and cows and all my rabbits have run away. This really shouldn't be the intended behaviour. Maybe some kind of bouding box which animals within are counted as " managed" by minecolonies and have a slightly different ai which doesn't allow them to leave when the gate is open?
Right now tthe animal herders colonists are kind of useless because they don't do their jobs effecctively.
I get the rest of the colonists being slow (e.g. the miner/farmer) for balance, but they do eventually get the job done. The rabbitherder lets the rabbits escape and then they are useless unless you go hunting rabbits over and over.

**Comment by uecasm** [comment]
Different building styles can do a better job of keeping animals contained.  Or if you ask about it on Discord there's some other advice that can help.

**Comment by oliverrook** [comment]
I have this happening a lot too.
What makes it more annoying is sometimes they just straight up leave the gate open.
I've started putting pressure plates on one side of the gate so they auto close.
