### ISSUE TITLE
Minecolonies and structurize should be published in sync, otherwise it's silly!

### ISSUE THREAD

**Issue by jgilmore** [ldtteam/minecolonies#7289]
The latest structurize version available on curseforge does have a corresponding version of structurize available.

Playing the the latest BETA of minecolonies that's available on curseforge requires structurize 14.177 ALPHA. This version of structurize IS NOT AVAILABLE on curseforge. Therefore, playing the latest beta requires compiling (with gradle) the PRECISE version of structurize that version of minecolonies requires.

This, in turn, requires getting the right version of gradle and ALL DEPENDENCIES. (6.5 is too new, 4.4.1 (the default for my distro) is too old.

SOLUTION:

When posting minecolonies to curseforge, upload the required version of structurize too. If it's not labeled as a BETA rather than an ALPHA release, then it should be relabled as BETA before posting. (Having a BETA version you can't run without ALPHA libraries is silly!)

I've given up on playing the latest beta, as structurize isn't compiling on my machine. I've spent an hour or so fiddling with this, and I've given up.

Please let me know when you have a BETA that's actually playable AT ALL on minecraft 1.16.5. Thank you!

**Comment by ravenbuilder934** [comment]
0.13.177 absolutely *is* on curseforge. When you're in the Files tab, click View All.
Our betas and alphas are at about the same stability; we just release alphas because curseforge limits the amount of releases and betas we can put out.
The version of structurize required is bumped manually in case there are breaking changes in structurize, which there were for this update. it'll be bumped soon.
