### ISSUE TITLE
Miner doesn't Mine on y:12 or y:8

### ISSUE THREAD

**Issue by Ch4in3r007** [ldtteam/minecolonies#7294]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 Forge: 36.1.30
- MineColonies Version: minecolonies-0.14.178-ALPHA-universal
Mine Colonies pack from Cursedforge with only addition of Smelting rotten flesh into Leather, had no problems so far

### Logs

- latest.log: https://gist.github.com/Ch4in3r007/c963cdfef8825364aac9311fc3a3bf1e

## Steps to reproduce the issue / details

So my Miner Level 3, Worker Level 8, housing Level 2 dug down his shaft and made the 2 last Nodes on y:12 and y:8, i assigned him to y:8, he dug up 5 Nodes, then stopped working, even after recall, Fire and hire etc.. So i asigned him to y:12 and he made 15 Nodes and also stopped working there. I led him dig a few Levels higher, there he had no problem. Today i tried again to set him down, he dug a few more nodes on y:8 and stopped again. after resetting him back to higher lvls and again back to the lowest lvl he went down, started digging (he got Cobbel in his Inventory), but after a few seconds stopped with request, as i opened he showed me error, i should open log and send it here. In the log the error is pretty much, but starting at Line 1300 it looks interesting.

Just reporting the AI issue. 

### Notes

---
## Viewers
![grafik](https://user-images.githubusercontent.com/86434324/123322844-0ba0c280-d535-11eb-8a71-e19d15565b1f.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
So this is the error that happens when the miner mines too low? Did you try it on the latest version too?

**Comment by Ch4in3r007** [comment]
I installed only a Week ago and didn't update so far, will do now and test again, give me a few minutes.
And yes, it only happened when he was mining that low, i checked the surroundings and seems like he hit a big open space, but i supplied him with cobble and he just mined fine on a higher level before when that happened.

**Comment by Raycoms** [comment]
If it still happens, I need a new log too, it's normal for them to stop mining when they hit an open space after some time. But they shouldn't error. they should jus tskip it.

**Comment by Ch4in3r007** [comment]
Ok, Updated both mods, he went back to the same place, mined there (got cobbel in Inventory and some Ores), but there was no Visable Mineshaft he dug and then switched to torches in his hand and tried to playce them, but got stuck again without error, can join the Discord to stream if that helps

**Comment by Raycoms** [comment]
Can you send me the world?

**Comment by Ch4in3r007** [comment]
Ok, can do if you tell me which Files you need and where i can upload them (also joined Discord (Ch4in3r#4223)
I dug arround a bit and found he dug his new tunnels behind a 2 block thick wall, as i opened them he progressed and dug again, placed his Mineshaft stuff and went to the second node he also dug behind a wall that i opened up. He now Digs there also without opening up, seems like the Mineshaft placement is off by a bit.feel free to contact me on Discord also

**Comment by Ch4in3r007** [comment]
HE is now trying to make the Mineshafts completely off form where he was doing them before 
![grafik](https://user-images.githubusercontent.com/86434324/123330005-bf0db500-d53d-11eb-9336-09ee1d328182.png)
I made a little pokehole, if i connect the ways he will maybe figure it out by himself?

**Comment by Ooh-Wallah-Wallah** [comment]
Ray, if this is still an open issue. If it can help in any way, my miner on the ADV server has this issue (or something very similar). 

You'd have to check in the hut block what level it is but it should quite obvious when compared to the nodes dug on levels round-about. Please feel free to mess around with it, if you need to...

I'm not going to be able to get onto the server myself for a few more weeks so can't dig that up.

**Comment by Teldrik** [comment]
Chiming in that I have this issue as well. 

The lowest level of my mineshaft is at y=8 and whenever I set that to be the actively worked on mining level, the worker only stands at the hut block with the (WORKING)[MINER_CHECK_MINESHAFT] tag above his head. Any other level seems to work fine but this one just makes them stop working entirely. My y=12 level does seem to work though, it's mostly the y=8 level that has issues for me.
So far, 13 nodes have been created on that level. But those were made well over two weeks ago. 
The miner has a diamond pick. There was lava on that level prior but with both the lava immunity researched and much of the lava lake turned into obsidian he should have no issues working. The worker has been replaced with no change in behaviour. I have had the issue on y=28 where the miner digs unconnected tunnels at some point as well. 
Hut block is at level 5. Had to creative in some resources to get one builder to level 5 for it early since I was experiencing that bug where the miner was at level 1 complaining about not having a diamond pick (An issue I think was fixed a while back now)

I ordered a mineshaft repair on both y=12 and =8. None have been finished despite access to materials. May or may not be related. 

Am playing on the modpack "Life in the Village 2". Latest update but with manual updates to keep Minecolonies and Structurize up to date with the current (22 of august) update, Version 0.14.342 BETA. No incompatibilities noticed as of yet due to the modpack centering around Minecolonies in the first place.

**Comment by Raycoms** [comment]
Can you send us a colony export from this world?

**Comment by Teldrik** [comment]
Alrighty. Tossed it into my drive.

Link: https://drive.google.com/file/d/1E-HB15FI6vkW3lTKlEZL4syT6NeMMkwr/view?usp=sharing

Not sure how well the world will load without the modpack but I hope it helps nonetheless. Let me know if I did something wrong. First time exporting so I will just assume I managed to do it correctly and there's no hidden command somewhere I should have used instead.

**Comment by Raycoms** [comment]
There is a colony export command, did you use that or just did a plain world upload? =D

**Comment by Teldrik** [comment]
I used the export command. I remembered having seen it when checking about for the various commands ingame. So that's what I used. Hopefully that's the proper way.

**Comment by firstiik** [comment]
Hi, I also have a problem with miner, but probably not exactly the same.
Miner stands next to mine and say and says locate "lates.log" and send the author.
In "Request Resources" writes "schematics / medievaloakalternati Step 0/6"
The last excavated lvl is level 18 at Y: 22.
Mine has no Nodes.
It looks like it has dug up a lvl and wants to build, but it only costs, I tried the Fire / Hire worker, restart the worker, and hire another, still the same bug, the bugs I noticed on the version of "minecolonies-0.14.343-ALPHA-universal. jar ", I also tried the version of" minecolonies-0.14.338-BETA-universal.jar ", but there is also a bug.
I use Biomes O 'Plenty to generate biomes.
What strikes me as strange is that if I use the "Build tool", I only find a model of a wooden mine, but my miner builds floors from cobblestone (medievaloakalternative).
[latest.log](https://github.com/ldtteam/minecolonies/files/7028358/latest.log)
