### ISSUE TITLE
Jungle style farm wont build

### ISSUE THREAD

**Issue by bigdon4** [ldtteam/minecolonies#7400]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  

- Minecraft Version:1.65, I am also playing Valhesia 3
- MineColonies Version:0.13.614 ALPHA

### Logs

- latest.log:  https://gist.github.com/bigdon4/48355c91bd9eb7b789f0bc29a71bdba1
## Steps to reproduce the issue / details

Create a jungle colony, build a level one farm.
The farmer will get stuck on the vines and be unable to complete the build, he also seems to be obsessed with constantly trimming the vines when they get to long so no progress is made.

### Notes

I have tried for total over 150 days on this alone and he will not finish, he's finished the structure, but will not complete the vines and logs and some fences.

I have tried building the farm over pre-existing trees, as well as letting him build them himself and just supplying him the logs, but both ways end up the same.

Now the building hut shows 100% supplied, but 0% finished, even though it was around 88% before.

I do recall him but he just gets stuck again.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by bigdon4** [comment]
Also forgot to say I have tried a few different recent versions of minecolonies but with no change.

**Comment by ravenbuilder934** [comment]
That Minecolonies version is over 270 out of date, update

**Comment by bigdon4** [comment]
i have tried the latest update aswell i just reproduced it on the alpha as I thought it was neccesary

**Comment by Raycoms** [comment]
I think we need some way to have the builder ignore "growing things". Else it might just be stuck indefinitely in the clear step.

**Comment by Raycoms** [comment]
Are you using optifine smooth world?

**Comment by bovine** [comment]
I am also running Valhelsia 3 (1.16) modpack, which includes minecolonies-0.14.310-ALPHA-universal, and had a lot of problems getting the level 1 Jungle Farm to build, although I eventually succeeded. Most other Jungle building types haven't had as many problems as the Farm, for whatever reason...

Some observations:

The builder would waste a lot of time climbing up and down the vines of neighboring structures to attempt to get close to the part of the Jungle Farm he was working on. Since the builder works on tall structures layer-by-layer, left-to-right, this means a lot of climbing to get close to the different edges of the Farm.
- My workaround was to manually prune away a lot of the vines on neighboring buildings, the builder won't waste time trying to climb up/down them and will just build from the ground level (much more time efficient).
- I also manually built a small bridge between the tops of two neighboring trees that I found my builder would frequently climb up/down to get between. This is obviously something specific to my build, but highlights the problem caused by climbing up/down neighboring trees.
- It would be more efficient to limit how far the builder is willing to climb+walk just to try to get closer to the building area. If there is already some distance calculation occurring, perhaps it is not considering the amount of climbing that is also needed. Just standing in the center of the Farm and waving his builder hands from afar would also be acceptable.
- It might also be more efficient to allow the builder to focus on finishing building up one of the trees at a time, rather than always working up layer by layer. This would also limit the amount of wasteful travelling around just to get close to the build area.
- Maybe require the builder stay within the new building's square footprint when trying to get close to the active build area?


Sometimes the builder will get stuck in a path-finding loop while on a vine, climbing up a vine then climbing down one unit, and then repeating.
- My workaround was to frequently use the "Recall" button on the builder's hut to get him down. Manually pruning away these specific vines prevented him from going back up those vines.
- Maybe some "stuck builder" detection logic should be added and automatically teleport the builder to where he needs to go if he is unable to make progress getting to where he needs to go after awhile.


When adding leaves to the jungle trees, parts of the recently placed leaves would despawn within a few seconds--apparently because they were too far away from the tree trunks. The builder would waste a lot of time coming back placing the more leaves that would again just disappear. This would eventually self-resolve and move to the next layer, but I feel there are still a lot of missing leaves that were intended to be placed but have been despawned.
- Maybe the builder needs to be an attempt to ensure that the leaves closest to the tree trunks are placed first?
- There may be an interaction with the faster tree despawning mod present in Valhesia 3?


The builder would occasionally fall when climbing up/down vines of neighboring trees. When this happens enough, he dies and another builder will need to take over. I had at least 5 builders die during the building of my Jungle Farm because of this, particularly in the later stages of building the Farm when it was getting taller.
- I'm not sure what circumstances causes the builder to fall from vines or tops of trees, but they need to path-find properly before picking a route that may cause them to fall.



If the builder dies and a new one starts, there is a lot of wasted effort that the new builder attempts to re-do when starting work. In particular, the new builder will try to remove any new vines that have started growing on the trees of the Jungle Farm. The new builder will also remove many of the torches and fence railings on just the entry walkway to the Jungle Farm and eventually build them back again in the same place.
- Maybe the builder should ignore vines when looking for things to remove
- I'm not sure why the fences and torches are getting destroyed and rebuilt
- This part is probably related to #7180
