### ISSUE TITLE
"Bad guys" are too OP!

### ISSUE THREAD

**Issue by seannyyx** [ldtteam/minecolonies#7408]
### Prerequisites 

- [/ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ /] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [/ ] I made sure that **this issue is not a duplicate of any existing issue.**

raiders spawn. and obliterate nearly all my knights and archers, despite having netherite armour and weapons

- Minecraft Version: 1.16
- MineColonies Version:14.292
- Structurize Version: 13.200
- Related Mods and their Versions:

## Expected behavior
knights and archers defeat the raiders, some (few) casualties. 

## Actual behavior
Go from 40 to 5 knights and archers and even I have died at least twice (also in netherite armour) before all the raiders are dead.

## Steps to reproduce the issue

play the game, have somewhere around 80 people, (including 30 knights and 10 archers, most of which are in diamond armour or higher.) and have a raid that just wipes you out. (despite the barbarians only occasionally wearing some chain armour.)

**Comment by Raycoms** [comment]
I'll close this already, because this indeed may happen occasionally in the following situations: (From a combination of the factors)
a) Hard mode strongly increases their strength
b) Colony size and skill level of the citizens are high
c) Archers and Knights have under average levels (very little combat experience and were not trained at the facilities)
d) The player defended the past raids without guard interference without anyone dieing.

This slowly ramps up the difficulty and might at one moment lead to an overwhelming raid.
