### ISSUE TITLE
Slimetrees

### ISSUE THREAD

**Issue by Liguma** [ldtteam/minecolonies#744]
### Minecolonies version

latest on server

### Expected behavior

lumber should replant slimesapling after cutting a slimetree

### Actual behaviour

replants oaksapling

**Comment by Wissi** [comment]
Yeah, same as Issue #718 
 
@nojo121 These are the current Issues with the LJ and Slime trees.
The LJ will plant any sapling anywhere.
1.- Plant normal saplings on the slimy dirt/grass (Which is also doable by player) instead of the Slime sapling.
2.- Plant Slime saplings on normal dirt (which player can NOT do) instead of oak saplings. (not sure if other variants as well) and which will never grow.
3.- Will not plant the correct variant of Slime Sapling it just harvested (if various types are planted).
3.- Will NOT harvest the leaves, will only take down the trunk like a normal tree. (This issue seems to be only in SMP. Apparently in SSP he does take down the leaves.)

The saplings Block ID is: " minecraft:sapling ", so I guess they are missing the Block Id **Data values:**
```
Oak Sapling         :0
Spruce Sapling      :1
Birch Sapling       :2
Jungle Sapling      :3
Acacia Sapling      :4
Dark Oak Sapling    :5
```
And the slime saplings Block ID is:  " tconstruct:slime_sapling " and the Block Id **Data values:**
```
Blue Slime Sapling      :0
Purple Slime Sapling    :1
Magma Slime Sapling     :2
```

@nojo121 has been working on it for over a week now from a request that had a bounty on it, it's actually a fix of the original request which has not been finished. He's usually fast about replying and fixing the issue. We'll just have to wait I guess.
