### ISSUE TITLE
Pathing issue with colonists: They go swimming [$10 awarded]

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#754]
### Minecolonies version

version 0.6.3317.

### Expected behavior

- When a colonist/guard goes to the next waypoint, they stay on dry land.

### Actual behaviour

- They take the shortest route, typically going for a swim, even if there is no way for them to get out of the water on the other side.

### Steps to reproduce the problem

1. Build a Fishing hut on one side of a large body of water.
2. Place a citizen hut on the opposite side of body of water.
3. Make sure that there is a dry land/bridge route to the citizen hut. Preferable both. Make sure route is not a direct route to either huts.
4. Use the command _/time add x_ to make it night time.
5. Watch as the fisherman swims across the body of water, ignore the dry route.

**Comment by SulpherStaer** [comment]
Builders do the same, even when a bridge is available.

**Comment by cltnschlosser** [comment]
Okay, so I played around with this, and found that because our heuristic is valued so highly, the extra weight that we put on swimming doesn't have enough affect. I doubled the value, and I'm seeing much more reasonable pathing.

Here are some screenshots from before my change:
![2017-05-22_11 35 31](https://cloud.githubusercontent.com/assets/1498529/26320306/0bf952e8-3ee8-11e7-90fd-9ba9222f4daa.png)
![2017-05-22_11 37 46](https://cloud.githubusercontent.com/assets/1498529/26320315/121d69e8-3ee8-11e7-82ef-761be3da3c98.png)

And after the change:
![2017-05-22_11 44 13](https://cloud.githubusercontent.com/assets/1498529/26320326/1d8b6172-3ee8-11e7-9f17-1209b3efd8e4.png)
![2017-05-22_11 44 52](https://cloud.githubusercontent.com/assets/1498529/26320335/218fe52c-3ee8-11e7-8ca7-8ac1454e1540.png)
![2017-05-22_11 59 49](https://cloud.githubusercontent.com/assets/1498529/26320355/375813a2-3ee8-11e7-9ff3-f01347d6e6f3.png)

In the last one you can see that if a citizen can't get out of the water on the other side, they won't enter the water (This may not be true for when the path gets broken into several different attempts).

Also while looking at this, I found that we weren't properly deprioritizing jumping/falling. The citizens are now more likely to walk around a singular block if it would require them to jump.

**Comment by cltnschlosser** [comment]
Also, you can see here that if there was more water, they would path around it, these values may need to be tweaked still:
![2017-05-22_12 21 37](https://cloud.githubusercontent.com/assets/1498529/26320692/5cbb24da-3ee9-11e7-989f-d230b0625bb6.png)

**Comment by Raycoms** [comment]
Nice, additionally (we already have an issue for that) we should avoid
citizens wandering into water when they are on their wander tasks.
Which often throws them into the water.

2017-05-22 14:16 GMT-03:00 Colton Schlosser <notifications@github.com>:

**Comment by Raycoms** [comment]
I think there are a lot of tweaks we can do with our pathfinding with the
different values (also increasing the priority on using the paths
(stonebrick and gravel).
Unfortunately my laptop says goodbye when I let the pathfinding render.

2017-05-22 14:24 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by cltnschlosser** [comment]
I did increase the priority of paths, but I didn't test it. I can fix that AI task

**Comment by Raycoms** [comment]
But that's actually even a separate issue:
https://github.com/Minecolonies/minecolonies/issues/781

2017-05-22 16:20 GMT-03:00 Colton Schlosser <notifications@github.com>:

**Comment by dawgermany** [comment]
I still have issues with colonists loving to swim even with pathblock alternatives and waypoints in 1.20.1

**Comment by GeneralMine** [comment]
Same here. The citizens have a valid bridge in front of them with waypoints leading towards there. Sidewise detour would be 10 blocks, as they go swimming 10 blocks next to the bridge
