### ISSUE TITLE
Bakers don't do their job

### ISSUE THREAD

**Issue by M7lk** [ldtteam/minecolonies#7554]
Hello, I play in version 1.16.5 and I have this problem that bakers do not work or ask for anything, I created several worlds to see if the problem was from my neighborhood and nothing, the bakers did not work even if I gave him what he needed as fuel, etc.

**Comment by uecasm** [comment]
Please fill in the template when reporting bugs.  But please ask for support on Discord before reporting bugs that aren't bugs.

Because this is not a bug -- the baker works to request, so you either need to request bread in a postbox or in a minimum stock somewhere before they will produce anything, like most crafters.
