### ISSUE TITLE
Crash : PM Description: Ticking block entity  java.util.ConcurrentModificationException [$5 awarded]

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#758]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.3317 or curse 

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

I came back from nether and this happens. It corrupt the world (every try to reload the save gives this very same crash.) I had to edit the world with MCEdit and delete the warehouse entity, and then I was able to load the world (now I have a citizen asking for a warehouse to work with :-)

By the way, what is this delivery man going to do? as of now seems not doing anything apart to see the floor everywhere looking for something...

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by jonabrv1965** [comment]
here the crash log...
[crash-2017-04-03_22.58.51-client.txt](https://github.com/Minecolonies/minecolonies/files/892034/crash-2017-04-03_22.58.51-client.txt)

**Comment by Zoidey** [comment]
Can you right click on the warehouse? if no then try and right click on all the other building to see if you can interact with them and if not you might be having the same issue as me. 
I have two warehouses that I can interact and the only way to is break the warehouse (core) and then place it back down exactly as it was and rebuild and re-upgrade. I haven't done this to my warehouses as I don't fancy moving all those chest full of stuff if I don't have to right now. I have done it with my Town Hall, Miner x1, Citizen Hut, Deliveryman. 
Once I broke the core and place it down and was able to right click to rebuild and then to upgrade they worked just like normal.

**Comment by jonabrv1965** [comment]
Hi Zoidey, remember : I deleted the warehouse entity block with MCEdit (the only way to recover my world)... It happened to me, few weeks ago, that when right clicked the fisherman inventories hut the game crashed, it was reported and fixed... I will try with the rest of inventories, I'll let you now

**Comment by jonabrv1965** [comment]
I was able to recreate this error. Getting tired of that colonist begging for warehouse I ordered my builder to build other one in the exact same place I had in the initial crash, the builder comply....and then...boom, this very same crash right now...

**Comment by Raycoms** [comment]
Can you give us more information? Version used, additional
mods/coremods. It crashed before you accessed it? Playing on server/single
player /lan game?

2017-04-05 14:18 GMT-03:00 jonabrv1965 <notifications@github.com>:

**Comment by jonabrv1965** [comment]
Hi Ray, of course. Here the FML Log where you will find the mods loaded.
I'm in singleplayer, survival...

[fml-client-latest.log (2).txt](https://github.com/Minecolonies/minecolonies/files/900802/fml-client-latest.log.2.txt)

In addition here the last crash log (which is very similar to what I upload earlier here)
[crash-2017-04-05_12.10.49-client.txt](https://github.com/Minecolonies/minecolonies/files/900804/crash-2017-04-05_12.10.49-client.txt)

Let me know if need anything else. I want to help!

**Comment by ProjectGR** [comment]
It happens that I got a very similar issue which if I have read the logs correctly it has something to do with the warehouse.
[latest.txt](https://github.com/Minecolonies/minecolonies/files/936032/latest.txt)

Thing is, this didnt happen initially, I added 17 mods on my pack yesterday and today (~10 minutes of gameplay before the crash) while I was breaking cotton from a farmland near the warehouse (if that matters), I suspect the NPC interacted with the.

**Mods I added since yesterday:**
- mysticalagriculture[1.11.2]-1.5.1.jar
- roots-2-0.015.jar
- Forgelin-1.4.1.jar
- bdlib-1.13.2.7-mc1.11.2.jar
- zerocore-1.11.2-0.1.0.5.jar
- fl-1.0.2.jar
- ExtremeReactors-1.11.2-0.4.5.28.jar
- gendustry-1.6.5.7-mc1.11.2.jar
- mcflux-2.6.1.jar
- refinedstorage-1.4.2.jar
- buildcraft-7.99.0.jar
- rftools-1.1x-5.92.jar
- cyberware-1.11.2-alpha-0.2.9.jar
- extrautils2-1.11.2-1.4.jar
- ShadowMC-1.11.2-3.7.5.jar
- Clipboard-1.11-1.2.1.jar
- ElecCore-1.11-1.7.417.jar

**Some additional info if it helps:**
[fml-client-latest.txt](https://github.com/Minecolonies/minecolonies/files/936143/fml-client-latest.txt)
The intresting part from the log above should be this:
[https://pastebin.com/MuqLsAVp](url)

Also it seems the world has not been corrupted for me.
**EDIT:** It seems the world crashes after about 15 minutes, I thought it had to do with the worker interacting with it but this happened after I fired him. I guess it has something to do with the block.

**Here is both crash reports:**
[crash-2017-04-19_16.39.24-client.txt](https://github.com/Minecolonies/minecolonies/files/936687/crash-2017-04-19_16.39.24-client.txt)
[crash-2017-04-19_20.25.30-client.txt](https://github.com/Minecolonies/minecolonies/files/936688/crash-2017-04-19_20.25.30-client.txt)
