### ISSUE TITLE
Lumber Jack, Miner, Builder and Delivery man. Update on Walls, fences and minecarts Walking bug

### ISSUE THREAD

**Issue by rexrapter1234** [ldtteam/minecolonies#764]
### Minecolonies version

version 1.10.2 or curse X.X.XX

1. Lumber Jack can not axe out all of the logs from a building, if a tree is linked to the building's logs.
2. Only one builder can start to build on building.
3. When canceling a build in the town hall the job is removed from the builder's hut block.
4. Miner can not build a quarry in the roof his quarry
5. Delivery man can delivered items from the warehouse to where they are needed.

Update on a bug: Colonies can walk around Walls, fences and minecarts.

- XXX

### Actual behaviour
 

1. Lumber Jack can axe out all of the logs from a building, if a tree is linked to the building's logs.
2. Two of my builder start to make the same building.
3. When canceling a build in the town hall the job is not removed from the builder's hut block.
4. Miner Start to build a quarry in the roof his quarry
15. Delivery man is not getting item from warehouse.

Update on a bug: Colonies can walk around Walls, fences and minecarts.

- YYY

### Steps to reproduce the problem

1. Make a tree next to a building with logs (add logs to the building if need to join up the building to the tree) and just let the Lumber Jack do this job.
2. Not sure how this happened.
3. Get the builder the start to make a building and the just cancel it in the town hall, then check the build's hut block, the request should still been request in the builder's hut block.
4. Not sure how this happened.
5. Make a town and put items in the warehouse and get same builder to make some buildings, then the Delivery man will walk around, but will not pick up any blocks from the warehouse.

Update on a bug: already reported this bug just adding to it.

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
1. Lumber Jack can axe out all of the logs from a building, if a tree is
   linked to the building's logs.
   -> unfortunately no way to detect this. It is extremely hard to detect a
   tree.
   2. Two of my builder start to make the same building.
   Should not happen in 99% of the cases, will be fixed with another
   feature soon which will assign them manually and more intelligently.
   3. When canceling a build in the town hall the job is removed from the
   builder's hut block.
   -> Patience with this. It sometimes needs a while until the job is
   removed. First the builder has to notice that and then he has to remove
   that.
   4. Miner can not build a quarry in the roof his quarry
   - I bet something went wrong with the ladders? Creeper exploded? For now
   also not detectable.
   5. Delivery man can delivered items from the warehouse to where they are
   needed.
   -> He should actually do that. Do you have the items in the warehouse?
   Did you wait long enough to make sure he doesnt deliver?


2017-04-05 13:42 GMT-03:00 rexrapter1234 <notifications@github.com>:

**Comment by rexrapter1234** [comment]
1. The Lumber Jack is  cutting down a tree next to a building and is also cutting down the building's logs.
2. Okay cool.
3. No normal the builder just stands there waiting and it just gets fixed when the server restart up.
4. Yes I think it may have been a Creeper exploded. Also the Lumber Jack cut down some of the logs in the miner's building too, as well as the farmer's level 4 building's logs.
5 A. I have lots of items in my warehouses. Lots of them.
5 B. I've waited for my delivery mens to Delivery items to any of my builder's huts. I have also checked to see what they are delivering at different times.

**Comment by Raycoms** [comment]
Which version of the mod are you using? The newest on curse?

2017-04-05 14:52 GMT-03:00 rexrapter1234 <notifications@github.com>:

**Comment by rexrapter1234** [comment]
Yes the MineColonies TestPack Version: 0.6.7
Minecraft Version: 1.8.9 (it 1.10.2 but it shows 1.8.9 on  Curse (modded) 
Forge-12.18.3.2221

Yes the new version on curse.

http://i243.photobucket.com/albums/ff156/rexrapter1234/info_zpstx4tn3lb.jpg

**Comment by Raycoms** [comment]
Can you try this here:
https://minecraft.curseforge.com/projects/minecolonies-testpack

2017-04-05 16:15 GMT-03:00 rexrapter1234 <notifications@github.com>:

**Comment by rexrapter1234** [comment]
I updated the the new version of the mod on curse when the last version come out. Which updated 3 days ago. I find the bugs playing on the Official Minecolonies server make by Kostronor. 1_Wissi_1, H3lay.

**Comment by Raycoms** [comment]
Ok, because the newest version is higher than 0.6.7 and its marked as 1.10

2017-04-05 16:35 GMT-03:00 rexrapter1234 <notifications@github.com>:

**Comment by rexrapter1234** [comment]
Yes I'm on the 1.10.2 version of the mod on the server.

**Comment by Raycoms** [comment]
Okay. The deliveryman works for me on the server. If you have the item the
worker requires in the warehouse the deliveryman should, eventually,
deliver it.

The case of the builder not finishing it accordingly if you terminate the
work order prematurely will be content of my tests later these days.

2017-04-05 17:03 GMT-03:00 rexrapter1234 <notifications@github.com>:

**Comment by rexrapter1234** [comment]
ok thanks

**Comment by marvin-bitterlich** [comment]
closing this for now
