### ISSUE TITLE
Miner likes to keep in valuable ores instead of depositing them

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7732]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The miner will occasionally deposit every ores to be taken to the smelter

## Actual behavior

He keeps the ore until they decided to dump their inventory from being too full, and it is too long of a process until that happen, the smelter would just asking for ores and not receive any single one.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Okay, you took it too far. You're now banned from making issues on this repository. This, like all 100 other issues you make are not issues. They are designed this way on purpose. Just because you got a "subjective feeling" sth should be "slightly faster/slower/different" doesn't imply that it should be done this way in the first place. There is a feature request repository for exactly this reason and I asked you numerous times to request those things there.

**Comment by uecasm** [comment]
It's also good to discuss things on Discord first, especially when you're not sure if something is intended to behave like that or not.  (Or even when you think you're sure.)
