### ISSUE TITLE
Clock not recognized by Builder

### ISSUE THREAD

**Issue by acdman87** [ldtteam/minecolonies#7913]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.278-RELEASE.jar

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue.  When Building Stage 4 builder, the builder requests a Vanilla Minecraft clock, but doesn't recognize that he has been given one.  When it is either in his inventory or in the warehouse.  Thus preventing advancement to next level in the building of buildings.  I am using Medieval Oak style.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Disable the quark change.

**Comment by acdman87** [comment]
Thanks, I will have the server owner do so and see if that works.

**Comment by acdman87** [comment]
How?  the only change I can see we have disabled and it still doesn't work...

**Comment by uecasm** [comment]
"Compasses work everywhere" is the Quark setting that needs to be disabled on the server.  After that, you need to craft a new clock/compass -- the existing ones still won't work.

If you enable advanced tooltips (F3+H) you can see if it shows "NBT" on the item or not.  A normal clock/compass has no NBT; if the NBT is present and non-zero then it will not work.

**Comment by acdman87** [comment]
![image](https://user-images.githubusercontent.com/97262769/148489166-2ec41a68-8f1a-48a1-8b3d-263203822b1e.png)

**Comment by acdman87** [comment]
Still doesn't work, but what is this NBT tag?

**Comment by uecasm** [comment]
Was that a freshly crafted one?  If so, it's possible some mod other than Quark is adding the tag (or it's still Quark, but the option wasn't disabled in the right place).

**Comment by acdman87** [comment]
We did get quark disabled, and this is a new clock...  Three in fact.

**Comment by uecasm** [comment]
Well, a working clock will not stack with a non-working clock 😉 

Try putting the clock in the first slot of your hotbar, and then enter the following command (this probably requires OP if you're on a server):
```
/data get entity @p Inventory[0]
```
This will display what the offending tag is (among other things).

**Comment by acdman87** [comment]
![image](https://user-images.githubusercontent.com/97262769/148491174-4637738c-7d99-4611-bc92-4c5f559c0632.png)
Perhaps it wasn't fixed after all

**Comment by acdman87** [comment]
So, even with the server and client both setting "Compasses Work Everywhere" = false we still get the same issue.

**Comment by uecasm** [comment]
It is likely that the server must be shut down, the config changed, and then restarted (in that order) to make the change actually take effect.

**Comment by acdman87** [comment]
Ok, it works now after another restart and check.  Thanks for your time!

**Comment by NJM1564** [comment]
Can't the villagers be set to ignore NBT on clocks?

**Comment by uecasm** [comment]
> Can't the villagers be set to ignore NBT on clocks?

It is possible (and was even implemented, briefly), but it's considered risky since it might result in data or resource loss or otherwise consuming items not intended for that purpose (for example, some mod might add clocks with diamond-encrusted frames that are only distinguished from regular clocks by their NBT, and you probably don't want one of those to get used).

We consider it a bug in Quark that it uses this particular method (modifying the actual clock item) for its feature; but an easy workaround exists by disabling the feature.

**Comment by NJM1564** [comment]
I think the likelihood of that happening is rather low. And easily recognized as what is happening.
Compared to getting stuck while making a building that is used commonly. And no clue as to really know what's going on
How many will simply never think of going here? What's the odds of anyone making a modded clock?
I'd rather lose all the diamonds everywhere rather than banging my head on an unknowable problem.

**Comment by MotionlessTrain** [comment]
You may have no problems losing diamonds, if a mod would implement a diamond encrusted clock like that, but not everyone would like that.

What's more, this is the same for enchantments as well. So a builder may suddenly use your overpowered enchanted bow to put it as decoration in a building somewhere, instead of a new bow which could have easily been crafted by the fletcher, when the builder would not care about NBT anymore
