### ISSUE TITLE
Colonists in minecarts getting stuck when going in different directions

### ISSUE THREAD

**Issue by RustyNova016** [ldtteam/minecolonies#7942]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.351-ALPHA.jar
- Structurize Version: structurize-1.18.1-1.0.323-ALPHA.jar
- Related Mods and their Versions: -

## Expected behavior

The colonists phase through each other on the rails when they go in different directions

## Actual behavior

The colonists block each other

![image](https://user-images.githubusercontent.com/50844553/149630289-018b0f09-07a6-4bbe-91d6-527ace230845.png)

## Steps to reproduce the issue

Place a long railway and have two colonists going in different directions

### Logs

- latest.log: https://gist.github.com/RustyNova016/1b97e861424b0938777279885e0ff760
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Strange, I saw this working fine already. Any mod that maybe alters minecart behaviour?

**Comment by kedamono** [comment]
Looking through your log file, you have duplicate mod versions running:
BiomesOPlenty-1.18.1-15.0.0.94-universal.jar & BiomesOPlenty-1.18.1-15.0.0.97-universal.jar.

Also, I see you're running Balm, which allows you to use Fabric mods. It might be one of those or Balm causing the problem.

[Edit: I mistook two different mods to be the same mod. Sorry]

**Comment by Maachiavelli** [comment]
Here are the mods I am running, shown in the screenshot.  
I am running into this same issue, but I have more details.  I have noticed that they only get stuck on each other if at least one of them is going relatively slow.  I cannot say exactly what speed, don't exactly know how to measure that.  But lets say you have two colonists heading toward each other and they have both been on a rails for a few seconds and are moving near top speed.  These colonists will clip through each other with no issue.  But lets now say one of them has only jumped onto the rail in the last second (or is travelling uphill) and is going slow, then BOTH colonists get stuck on each other, regardless of how fast the fast one is travelling.  And of course then, if both are slow, they both get stuck too.  They only clip through each other if they are both "fast".  Again, I don't know how exactly to measure their speed so that's all I can really say.

Oh and of course if a colonists is stuck, they have a "slow" speed of 0 kph of course, leading to every single other colonist who rolls up to them also gets stuck and it causes these horrible pile-ups, really breaks the Fortress schematics...

![image](https://user-images.githubusercontent.com/73868883/149728327-bee67e81-d41f-4b60-8b7b-96ada76da526.png)

**Comment by lazystudent3** [comment]
Hi guys,
I think i got similar problem. I did try rails early on and they were blocking each other like that so i decided to get ride of them. 
Here is screen where I put some rails just to show the problem because i dont use rails in my town (for now).
PS : I added Building Gadgets from Direwolf to the pack as well as Faithful texture packs. 
![2022-01-17_15 48 16](https://user-images.githubusercontent.com/74244333/149791691-3f771f30-9657-4a2f-86b1-23b9d5073e1d.png)
![modpackname](https://user-images.githubusercontent.com/74244333/149791697-caeab082-4feb-40bb-b9f1-75d1d061d6a9.PNG)

**Comment by Bonzai2022** [comment]
> Looking through your log file, you have duplicate mod versions running: BiomesOPlenty-1.18.1-15.0.0.94-universal.jar & BiomesOPlenty-1.18.1-15.0.0.97-universal.jar.
> 
> Also, I see you're running Balm, which allows you to use Fabric mods. It might be one of those or Balm causing the problem.
> 
> [Edit: I mistook two different mods to be the same mod. Sorry]

And i'm having the same Problem using the official Mincolonies Modpack, where balm is included.
I don't think that's the issue.
It's annoying... :(
