### ISSUE TITLE
Bug: Pregenerated Houses Sleeping Error

### ISSUE THREAD

**Issue by LittleLyla** [ldtteam/minecolonies#7962]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.355 Alpha
- Structurize Version: 1.0.326 Alpha
- Related Mods and their Versions: 

## Expected behavior
Pregenerated houses being claimed resulting in colonists sleeping is the expected behavior. Without the need of any other influence.

## Actual behavior
Pregenerated houses being claimed result in colonists NOT sleeping UNLESS the house is repaired, regardless of pre-existent damage or not. Original conversation: https://discord.com/channels/139070364159311872/915411448342118441/933574857134850140

## Steps to reproduce the issue

1. Find a pregenerated colony with a house (also might effect original townhall).
2. Claim a house.
3. Assign house to an initial colonist.
4. Wait until they attempt to go to bed.
5. Follow them into the house to watch them stand near the bed without sleeping.

### Logs

N/A

### Notes
N/A

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Looks like the reactivate option triggers part of the building code (it creates the internal building data and sets it to the right level, and adds construction tape) -- but doesn't remove the construction tape and doesn't register special blocks from the schematic (e.g. beds, racks).

Both of these are fixed when you follow up with a repair (which is a good idea anyway since worldgen can leave the building incomplete) but it should really treat it as a normal building completed process anyway.

**Comment by Raycoms** [comment]
We'll have a small update to the worldgen colonies soon, I'll add some text in the claim text to tell the player to repair or upgrade

**Comment by Raycoms** [comment]
adjusted config
