### ISSUE TITLE
[BUG] Minimum stock is showing air instead of the items selected before update

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies#8140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

494

### Structurize Version

352

### Current Behavior

before update had a slection of items in minimum stock in the warehouse, after update they all show "Air"

### Expected Behavior

items would be same after update

### Reproduction Steps

update?

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SivartMcDorf** [comment]
on top of this many players warehouse blocks have disconnected from their colony the couriers can still use them but the players can't click on them.

**Comment by Inomutso** [comment]
I am having the same Issue, as SivartMcDorf reported.

In my 1.18.1 Colony, I found this issue three days ago, and I had to crash down my Level 5 Medieval Spruce Warehouse.
Then one of my Builders had to build up a new Warehouse, and it was ok for 1 day
Now, I have the same again, the Hut Block is broken, the Warehouse is being used, but no sorting, no assigning new Couriers

I think, this Issue came in with minecolonies-1.18.1-1.0.479-ALPHA.jar

Actually I am running Minecolonies-1.18.1-1.0.494-ALPHA - Structurize-1.18.1-1.0.352-ALPHA on forge-1.18.1-39.1.2

**Comment by MotionlessTrain** [comment]
Could either of you attach a latest.log?

**Comment by Raycoms** [comment]
hotfix pushed
