### ISSUE TITLE
Cook cannot recursively craft recipes that involve pam's tools

### ISSUE THREAD

**Issue by Darinth** [ldtteam/minecolonies#8337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.696-ALPHA

### Structurize Version

1.0.392-RELEASE

### Related Mods and their Versions

1. Forge version: 36.2.24
2. Pam's harvestcraft versions:
    - pamhc2crops-1.16.3
    - pamhc2foodcore-1.16.3-1.0.2
    - pamhc2foodextended-1.16.3-1.0.4
    - pamhc2trees-1.16.3-1.0.1

### Current Behavior

Attempting to craft more than 1 item that uses a pam's harvestcraft tool (such as the bakeware) that would require the crafting other other parts fails to find any parts of the recipe. Crafting small quantities has weird issues, will detail them below in the anything else section. Crafting works for single-step recipes, but as soon as you craft items that require crafting other items *and* it involves a pam's harvestcraft tool the crafting system cannot find the parts in the hut inventory/racks.

### Expected Behavior

Attempting to craft pam's harvestcraft foods that require multiple steps works. It queues up all of the items necessary in the chain and crafts each one to it produces the final item.

### Reproduction Steps

1. Disable roasted peanuts as food at the restaurant
2. Teach the recipe to make blackberry jelly to the restaurant
3. Teach the recipe to make peanut butter to the restaurant
4. Teach the recipe to make blackberry jelly sandwich to the restaurant (make sure you teach them the version that uses peanut butter)
5. Place all of the components necessary to craft a stack of blackberry jelly sandwiches in the hut inventory
    - 64 bread
    - 64 peanuts
    - 64 sugar
    - 64 blackberry
    - 1 grinder
    - 1 sauce pan
    - 1 cutting board
6. Place down a request a stack of blackberry jelly sandwich from a postbox
7. Cutting board and bread required for initial recipe are not found.

### Logs

https://gist.github.com/Darinth/79ea12d26cf43ba2dafb66ec71e14849

### Anything else?

The issue was originally discovered dealing with a much larger modpack I put together. I was having issues with the restaurant not finding stuff needed to craft the pam's harvestcraft recipes. After testing in a solo world, I was able to craft recipes (including those from pam's) that didn't use tools. After talking with people in discord who said they were able to craft I thought it might be interference from another mod.

I setup a pack with just minecolonies, pam's, and JEI and used a datapack to also create some recipes for minimum reproduction and to rule out that there was something weird going on with the recipes for pam's itself. I created a datapack that allowed me to directly craft cooked beef into cooked mutton, cooked mutton into cooked chicken, cooked beef + bakeware into cooked mutton, cooked mutton + bakeware into cooked chicken. Super simple recipes that I could stick small amounts of stuff into the restaurant to test crafting.

When I teach the cook the recipes to craft beef into mutton and mutton into chicken and request chicken everything works as expect. Cook can make chicken from beef.

When I teach the cook the recipes to craft beef + bakeware into mutton and mutton + bakeware into chicken, I can craft craft mutton freely from beef and bakeware in any quantity, once I have mutton I can craft the mutton into chicken in any quantity. But if they do not have mutton, cooking chicken is buggy at best. Any large quantity will not craft under any circumstance. It fails to find anything. Not even the steak that is in the inventory. It in fact wants to craft more steak or will request it from the warehouse.

Small quantities can be crafted after multiple attempts. If I make a request for chicken equal to the number of bakeware I have (or less) the first attempt fails. It thinks it doesn't have enough bakeware. If I then cancel the first request and make another one, it now knows it has enough and will craft the chicken. This cycle repeats. If I let the first set finish and request another... it once again thinks it doesn't have enough bakeware but canceling the first request and making a second request allows it to find the bakeware and craft it.

If there's anything else I can do to assist I am happy to do so. I don't think you'll have repro issues, but if you do I'm happy to hop on discord to show it in action. I'm on the minecolonies discord as Darinth.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Related to ldtteam/minecolonies-features#641 (though a tag is not the right way to do that).

**Comment by Sandriell** [comment]
I feel like this is a much larger issue than simply failing to recognize the pam's utensils. The cook often fails to recognize any ingredients they already have.

Some pictures to show...

Here you can see the cook needs 128 eggs and is requesting 64. Same with the request for 64 sugar as well.

![2022-04-19_01 37 21](https://user-images.githubusercontent.com/10704907/166985699-81dba6f9-ba0f-48f9-b8bc-3447d43a4d69.png)

However there is already 192 eggs and 64 sugar in the hut's inventory,

![2022-04-19_01 37 16](https://user-images.githubusercontent.com/10704907/166985718-7fe1f3f1-7380-4a75-a2b0-23fd624e6f93.png)


And another time showing another request for 128 eggs, but now it is failing because all the eggs are gone from the warehouse
![2022-04-19_01 52 24](https://user-images.githubusercontent.com/10704907/166985734-a2229e56-0ad6-4eee-b31e-e9e9bf3eeb8d.png)

Because they have built up in the hut's inventory and are being ignored.. there are 298 eggs in the hut's inventory.
![2022-04-19_01 52 16](https://user-images.githubusercontent.com/10704907/166985740-fa28a521-3645-4281-acfe-1d0ba7d7a708.png)

**Comment by Darinth** [comment]
So there may be a relation between this and https://github.com/ldtteam/minecolonies-features/issues/641. Though the description there doesn't quite seem like a match. I can craft an unlimited amount of items, as long as there's no need for crafting sub-items. So I can craft an unlimited amount of blackberry jelly from sugar and blackberry's with just 1 sauce pan. I just rechecked and crafting 256 with a single tool. No issues. It's not until you try to craft an item and you're missing something and it needs to craft sub items... and that that point everything falls apart. It seem like the mod is actually designed to handle these items, but develops an issue once recipes that require crafting sub-recipes show up.

Sandriel... I am not able to reproduce your issue. As long as the recipe doesn't involve pam's tools, I can craft any recipe including doing crafting that requires crafting sub-items. Consistently, without any issue. :( I am wondering if there's something weird withthe recipes you've selected/created/are in the modpack, since that's also not the standard pam's harvestcraft recipe (at least in 1.16.5). Pumpkin bread is made from pumpkins, dough, and bakeware. Dough is made from salt, water, flour, and a mixing bowl. Possibly interference from another mod? I reduced all of the way down to a minimal set of mods to reproduce the issue.

**Comment by Sandriell** [comment]
The issue with ignoring ingredients doesn't always occur, and seems most likely to occur when the job gets held up for some reason. Say if the cook gets most of what he needs delivered right away and then ends up having to wait awhile for something- and then by the time it shows up he has forgotten about the stuff he already has. Probably similar to having a multi-step job like you have done and forgetting about the things he has when he gets to the later steps. Try making him wait a MC day or two for one of the ingredients and then see if he is still successful.

Also the reason my recipes are different is because I edited them manually myself to remove the pam's tools, hoping to get around this issue.

**Comment by Ruvanal** [comment]
I have run into this problem with Pam's Harvest craft recipes also on a server with a friend.  A work around that we have found for this is to take the utensil out of their inventory or racks and then putting it back into the control block inventory.  This usually results in burst of crafting to finish multiple amounts of the crafting.  It seems that they do no recognize that the utensil is returned to them after its done a crafting step.  

Early on we also encountered a situation where they duplicated a skillet on 2 occasions but could not consistently duplicate that effect.  We have not encountered this duplication of items for a couple of weeks of play since then.

**Comment by Darinth** [comment]
Yup. I used the same work-around (I actually just put them back in storage), however this is a work-around requiring manual intervention and prevents one of my goals of being able to have the warehouse keep certain quantities of certain foods in stock automatically. It's not automatic if I have to regularly run over to the restaurant and take all of the cooking utensils from the citizens and put them back in their storage.

**Comment by Raycoms** [comment]
This should be fixed afaik
