### ISSUE TITLE
[BUG] <Placing Level 5 Hut Blocks>

### ISSUE THREAD

**Issue by Dylbert93** [ldtteam/minecolonies#8585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.1-1.0.982-ALPHA

### Structurize Version

1.19.2-1.0.437-ALPHA

### Related Mods and their Versions

Forge - 43.1.2
Block UI - 1.19-0.0.60-ALPHA
Domum Ornamentum - 1.19-0.0.60-ALPHA
Multi-Piston - 1.19-1.2.16-ALPHA
Ambient Sounds 5 - v5.2.1_mc1.19
Balm - 4.5.3
Biomes O' Plenty - 1.19.2-17.1.1.150
Bookshelf - 1.19.2-16.1.4
Corpse - 1.19.2-1.0.0
Crafting Tweaks - 1.19-15.1.0
Creative Core - v2.8.4_mc1.19.2
Enchantment Descriptions - 1.19.2-13.0.1
Explorer's Compass - 1.19.2-1.2.4
Harvest with ease - 1.19.2-4.0.0.0
Inventory Profiles Next - 1.19-1.6.5
Jade - 1.19.1-forge-8.0.1
Journey Map - 1.19.1-5.9.0beta2-forge
JEI - 1.19.2-forge-11.2.0.256
Kotlin for Forge - 3.7.1-obf
Mouse Tweaks - 1.19-2.23
Nature's Compass - 1.19.2-1.9.7
Terra Blender - 1.19.2-2.0.1.125
When Dungeons Arise - 1.19-2.1.51-beta
William Wythers' Overhauled Overworld - 3.1.7+1.19.2

### Current Behavior

While placing a decoration for Medieval Birch, the one that lays out your university and library it places level 5 Hut
![2022-08-26_11 15 34](https://user-images.githubusercontent.com/111447206/186798195-4ef274f2-a37b-4994-8cda-3576cfda686a.png)
![2022-08-26_11 15 47](https://user-images.githubusercontent.com/111447206/186798201-6e489007-a40a-4449-a360-a29dc66fe553.png)
![2022-08-26_11 15 54](https://user-images.githubusercontent.com/111447206/186798204-06d8c9eb-ffc6-4338-9262-57a903bee9cf.png)
![2022-08-26_11 16 14](https://user-images.githubusercontent.com/111447206/186798207-b2090e82-04bb-4b46-926b-777e95017f65.png)
s

### Expected Behavior

Place level 0 Buildable huts

### Reproduction Steps

Have Medieval Birch Style
Go to Decorations
Misc
Place universitylibrary

### Logs

https://gist.github.com/Dylbert93/5e9d2359ef91cea574c60ec185cb1248

### Anything else?

Posted in #schem-bugs and Moobien said its a proper bug

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Tracing this, it looks like the child building originally gets the `education/university1.blueprint` path as expected.  And then because it doesn't have the "invisible" tag (which it _shouldn't_) it overrides the path to `decorations/misc/university0.blueprint`.  Then creates the building as a fully-constructed level 1 and removes construction tape, then places fresh construction tape and for some undiscovered reason starts trying to load the `decorations/misc/university5.blueprint` instead.  So it's all kinds of confused.

Edit: ah, the level 5 requests are from the neighbour renderer, because the build tool preview for the decoration is still open.  Of course, that's looking in the wrong folder too.

**Comment by Raycoms** [comment]
fixed
