### ISSUE TITLE
[BUG] [Server thread/ERROR] [structurize/]: Error loading blueprint:  java.io.FileNotFoundException: null

### ISSUE THREAD

**Issue by daniilmeranov** [ldtteam/minecolonies#8622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1004-ALPHA

### Structurize Version

1.0.443-ALPHA

### Related Mods and their Versions

Forge 43.1.1
blockui-1.19-0.0.61-ALPHA
domum_ornamentum-1.19-1.0.60-ALPHA-universal
multi-piston-1.19-1.2.16-ALPHA
exoticbirds-1.19.2-2.6.0
FarmersDelight-1.19-1.1.2
jei-1.19.2-forge-11.2.0.256
journeymap-1.19.1-5.9.0beta2-forge
NaturesCompass-1.19.2-1.9.7-forge

### Reproduction Steps

Caledonia build style. Miner.

### Logs

https://gist.github.com/daniilmeranov/9d493faf37818965eebb384c8033bf5c

**Comment by MotionlessTrain** [comment]
It looks like the needsFallBack function, which finds out whether the style defines its own mining nodes, has a flaw in it which causes the log spam:
https://github.com/ldtteam/minecolonies/blob/6b19cccfc48a03a68539e800d734fab77a7e8693/src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java#L349-L352
The StructurePacks#getBluePrint function throws a FileNotFoundException instead of returning null, so this function would probably never return true (which is the expected outcome in case of Caledonia)

**Comment by Raycoms** [comment]
It throws an error in the log, but returns null afterwards

**Comment by Raycoms** [comment]
Works fine, just a bit spammy, I'll add an override to those methods that don't log on null
