### ISSUE TITLE
[BUG] Gates Not Accepting Redstone Signal

### ISSUE THREAD

**Issue by Raulwicke** [ldtteam/minecolonies#8897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1183

### Structurize Version

1.19.2-1.0.472-BETA

### Related Mods and their Versions

1. Forge Version: 43.2.3
2. BlockUI Version: 1.19-0.0.64-ALPHA
3. Domum Ornamentum Version: 1.19-1.0.76-ALPHA-universal

### Current Behavior

Placing a redstone torch, redstone signal, lever, etc. on any block surrounding a gate does not trigger the gate to open or close.

### Expected Behavior

The Gate should react to a redstone signal.

### Reproduction Steps

Place a gate (any size)

### Logs

https://pastebin.com/fXKywpgz

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Currently Forge 43.1 is the most preferred version, and in a test environment with that version it's working fine for me.  I have not double-checked it with Forge 43.2.

Can you reproduce the problem in an instance with only Minecolonies and dependencies, not other mods?  Last time there was a gate redstone issue reported, it was due to another mod adding invisible redstone signals around the player.

(Side note: there is one interesting redstone behaviour with gates, that I'm not sure if it's intended or not: if you toggle a signal in the lower half of the gate or below, it will open/close on every toggle.  If the signal is at the side of the top block or above the gate, it will open/close on every second toggle.)

**Comment by Raycoms** [comment]
I believe the weird behavior comes from the gate blocks relaying the redstone signal to the neighboring blocks too. We should probably prevent this

**Comment by Raulwicke** [comment]
Using the same configuration on a clean creative world with no other mods, the issue is not reproducible.

I also tested on a creative world with all mods installed, and the issue is not reproducible. It only appears to occur on the server.

**Comment by Raycoms** [comment]
Checked on this and it actually works as intended. The gate can be triggered from the sides and the bottom just fine

**Comment by Raulwicke** [comment]
This issue still occurs, even on the most up-to-date minecolonies version. The issue only occurs on my server. For some reason, that gate is not updating correctly between player instances, and it looks like it can't recognize a redstone signal because of it.

**Comment by Raycoms** [comment]
Does it occur on a clean server?

**Comment by Raulwicke** [comment]
I have no way of testing that as I only have the one server.

**Comment by Raycoms** [comment]
Tried in a local server instance, cant reproduce either. So it must be another mod causing it
