### ISSUE TITLE
Pirates have not spawned in ages  

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/minecolonies#9030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.1305.alpha.jar

### Structurize Version

18.2-1.0-424-alpha.jar

### Current Behavior

we are not seeing pirates anymore.  My colony has a lot of coast and we used to see them often. 
My husband's colony also used to see them often and no longer does.   We get raids every 12-16 game days and that equates to almost one a real-life day in each colony,  it's been weeks to months we have not seen pirates.  They were almost every raid in my colony which is larger and has more coast and every 2-3 raids in my husbands colony 
![2023-03-26_19 41 20](https://user-images.githubusercontent.com/121142637/227812391-52c2a58c-affb-41f9-bd26-6216f47a268c.png)
![2023-03-26_19 40 41](https://user-images.githubusercontent.com/121142637/227812394-97f1a1fc-cc31-4701-a34c-6040104e03cb.png)
![2023-03-26_19 43 27](https://user-images.githubusercontent.com/121142637/227812395-67b4aa7a-576d-4af7-b5de-66bb5997a389.png)

### Expected Behavior

 They said they would be back and we expected them to keep their word! 

### Reproduction Steps

 build a colony on a beach and play for a really long time 

### Logs
https://gist.github.com/anastasia590/89dc511f8aa888df01c2f3e2edb6c091

 
### Anything else?

I cannot expand any further into the beach area,  the buildings have not changed to cause less raids in this area of the colony.  
  I still get beach raids but they are only mummies,  I get amazons and barbarians elsewhere in the colony.   I'm in the jungle and don't expect norsemen but my husband's colony is in a plain near a snowy mountain and he's never seen norsemen ever.

**Comment by Talyda** [comment]
Just gonna add on to this, there has been at least half a dozen people mention this over the past month or so, in both 1.18 and 1.19 seems to be just pirates
Seuzz#9186  on discord has made a test colony on an island, and using the raid commands, can get all raids to work except pirates.  They've done a lot of testing actually if you want to search their messages

**Comment by sweg4552** [comment]
I can also attest to this. my colony is on an island and of the almost 100 raids so far,  I haven't gotten a single pirate raid. It'll always find the smallest slither of land far away from my island to spawn a barbarian raid. I play on a server so can't test the command but i'm starting to think this is an issue with raid spawn mechanics rather than bad luck

playing on 1.19.2-1.0.1316-ALPHA

**Comment by Knaxia** [comment]
I'd like to add my voice to this. I'm thinking that it's going a bit more than just pirates at this point.

I have a colony started since the 1.19.4 came out, I keep the thing updated since the start as much as I can. I run strictly with the mods for minecolonies, with JEI, JourneyMap and World Edit.  Nothing else. I run on a personal dedicated server.

Currently on 1.19.4-1.0.1411-ALPHA (I haven't had time to grab today's update)

My colony is half in plains, half in a sparse jungle, with a big river going north, and a large ocean to the east. 
![image](https://github.com/ldtteam/minecolonies/assets/73440864/c48e32a1-6e5e-406f-b763-f84b5d30a1e8)

Now this colony was started on March 29th, 2023. I'm now at 60 citizens, with 27 guards total, most of my buildings are level 4, with some 3 leftovers. The colony is well over 100 days old.  Since the start, I've only ever got Barbarians; never got anything else. I would have suspected some pirates with the amount of water before it was colony border claimed to the north, or even now in the ocean right to the east. Same with Amazons, it's more jungle than plains at this point, and it's always been barbarians spawning there.

Now when I did a colony in 1.19.3, before the official 1.19.4 came out, I started a colony in a Taiga, and in the short time that colony existed, I had Mummies twice with no desert near by, Amazons once with no jungles either and many norsemen (now that's normal) and some barbarians. 

Now I went to test into single player in 1.19.4, but using the raid command since I didn't want to wait so long for nothing, in a random colony by the edge of the sea, with some mountains, and plains, I did get norsemen at the 1st time, but then only barbarians, Now note it was using commands to spawn raids, without being specific to which kind. So I'm very much inclined to say that the current natural spawn system for raid type seems to be broken.  I'm not sure if it's the biome detection that's wrong, since even in 1.19.3 I had mummies and amazon in the middle of a taiga only area, or something else.

**Comment by DSMister** [comment]
Gonna add on here:

One side of my colony is entirely water. I've had roughly 70-80 raids, and none of them have been pirates. Even in my server, where over 50 people have played so far, no one has reported pirates, even the ones who are essentially waterlocked. For those who don't have any land for raids to spawn, they actually don't ever get raids at all.

**Comment by Jinotad** [comment]
Doing the underwater style on the Patron server.  So far out of all my time playing, I've only had 3 barbarian raids spawning on some ice near my colony out of my entire time on the server. Never had any ship raids spawn.

minecolonies-1.19.2-1.0.1541-ALPHA.jar
structurize-1.19.2-1.0.492-ALPHA.jar

![2023-07-12_21 11 42](https://github.com/ldtteam/minecolonies/assets/85356635/d1a7ad58-e512-4664-9741-1eca8df500a4)
