### ISSUE TITLE
[1.11.2-0.7.683] Delivery failing to hand off item

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#913]
### Minecolonies version

1.11.2-0.7.683

### Expected behavior

- Recipient actually gets the requested item 

### Actual behaviour

- A worker calls for a tool (in my case the lumberjack & fisher)
- I watched the deliveryman actually get the item have go to their delivery phase only for the item to disappear on handoff

**Comment by ziocho** [comment]
I'm also having this issue as well on **1.11.2-0.7.777** single-player!

**Expected behavior:**

Deliverymen taking requested tool from Warehouse and delivering to intended worker.

**Actual Behavior:**

Any worker that calls for any tool (multiple calls from Builders, Lumberjacks, Fisher, Guards for axes, shovels, bows, hoes) doesn't receive the tool despite producing over 30 of each and placing in warehouse. The deliverymen will take the requested item from the Warehouse, walk to the intended recipients' working hut and... the item disappears. The item is no longer in the deliveryman's inventory, and not in the hut's inventory nor the intended worker's inventory.

**Comment by marchermans** [comment]
This seems to be in issue with inventories.
I rewrote that system in the last couple of weeks and will check it out.

Maybe i can find something,

**Comment by xavierh** [comment]
Pretty sure is has been fix with https://github.com/Minecolonies/minecolonies/pull/929

**Comment by xavierh** [comment]
@wilsondgonzales this should be fix in the last jar I sent to you, could you confirm ?

**Comment by wilsondgonzales** [comment]
@xavierh after using the second jar that you gave with added logging, I tested my lumberjack by taking his axe. On the log, it shows he's requesting the tool and ingame, the deliveryman does bring the axe to him but the handoff doesn't happen and the item is lost. Here's the same log from #915 that this has happened as well https://paste.ee/p/kUUK5
