### ISSUE TITLE
[BUG]One guard appears in multiple locations simultaneously and keep stationary even he dead

### ISSUE THREAD

**Issue by xfgj** [ldtteam/minecolonies#9687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.332-BETA

### Structurize Version

1.19.2-1.0.661-RELEASE

### Related Mods and their Versions

1. Forge version:1.19.2-43.3.5
2. Block UI version:1.19.2-1.0.127-BETA

### Current Behavior

![image](https://github.com/ldtteam/minecolonies/assets/58296904/e4b2cdf3-0b56-42cc-b6b8-d5671deee61b)
![image](https://github.com/ldtteam/minecolonies/assets/58296904/44ad2d47-d06d-4b12-bc64-b74d97e1d304)
![image](https://github.com/ldtteam/minecolonies/assets/58296904/4c5fa4d0-513e-4b8d-89da-6f71beb3532c)
![image](https://github.com/ldtteam/minecolonies/assets/58296904/6c0bbdd5-a3fb-4546-b3bf-bc40035f00fa)
The guard appears in multiple locations simultaneously and keeps stationary, and I can't hurt it. It won't disappear Even when I use /kill command.

### Expected Behavior

I hope it can disappear and this bug won't happen again.

### Reproduction Steps

I have no idea about how this happens.

### Logs

https://gist.github.com/xfgj/6588d82904a0162310faa20f8b2c7d65

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by LordCorellon** [comment]
Had this issue myself, it was caused by a corrupt colony file and only deleting and rebuilding the colony fixed it (For myself).

In my case what happened is that Citizen ID: 6 was corrupted and whatever citizen was in this entry would start spawning a "clone"   each time the server restarted.   It would generate duplicate entity ID's on in the server log for each duplicate.

Unfortunately killing the citizen didn't work as whatever citizen next got the ID of 6 would start exhibiting the same behaviour.  

I had had chalked it up to a file corruption or when the server shutdown without saving properly as it never reoccurred.

**Comment by Raycoms** [comment]
This can actually happen because of minecraft entity management. Restarting or reloading the affected chunks fixes it.

**Comment by LordCorellon** [comment]
@Raycoms In my case it was not solved by restarting the server, reloading the chucks or even installing a mod that would remove the duplicate entities.

I went so far as to kill off all citizens, reload the server until all entities were reported as removed and there were no entities visible and then start repopulating the village, as soon as ID 6 was a assigned duplicates started appearing again.

As I said I can't reproduce as after deleting the village and rebuilding it it never occurred again but just wanted to comment that a restart/reload did not correct, even deleting the colony itself didn't correct it unless I deleted the corresponding colony file from the server.  Even if I deleted the colony and reloaded it with the backup command it would reoccur as soon as Citizen 6 was populated

**Comment by TwoPointInfinity** [comment]
Having the issue on my server too. The duplicate is actually many many many duplicates in 1 spot. So many it brought down my fps from 190 to 10.
![2024-01-20_15 10 55](https://github.com/ldtteam/minecolonies/assets/7976722/a4c1b843-8b16-4da5-9dd8-5dec88536df9)
![2024-01-20_15 10 48](https://github.com/ldtteam/minecolonies/assets/7976722/4be99771-4861-43fc-b812-f3840da8efe3)
Restarting the server doesnt help. Teleporting the citizen doesnt help, reloading the citizen doesnt help. I have tried /kill all entities in the radius of its cordinates, but they dont exist some how. Although this entitiy is a duplicate of the original, it has a different UUID because it is somehow REAL ENTITY. I doubt this is a vanilla bug as its never happened with villagers or pets or any of that nature in vanilla, its seemingly unheard of. But when i google'd minecolony citizen duplicate many tickets of this issue showed up. im sorry to say this is still, after previous attempts to fix it, a bug in minecolonies. 
If a fix cant be easily added to stop this from happening i would love a way to remove them for now, or a way to reload every colony citizen. Or rescarn the entire colony. I dont know. But its making it unplayable. 

Please re-open a ticket about this duplication issue as many people talk about it here in the minecolony issues page. If the issue that minecolonies is running into is an issue because of vanilla minecraft's entitiy management, maybe we can find another way. a way to manage the entities via 3rd party, or figure out how minecraft's entity management works for minecraft but not for minecolonies.

**Comment by TwoPointInfinity** [comment]
A Sad Day Indeed.
After thorough testing I exhausted all my other options. With a heavy heart i must inform you all that Eduardo G Johnston took the great staircase to the graveyard. 

After Eduardo was settled 1 meter under, the server was restarted. At last, after the restart all the duplicated of the bugged knight were removed. Eduardo was the first citizen to die and is hopefully the last. Good luck on fixing this issue and hopefully Eduardo wont have to make any new friends who share this tragic ending.
