### ISSUE TITLE
(BUG) Citizens Disappearing in LAN world, even after restarting multiple times

### ISSUE THREAD

**Issue by BlaccPanter** [ldtteam/minecolonies#9898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.546-BETA.jar

### Structurize Version

Structurize: 1.20.1-1.0.718-BETA

### Current Behavior

Me and my brother play in a LAN world. Suddenly when I went back into my colony all my colonists disappeared. We both restarted minecraft, but the issue kept going. After a few restarts my colonists were back, but his colonists were gone. At the end, after restarting for more then 5 times either one couldnt find the colonistst. They weren't visible, recalling didnt work, but they still did show in the townhall as citizens.

### Expected Behavior

That my colonists are visible and can be interacted with, all of them.

### Reproduction Steps

I read in the discord that it happens to every world that is made before beta 541 once, but I dont have any clue on how to reproduce this.

### Logs

Logs cant be traced back

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
can't reproduce this with just mineoclonies, you probably got some errors in your log during entity spawn caused by another mod

**Comment by Raycoms** [comment]
please send us your latest log

**Comment by loadi-dev** [comment]
As I have the same issue with my colonies as well I tried various things.
* First I thought it might be related to performance optimizing mods, so I disabled them and started the game in single player without them. ->No success. Only 1 child was shown in the second colony (and visitors).
  * During the process another child showed up. But when I tried to spawn new citizens via commandline they directly started "invisible" (success message in the chat and listed in the townhall, but nowhere to be found and unable to recall them).
* Then I disabled all mods exluding minecolonies (and dependencies). -> No success. Same behaviour as before.

* I then started a fresh profile with only minecolonies included using version 1.1.537 and created 2 townhalls (I did 1 myself and asked a friend to create the second one via LAN). But even after upgrading to version 1.1.546 everything worked fine. So I conclude it seems to be something wrong in our save game (/world) itself. When I moved the world to a multiplayer server it also didn't work.

For me this issue was first introduced when we upgraded from 1.1.537 to 1.1.538 (released on Apr. 4th).

**Comment by Raycoms** [comment]
latest.log please

**Comment by loadi-dev** [comment]
I'm not sure what you are looking for, so I took a clean log of starting my existing world without any additional mods besides minecolonies (latest).

[latest.log](https://github.com/ldtteam/minecolonies/files/14896817/latest.log)

**Comment by Raycoms** [comment]
a log when the issue is present, yeah

**Comment by BlaccPanter** [comment]
Sam is also working on it just so you know

**Comment by Raycoms** [comment]
fixed

**Comment by Lef0u8** [comment]
How did you guys managed to fix this? Not only all my citizens disappeared but the new ones i recruit disappears the second i recruit them
