### ISSUE TITLE
[BUG] Aquatica deco upgrades are not oriented

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#9932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.566-BETA

### Structurize Version

structurize-1.20.1-1.0.731-RELEASE

### Related Mods and their Versions

stylecolonies-1.4
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal

### Current Behavior

After building and upgrading an Aquatica/infrastructure/connectors/connectorcorner1, I tried to upgrade the connector. The connector was rotated by 180 degrees from the original connector.

Level 1 connectorcorner in a test world:
![image](https://github.com/ldtteam/minecolonies/assets/34487065/e83889a5-5ea2-4f6c-b971-7fa2776cf61c)

Level 2, after clicking upgrade on the deco controller, halfway through the build:
![image](https://github.com/ldtteam/minecolonies/assets/34487065/ce6fa7ce-6099-42bd-95ce-44b4d9e1a412)

I also checked that the schematic was the right orientation in the build tool. It is. Levels 1, 2, and 5 shown.
![image](https://github.com/ldtteam/minecolonies/assets/34487065/b4da7722-fdfb-4e43-a6c1-e4f4edeb6463)
![image](https://github.com/ldtteam/minecolonies/assets/34487065/e5bc499e-12c6-4170-8eee-c56116eceaf0)
![image](https://github.com/ldtteam/minecolonies/assets/34487065/2b8ce135-4ca1-4c7d-a7a3-b102676e7bf5)

I've already updated stylecolonies and removed my local install of Aquatica.

### Expected Behavior

The connector should overlay the previous level so that they are oriented identically. 

### Reproduction Steps

1. Start a colony and a builder.
2. Build the Aquatica/infrastructure/connectors/connectorcorner1 somewhere aesthetic.
3. Upgrade that decoration by clicking "upgrade" on the deco controller.
4. Be sad that your underwater base is now flooded and the colonists can't path through it.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
I was chatting with Ray about this last night. I am CURIOUS if it could be related to the fix that @uecasm did a couple of months back. I remember him saying that only the deco controllers in the dome caps would need replacing so I never touched the ones in the compartments as they are essentially the 'roads' of aquatica.

**Comment by uecasm** [comment]
Any instance where there is a decoration controller as a "child hut" of some parent building or decoration would have needed to be replaced and rescanned.  I _think_ standalone deco controllers were safe, but I don't recall if I tested that.

**Comment by liaowangdezhuzhu** [comment]
![1](https://github.com/ldtteam/minecolonies/assets/16397637/c3610b8c-179e-4ca4-adc9-b543867fa619)
![2](https://github.com/ldtteam/minecolonies/assets/16397637/a6b1e178-d9c9-4df5-9b57-f1d886ae0380)

I also encountered this problem. As shown in the picture, I built a first-level wall using mirroring, and the first-level wall could be constructed at the correct angle. However, when I upgraded this wall to the second level, its angle changed.

### **Reproduction Steps**

1. Start a colony and a builder.
2. Build the Byzantine_for_1.20/Walls/Wall_main/wallmain1
3. Mirror button must be used once, meaning the mirror button is in the 'on' position.
4. Upgrade that decoration by clicking "upgrade" on the deco controller.

### **Anything else?**

- The only difference with this issue is that it requires using the mirror button once; if not used, the problem won't reproduce.
