### ISSUE TITLE
[BUG] structurize placeholder and etc. break with certain structures

### ISSUE THREAD

**Issue by Mysticpasta1** [ldtteam/minecolonies#9947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.516-BET

### Structurize Version

1.0.689-RELEASE

### Related Mods and their Versions

Forge Version 43.3.13

### Current Behavior

Generating certain structures by natural world gen causes structure placeholders to show up

### Expected Behavior

no structurize placeholders should show in natural world gen

### Reproduction Steps

load new world
look around for a structure

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
To give some more context from the discord discussion: This was found in the Colonial park, but seems to appear with other decorations from other styles too

**Comment by Talyda** [comment]
The Colonial Park (large one) when world genned in, places solid placeholders, instead of using them as intended 
![image](https://github.com/ldtteam/minecolonies/assets/17323101/cc0d62a3-b50d-4c50-bda6-4f5182203a2d)
 Light placeholders are showing up in Colonial fountain and paths/roads 
![image](https://github.com/ldtteam/minecolonies/assets/17323101/95dbce3e-0db9-4fd5-b86b-b7f167dc1024)

Medieval park (for example) in build tool has a layer of solid placeholders under it, but they work as expected in world gen, as did Desert Oasis fountain (though water placeholders appear as placeholders)  Incan roads in build tool have both light and dark placeholders, but they appear as expected in world gen

*edits* that is honestly all I have the energy to test right now. Seems to be mostly Colonial though

**Comment by MotionlessTrain** [comment]
It look like that e.g. the processor list in Desert Oasis has the code for replacing solid placeholders and regular placeholders in it, which is why that one seems to work correctly
Colonial, among other styles (at least Caledonia) is missing those
(Fluid placeholders are missing from Desert Oasis, as the fountain doesn't really spill water, and I haven't checked all other styles whether the placeholder code is present in the decorations and roads processors)
