### ISSUE TITLE
[BUG] Quarrier will not quarry

### ISSUE THREAD

**Issue by Putzaroo** [ldtteam/minecolonies#9950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.566-BETA

### Structurize Version

1.0.731-RELEASE

### Related Mods and their Versions

1. Forge 47.2.20 2. Domum Ornamentum 1.0186-RELEASE
All the mods 9 0.2.58

### Current Behavior

Quarry building is built and quarrier assigned. Quarrier stands at quarry hut tile and does nothing. Does not ask for items or tools. 
He is equipped with tools according to his mine level. Fired and Hired several times over.

### Expected Behavior

Quarrier is expected to begin quarrying out his quarry... 

### Reproduction Steps

1. Build a quarry (using shire). 2. Assign quarrier from mine.  3. Enjoy

### Logs

https://gist.github.com/Putzaroo/8db946617b0ef921a062665087b6d43d

### Anything else?

I have deleted the ATM configs and allowed them to repopulate with the correct settings

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Been several reports of this on discord over the past couple of weeks.

If people go to the mine and check the required resources tab, the materials in there are counting up to how many they need, then starting over and recalculating and counting again, over and over.

Someone dropped down to version .461 and the quarrier started working immediately. Here: https://discord.com/channels/139070364159311872/1003402487417548801/1237757655942955118

Someone else gave them the materials they needed, and that started them working, but as soon as they ran out, were stuck again (I think!) here: https://discord.com/channels/139070364159311872/1003402487417548801/1237566555651309679

Earliest version someone else said they saw it was 1.20.1-1.1.481 here: https://discord.com/channels/139070364159311872/1125094832143077456/1237554789655642204

**Comment by MotionlessTrain** [comment]
What I noticed in my own colony (using 1.1.571) is that only signs and torches are on the resources list, not any of the other blocks in the quarry
(This is a 9x9 simple quarry, where I just hired a quarrier in. Nothing has been done with the quarry yet)

**Comment by craft90** [comment]
I'm on Minecolonies 1.20.1 - 1.1.563 - RELEASE, and I've had issues with the quarry aswell. The modpack is highly modded. However I'd find a workaround. After some testing with just Minecolonies (Minecolonies Original Simple quarry) I realized that by giving the quarrier the materials directly into their inventory (framed cobblestone, cobblestone, torches and a stack of dirt) they seems to be working properly. By placing the quarryshaft I could check the resources and know what to give the quarrier.

I also found that the issue seem to persist in a modpack with just Minecolonies, its dependencies and some supporting mods (dymap addon, better with minecolonies, tweaks, compatibility and byzantine style pack).

At no point did the quarrier request materials, the Mine kept re-calcuating material cost and the quarrier seemingly seem to break the dirt blocks with just their fists. I'm rather confident that the issue is on Minecolonies side. Maybe somewhere in the request system?

**Comment by MotionlessTrain** [comment]
This issue is caused by the new zig-zag default iterator
The quarrier seems to start calculating resources from the row with the highest Z-value, and decrementing the iterator to get the resources of the entire layer. Previously, decrementing caused the row-by-row algorithm to go from highest Z-value to the lowest, but the zig-zag always start at Z-value 0 and goes upwards (decrementing now just means going from highest Y-level to lowest)
In particular, that means for the decoration blocks the entire X-Z plane is calculated, and for the solid and entity blocks, just one row is calculated. When the quarrier started building, they missed the first block they needed, which led them to calculate the resource list again, etc.
